### ISSUE TITLE
Connect s3 to delta lake

### ISSUE THREAD

**Issue by nampqaime** [delta-io/delta#1062]
Hello,

I want to connect s3 (not aws s3) on my device to delta lake.
I have information about "AccessKeyId", "SecretAccessKey", endpoint (ip address, port)
Looks like there are no instructions for setting this up. Please help me how to connect my s3 to delta lake.

Thank you.

**Comment by vkorukanti** [comment]
Hi @nampqaime, Looking into it. Could you please clarify `s3 (not aws s3)`. Do you mean S3 compatible storages that are not from AWS (ex. Minio)?

**Comment by vkorukanti** [comment]
Hi @nampqaime, did you try passing the Spark config for S3 described [here](https://hadoop.apache.org/docs/r2.10.1/hadoop-aws/tools/hadoop-aws/index.html#S3A_Authentication_methods)? There is also a config option for endpoint `fs.s3a.endpoint`.

**Comment by nampqaime** [comment]
Hello @vkorukanti , I try passing the Spark config for S3 following below code

`import pyspark
from delta import *
from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession
sc = SparkContext('local')
spark = SparkSession(sc)

sc=spark.sparkContext

hadoop_configuration=sc._jsc.hadoopConfiguration()
hadoop_configuration.set("fs.s3a.access.key","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
hadoop_configuration.set("fs.s3a.secret.key","bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
hadoop_configuration.set("fs.s3a.endpoint", "192.168.210.16:31665")

hadoop_configuration.set("fs.s3a.path.style.access", "true")
hadoop_configuration.set("fs.s3a.connection.ssl.enabled", "true")

rdata = spark.read.options(header='True', delimiter=',').csv("s3a://cephbucket-vhl/data/data_destination.csv")

rdata.show()

rdata.printSchema()`

but I got some error, How can I fix it, thank you.

`22/04/16 11:30:14 WARN Utils: Your hostname, nampq resolves to a loopback address: 127.0.1.1; using 192.168.2.6 instead (on interface wlp3s0)
22/04/16 11:30:14 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
22/04/16 11:30:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Traceback (most recent call last):
  File "s3a.py", line 25, in <module>
    rdata = spark.read.options(header='True', delimiter=',').csv("s3a://cephbucket-vhl/data/data_destination.csv")
  File "/home/nampq/anaconda3/envs/nampq/lib/python3.6/site-packages/pyspark/sql/readwriter.py", line 737, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/home/nampq/anaconda3/envs/nampq/lib/python3.6/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/nampq/anaconda3/envs/nampq/lib/python3.6/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/nampq/anaconda3/envs/nampq/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o29.csv.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2595)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3269)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
        at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:377)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:795)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2499)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2593)
        ... 25 more`

**Comment by nampqaime** [comment]
Hello @vkorukanti ,

I can connect to s3 with your idea, thank for your help.
