### ISSUE TITLE
[BUG] saveAsTable fails with Spark 3.2, delta 1.1.0.

### ISSUE THREAD

**Issue by brysd** [delta-io/delta#1069]
## Bug
Using spark3.2 and delta 1.1.0 fails to create managed table -> saveAsTable returns java.lang.NoSuchMethodError
There is no issue with creating the delta files.

### Describe the problem
trying to use saveAsTable or "CREATE TABLE delta using DELTA LOCATION '/path/to/files'" results in java.lang.NoSuchMethodError

code was executed as following:

``` shell
kinit -k -t path/to/mykeytab myprincipal
/usr/bin/spark3-submit --packages io.delta:delta-core_2.12:1.1.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" --num-executors 4 --principal myprincipal --keytab path/to/mykeytab delta_test.py
```

#### Steps to reproduce

Script used to test:

``` python
import pyspark
from delta.tables import *

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
from pyspark.sql.functions import col

spark = SparkSession.builder.appName('testDelta') \
	.config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
	.config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
	.getOrCreate()

# dummy data for test
data = [["mammal", "dog", "chihuahua", 100], \
		["mammal", "dog", "german shepherd", 137], \
		["mammal", "dog", "german hound", 89], \
		["insect", "butterfly", "tiger swallowtail", 5000], \
		["insect", "butterfly", "bronze copper", 5067], \
		["mammal", "cat", "american shorthair cat", 600], \
		["mammal", "cat", "abyssinian cat", 34]]

# initial schema
schema = StructType([StructField("class", StringType(), True), \
					 StructField("family", StringType(), True), \
					 StructField("breed", StringType(), True), \
					 StructField("occurrences", IntegerType(), False)])

# create spark dataframe -- this will become version 0
df = spark.createDataFrame(data, schema)

try:
	df.write.format("delta") \
		.mode("overwrite") \
		.option("userMetadata", "initial schema") \
		.option("path", "/path/to/deltafiles") \
		.saveAsTable("delta")
	print("initial attempt succeeded")

except Exception as err:
	print(f"Exception occurred: {err}")
	try:
		# try alternative -- first external & then creation of table
		df.write.format("delta") \
			.mode("overwrite") \
			.option("userMetadata", "initial schema") \
			.save("/path/to/deltafiles")
		print("delta files created")
		spark.sql("CREATE TABLE delta using DELTA LOCATION '/path/to/deltafiles'")
		print("unmanaged delta table created")
	except Exception as err:
		print(f'Exception occurred: {err}')
```

#### Observed results

Exception when executing saveAsTable:

``` text

java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.catalog.CatalogTable.<init>(Lorg/apache/spark/sql/catalyst/TableIdentifier;Lorg/apache/spark/sql/catalyst/catalog/CatalogTableType;Lorg/apache/spark/sql/catalyst/catalog/CatalogStorageFormat;Lorg/apache/spark/sql/types/StructType;Lscala/Option;Lscala/collection/Seq;Lscala/Option;Ljava/lang/String;JJLjava/lang/String;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;Lscala/Option;Lscala/collection/Seq;ZZLscala/collection/immutable/Map;Lscala/Option;)V
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.org$apache$spark$sql$delta$catalog$DeltaCatalog$$createDeltaTable(DeltaCatalog.scala:130)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog$StagedDeltaTableV2.commitStagedChanges(DeltaCatalog.scala:390)
        at org.apache.spark.sql.execution.datasources.v2.TableWriteExecHelper.$anonfun$writeToTable$1(WriteToDataSourceV2Exec.scala:487)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1496)
        at org.apache.spark.sql.execution.datasources.v2.TableWriteExecHelper.writeToTable(WriteToDataSourceV2Exec.scala:471)
        at org.apache.spark.sql.execution.datasources.v2.TableWriteExecHelper.writeToTable$(WriteToDataSourceV2Exec.scala:466)
        at org.apache.spark.sql.execution.datasources.v2.AtomicReplaceTableAsSelectExec.writeToTable(WriteToDataSourceV2Exec.scala:193)
        at org.apache.spark.sql.execution.datasources.v2.AtomicReplaceTableAsSelectExec.run(WriteToDataSourceV2Exec.scala:224)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:111)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:111)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:129)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:856)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:624)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:562)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Exception occurred: An error occurred while calling o93.saveAsTable.
```

The files are created in /path/to/deltafiles.

Exception when executing spark sql 
```sql 
CREATE TABLE delta using DELTA LOCATION '/path/to/deltafiles'
```

``` text
Exception occurred: An error occurred while calling o67.sql.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.catalog.CatalogTable.<init>(Lorg/apache/spark/sql/catalyst/TableIdentifier;Lorg/apache/spark/sql/catalyst/catalog/CatalogTableType;Lorg/apache/spark/sql/catalyst/catalog/CatalogStorageFormat;Lorg/apache/spark/sql/types/StructType;Lscala/Option;Lscala/collection/Seq;Lscala/Option;Ljava/lang/String;JJLjava/lang/String;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;Lscala/Option;Lscala/collection/Seq;ZZLscala/collection/immutable/Map;Lscala/Option;)V
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.org$apache$spark$sql$delta$catalog$DeltaCatalog$$createDeltaTable(DeltaCatalog.scala:130)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.createTable(DeltaCatalog.scala:209)
        at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:42)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:111)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:111)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
```
#### Expected results
No exceptions. 

#### Further details
Our HDFS environment applies Kerberos authentication - hence the kinit.
There is no issue with the authentication by itself -> principal user has access to the underlying path of the delta files.

### Environment information

* Delta Lake version: 1.1.0
* Spark version: 3.2.0.3.2.7170.0-49
* Scala version: 2.12.10

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

**Comment by allisonport-db** [comment]
This looks like a compatibility issue. Can you provide the output of `bash -x /usr/bin/spark3-submit ...`?

**Comment by brysd** [comment]
Hi, thanks for the feedback - sorry for late reply but was on holidays.

Anyway, back and continuing on delta:

this is the output:
```shell
+ SOURCE=/usr/bin/spark3-submit
++ dirname /usr/bin/spark3-submit
+ BIN_DIR=/usr/bin
+ '[' -h /usr/bin/spark3-submit ']'
++ readlink /usr/bin/spark3-submit
+ SOURCE=/etc/alternatives/spark3-submit
+ [[ /etc/alternatives/spark3-submit != /* ]]
+++ dirname /etc/alternatives/spark3-submit
++ cd -P /etc/alternatives
++ pwd
+ BIN_DIR=/etc/alternatives
+ '[' -h /etc/alternatives/spark3-submit ']'
++ readlink /etc/alternatives/spark3-submit
+ SOURCE=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/spark3-submit
+ [[ /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/spark3-submit != /* ]]
+++ dirname /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/spark3-submit
++ cd -P /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin
++ pwd
+ BIN_DIR=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin
+ '[' -h /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/spark3-submit ']'
+++ dirname /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/spark3-submit
++ cd -P /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin
++ pwd
+ BIN_DIR=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin
+ CDH_LIB_DIR=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/../../CDH/lib
+ LIB_DIR=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/../lib
+ export HADOOP_HOME=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/../../CDH/lib/hadoop
+ HADOOP_HOME=/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/../../CDH/lib/hadoop
+ . /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/../../CDH/lib/bigtop-utils/bigtop-detect-javahome++ BIGTOP_DEFAULTS_DIR=/etc/default
++ '[' -n /etc/default -a -r /etc/default/bigtop-utils ']'
++ JAVA11_HOME_CANDIDATES=('/usr/java/jdk-11' '/usr/lib/jvm/jdk-11' '/usr/lib/jvm/java-11-oracle')
++ OPENJAVA11_HOME_CANDIDATES=('/usr/java/jdk-11' '/usr/lib/jvm/java-11' '/usr/lib/jvm/jdk-11' '/usr/lib64/jvm/jdk-11')
++ JAVA8_HOME_CANDIDATES=('/usr/java/jdk1.8' '/usr/java/jre1.8' '/usr/lib/jvm/j2sdk1.8-oracle' '/usr/lib/jvm/j2sdk1.8-oracle/jre' '/usr/lib/jvm/java-8-oracle')
++ OPENJAVA8_HOME_CANDIDATES=('/usr/lib/jvm/java-1.8.0-openjdk' '/usr/lib/jvm/java-8-openjdk' '/usr/lib64/jvm/java-1.8.0-openjdk' '/usr/lib64/jvm/java-8-openjdk')
++ MISCJAVA_HOME_CANDIDATES=('/Library/Java/Home' '/usr/java/default' '/usr/lib/jvm/default-java' '/usr/lib/jvm/java-openjdk' '/usr/lib/jvm/jre-openjdk')
++ case ${BIGTOP_JAVA_MAJOR} in
++ JAVA_HOME_CANDIDATES=(${JAVA8_HOME_CANDIDATES[@]} ${MISCJAVA_HOME_CANDIDATES[@]} ${OPENJAVA8_HOME_CANDIDATES[@]} ${JAVA11_HOME_CANDIDATES[@]} ${OPENJAVA11_HOME_CANDIDATES[@]})
++ '[' -z '' ']'
++ for candidate_regex in '${JAVA_HOME_CANDIDATES[@]}'
+++ ls -rvd /usr/java/jdk1.8.0_232-cloudera
++ for candidate in '`ls -rvd ${candidate_regex}* 2>/dev/null`'
++ '[' -e /usr/java/jdk1.8.0_232-cloudera/bin/java ']'
++ export JAVA_HOME=/usr/java/jdk1.8.0_232-cloudera
++ JAVA_HOME=/usr/java/jdk1.8.0_232-cloudera
++ break 2
+ exec /opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/bin/../lib/spark3/bin/spark-submit --packages io.delta:delta-core_2.12:1.1.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --num-executors 4 --principal vdp@BDA2.VDAB.BE --keytab vdp2.keytab delta_unmanaged.py
:: loading settings :: url = jar:file:/opt/cloudera/parcels/SPARK3-3.2.0.3.2.7170.0-49-1.p0.18822714/lib/spark3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/dbrys1/.ivy2/cache
The jars for the packages stored in: /home/dbrys1/.ivy2/jars
io.delta#delta-core_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-ac2ec4fa-48d9-457d-940d-f29a652f8ac3;1.0
        confs: [default]
        found io.delta#delta-core_2.12;1.1.0 in central
        found org.antlr#antlr4-runtime;4.8 in central
        found org.codehaus.jackson#jackson-core-asl;1.9.13 in central
:: resolution report :: resolve 152ms :: artifacts dl 7ms
        :: modules in use:
        io.delta#delta-core_2.12;1.1.0 from central in [default]
        org.antlr#antlr4-runtime;4.8 from central in [default]
        org.codehaus.jackson#jackson-core-asl;1.9.13 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-ac2ec4fa-48d9-457d-940d-f29a652f8ac3
        confs: [default]
        0 artifacts copied, 3 already retrieved (0kB/5ms)
22/04/26 13:35:38 INFO spark.SparkContext: Running Spark version 3.2.0.3.2.7170.0-49
```

**Comment by allisonport-db** [comment]
Hi @brysd, it looks like here you are using a Cloudera version of spark. Upon further investigation, the Cloudera version has altered the interface of `CatalogTable` from Apache Spark, and added the field `accessInfo` which is causing the incompatibility issue (see below for the two different constructors).

Unfortunately we cannot help with this as Delta Lake is compatible with public Apache Spark. We recommend contacting Cloudera support for help with the issue.

Closing this for now, but feel free to reopen as appropriate.

Apache Spark constructor:
```
case class CatalogTable(
    identifier: TableIdentifier,
    tableType: CatalogTableType,
    storage: CatalogStorageFormat,
    schema: StructType,
    provider: Option[String] = None,
    partitionColumnNames: Seq[String] = Seq.empty,
    bucketSpec: Option[BucketSpec] = None,
    owner: String = "",
    createTime: Long = System.currentTimeMillis,
    lastAccessTime: Long = -1,
    createVersion: String = "",
    properties: Map[String, String] = Map.empty,
    stats: Option[CatalogStatistics] = None,
    viewText: Option[String] = None,
    comment: Option[String] = None,
    unsupportedFeatures: Seq[String] = Seq.empty,
    tracksPartitionsInCatalog: Boolean = false,
    schemaPreservesCase: Boolean = true,
    ignoredProperties: Map[String, String] = Map.empty,
    viewOriginalText: Option[String] = None) {
```

Cloudera constructor:
```
public CatalogTable(
TableIdentifier identifier, 
CatalogTableType tableType, 
CatalogStorageFormat storage, 
StructType schema, 
Option<String> provider, 
Seq<String> partitionColumnNames, 
Option<BucketSpec> bucketSpec, 
String owner, 
long createTime, 
long lastAccessTime, 
String createVersion, 
Map<String, String> properties, 
Option<CatalogStatistics> stats, 
Option<String> viewText, 
Option<String> comment, 
Seq<String> unsupportedFeatures, 
boolean tracksPartitionsInCatalog, 
boolean schemaPreservesCase, 
Map<String, String> ignoredProperties, 
Option<String> viewOriginalText, 
AccessInfo accessInfo) {
    Product.$init$(this);
  }
```

**Comment by ksmatharoo** [comment]
@brysd you can create a small project, override 2 classes of DeltaCatalog, compile with cloudera spark and use it.
for reference you can check this https://github.com/ksmatharoo/CDPDelta
