### ISSUE TITLE
DeltaMergeBuilder not handling schema order difference

### ISSUE THREAD

**Issue by guyneedhamcanva** [delta-io/delta#109]
I have a DataFrame with a schema containing userCtx, a nested field:
```
 |-- userCtx: struct (nullable = true)
 |    |-- userId: string (nullable = true)
 |    |-- brand: string (nullable = true)
 |    |-- experience: string (nullable = true)
 |    |-- experienceBrand: string (nullable = true)
 |    |-- locale: string (nullable = true)
 |    |-- experiments: map (nullable = true)
 |    |    |-- key: string
 |    |    |-- value: string (valueContainsNull = true)
 |    |-- country: string (nullable = true)
 |    |-- tier: string (nullable = true)
 |    |-- featureBundles: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
```

And a Delta Lake table with the schema:
``` 
 |-- userCtx: struct (nullable = true)
 |    |-- userId: string (nullable = true)
 |    |-- brand: string (nullable = true)
 |    |-- experience: string (nullable = true)
 |    |-- locale: string (nullable = true)
 |    |-- experiments: map (nullable = true)
 |    |    |-- key: string
 |    |    |-- value: string (valueContainsNull = true)
 |    |-- country: string (nullable = true)
 |    |-- tier: string (nullable = true)
 |    |-- featureBundles: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- experienceBrand: string (nullable = true)
```

These two schemas only differ in the order of the fields, namely `experienceBrand`. I am trying to upsert into the table, code fragment:

```
DeltaTable.forPath(datasetTablePath)
          .as("lake")
          .merge(
            lakeLanding.toDF().as("lake_landing"),
            "lake.date = lake_landing.date and lake.eventId = lake_landing.eventId")
          .whenMatched
          .updateAll()
          .whenNotMatched
          .insertAll()
          .execute()
```

I get this exception:
```
org.apache.spark.sql.AnalysisException: cannot resolve 'lake_landing.`userCtx`' due to data type mismatch: cannot cast struct<userId:string,brand:string,experience:string,experienceBrand:string,locale:string,experiments:map<string,string>,country:string,tier:string,featureBundles:array<string>> to struct<userId:string,brand:string,experience:string,locale:string,experiments:map<string,string>,country:string,tier:string,featureBundles:array<string>,experienceBrand:string>;
  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:115)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:107)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:278)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:278)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:277)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
  at org.apache.spark.sql.catalyst.trees.TreeNode.org$apache$spark$sql$catalyst$trees$TreeNode$$mapChild$2(TreeNode.scala:295)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4$$anonfun$apply$13.apply(TreeNode.scala:354)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:296)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:354)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:104)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:116)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$2.apply(QueryPlan.scala:121)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:296)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:121)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:126)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:126)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:93)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:107)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:85)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:85)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:95)
  at io.delta.tables.DeltaMergeBuilder.execute(DeltaMergeBuilder.scala:232)
```

Is it possible that the merge builder is not handling nested fields in a different order?

**Comment by marmbrus** [comment]
Yeah, I think you are correct that the field order is causing this failure. This is inconsistent with the behavior when writing into a table directly, so I would consider it a bug. I'm not sure how hard it will be to fix though.

**Comment by tdas** [comment]
I am going to try reproducing and fixint this issue.

**Comment by tdas** [comment]
@guyneedhamcanva can you give a minimalistic but end-to-end code example that reproduces this error? I am having a hard time reproducing it. Also, which version of Spark are you using?

**Comment by tdas** [comment]
@guyneedhamcanva ping

**Comment by guyneedhamcanva** [comment]
I'm going to try to reproduce the issue this week. Spark version is 2.4.3, and Delta Lake is 0.3.0.

**Comment by tdas** [comment]
I was able to reproduce the error. And I think this is the expected behavior. @marmbrus please correct me if am wrong but the expected behavior is that column order of top-level columns should not matter as we will automatically reorder the top-level columns to match the order in the table. However, in your case, the field order is different within a top-level struct column. I dont think we guarantee the same automatic reordering for nested fields. So this failure due to order mismatch of fields is not an inconsistent behavior right now, so may not be considered as a "bug"

Nonetheless, this can be considered an annoyance. Whether we should improve this behavior with respect to field names or not is a larger question because we should update all operations to provide consistent behavior nested field behavior. That is a separate feature that is worth discussing.

Internally what is happening is as follows. In the DML operations like merge and update, we automatically cast the update/insert expressions to the target column type. In this case, we are dealing with struct-type columns and by SQL standards, the two structs (with different field orders) are considered as different structs. Also by SQL standards, cast between two structs is done by mapping with field position and not field name. Furthermore, you have another complex type (i.e. `experiments`) inside the top-level struct column `userCtx`. All these together is resulting in the cast attempting to convert a scalar type field to a complex type field (or vice versa). This results in the analysis exception.

**Comment by marmbrus** [comment]
I consider this a bug since it is inconsistent with Delta's general handling of columns. In general we try to treat nested and top-level columns the same.

As an example, the following does work today: 

```
// Write #1
case class Data(a: A)
case class A(b: Int, c: Int)
val df1 = Seq(Data(A(1,2))).toDS()
df1.write.format("delta").mode("append").save("/home/michael/structs")

// Write #2
case class Data(a: A)
case class A(c: Int, b: Int)
val df2 = Seq(Data(A(1,2))).toDS()
df2.write.format("delta").mode("append").save("/home/michael/structs")
```

It is not clear to me why a merge is different than append here.

**Comment by Dexteroo7** [comment]
Hello, I am getting this in spark 3.0.0 with delta 0.7.0 as well. Here is some code to replicate the issue.
```
# here we can see that schema merge works fine for a simple append, but delta merge fails in the updated schema
# e = AnalysisException("cannot resolve 'source.`array_field`' due to data type mismatch: cannot cast array<struct<map_field...:79)\n\tat 
# py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\n", None)
def test_nested_schema_merging_fail(spark: SparkSession):
    path = "test_nested_schema_merging_fail"
    a = """
    {
      "array_field": [
        {
          "map_field": {
            "Key": {
              "string_field_b": "blah_b",
              "inner_array_field_a": [],
              "inner_array_field_b": [],
              "string_field_c": "blah_c"
            }
          }
        }
      ],
      "dt": "2020-01-02"
    }
    """
    b = """
    {
      "array_field": [
        {
          "map_field": {
            "Key": {
              "string_field_b": "blah_b",
              "inner_array_field_a": [],
              "inner_array_field_b": [],
              "inner_array_field_c": [],
              "string_field_c": "blah_c"
            }
          }
        }
      ],
      "dt": "2020-01-02"
    }
    """
    df_a = spark.read.json(spark.sparkContext.parallelize([a]))
    df_b = spark.read.json(spark.sparkContext.parallelize([b]))

    # create delta delta
    df_a.write \
        .format("delta") \
        .partitionBy("dt") \
        .save(path)
    # write data with changed schema using simple append
    df_b.write \
        .format("delta") \
        .option("mergeSchema", "true") \
        .mode("append") \
        .partitionBy("dt") \
        .save(path)
    # write data with changed schema using delta merge
    from delta.tables import DeltaTable
    target = DeltaTable.forPath(spark, path)
    target.alias("target"). \
        merge(df_b.alias("source"), "false"). \
        whenNotMatchedInsertAll(). \
        execute()
    spark.read.format("delta").load(path).coalesce(1).write.json("output_1")


# here we can see that schema merge works fine for a simple append, but delta merge produces incorrect output.
# the fields in the output are reorderd and do not map to the correct columns
def test_nested_schema_merging_fields_reordered(spark: SparkSession):
    path = "test_nested_schema_merging_fields_reordered"
    a = """
    {
      "array_field": [
        {
          "map_field": {
            "Key": {
              "string_field_b": "blah_b",
              "inner_array_field_a": [],
              "inner_array_field_b": [],
              "string_field_c": "blah_c"
            }
          }
        }
      ],
      "dt": "2020-01-02"
    }
    """
    b = """
    {
      "array_field": [
        {
          "map_field": {
            "Key": {
              "string_field_b": "blah_b",
              "inner_array_field_a": [],
              "inner_array_field_b": [],
              "string_field_a": "blah_a",
              "string_field_c": "blah_c"
            }
          }
        }
      ],
      "dt": "2020-01-02"
    }
    """
    df_a = spark.read.json(spark.sparkContext.parallelize([a]))
    df_b = spark.read.json(spark.sparkContext.parallelize([b]))

    # create delta delta
    df_a.write \
        .format("delta") \
        .partitionBy("dt") \
        .save(path)
    # write data using simple append
    df_b.write \
        .format("delta") \
        .option("mergeSchema", "true") \
        .mode("append") \
        .partitionBy("dt") \
        .save(path)
    # write data with changed schema using delta merge
    from delta.tables import DeltaTable
    target = DeltaTable.forPath(spark, path)
    target.alias("target"). \
        merge(df_b.alias("source"), "false"). \
        whenNotMatchedInsertAll(). \
        execute()
    spark.read.format("delta").load(path).coalesce(1).write.json("output_2")

```

**Comment by tdas** [comment]
This bug is still present, we havent solved it because the solution is a tricky one involving casting struct types. Let's see if we can spend some time on this before the next release.

**Comment by tdas** [comment]
0.8.0 add nested schema evolution in merge. please test out 0.8.0 if you are facing this issue.

**Comment by dennyglee** [comment]
Pure FYI - please refer to [Automatically Evolve Your Nested Column Schema, Stream From a Delta Table Version, and Check Your Constraints](https://databricks.com/blog/2021/02/10/automatically-evolve-your-nested-column-schema-stream-from-a-delta-table-version-and-check-your-constraints.html) for more information.
