### ISSUE TITLE
xxx.dfs.core.windows.net not found in running [BUG]

### ISSUE THREAD

**Issue by kongluo** [delta-io/delta#1093]
Delta lake uses data lake storage gen2 for storage and generates an error of xxx.dfs.core.windows.net not found. The error occurs after the program runs for a few days, and it suddenly appears during normal operation. question.

------------------->
Configuration property xxx.dfs.core.windows.net not found.
	at org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:342) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:812) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:149) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:108) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.parquet.hadoop.util.HadoopOutputFile.fromPath(HadoopOutputFile.java:58) ~[parquet-hadoop-1.10.1.jar:1.10.1]
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:389) ~[parquet-hadoop-1.10.1.jar:1.10.1]
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:349) ~[parquet-hadoop-1.10.1.jar:1.10.1]
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetOutputWriter.scala:36) ~[spark-sql_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anon$1.newInstance(ParquetFileFormat.scala:149) ~[spark-sql_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.sql.delta.Checkpoints$.$anonfun$writeCheckpoint$2(Checkpoints.scala:286) ~[?:?]
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.1.1.ja
<-------------------

According to the documentation of hadoop-azure, the problem is caused by the wrong url, but there is no problem with my url, because the program can run normally, and it has been running for a few days, and the log can be queried that the problem will occur frequently Generated, but sometimes the executor will retry successfully, and sometimes the executor will fail to retry and cause the entire task to fail

According to the official documentation of delta lake connecting to data lake storage gen2, the connection is using oAuth, but my connection method is using shareKey

            String accountName = conf.get("spark.sensor.storage.azure.accountName", "");
            String accountKey = conf.get("spark.sensor.storage.azure.accountKey", "");
            String system = conf.get("spark.sensor.storage.azure.system", "");
            conf.set("spark.delta.logStore.class", "org.apache.spark.sql.delta.storage.AzureLogStore");
            conf.set("fs.azure.account.auth.type." + accountName + ".dfs.core.windows.net", "SharedKey");
            conf.set("fs.azure.account.key." + accountName + ".dfs.core.windows.net", accountKey);
            conf.set("fs.azure.enable.flush", "true");
            conf.set("fs.azure.enable.check.access", "true");

Does it have anything to do with this?

Environment information
Azure data lake storage gen2
Delta Lake version: 1.0.0
Spark version: 3.1.2
Hadoop version: 3.2.0
Scala version: 2.12

**Comment by zsxwing** [comment]
@kongluo do you have concurrent queries in the same Spark applications and each query itself may modify `conf`?

**Comment by kongluo** [comment]
> @kongluo do you have concurrent queries in the same Spark applications and each query itself may modify `conf`?

No, there is only one spark task to consume kafka data, and then write to data lake storage gen2, no other tasks

**Comment by kongluo** [comment]
> @kongluo do you have concurrent queries in the same Spark applications and each query itself may modify `conf`?

Does it have anything to do with the connection method with the data lake storage gen2? This problem was not found when the amount of data was small, and it would appear every few days when the amount of data was large

**Comment by zsxwing** [comment]
> Does it have anything to do with the connection method with the data lake storage gen2?

I'm not familiar with the code inside hadoop-azure. But will try to help go through the Spark and Delta Lake part to see if it's a bug in Spark or Delta Lake.

Could you provide the entire stack trace? When Spark throws an exception like this, it should also have a stack trace in the driver.

**Comment by kongluo** [comment]
> > Does it have anything to do with the connection method with the data lake storage gen2?
> 
> I'm not familiar with the code inside hadoop-azure. But will try to help go through the Spark and Delta Lake part to see if it's a bug in Spark or Delta Lake.
> 
> Could you provide the entire stack trace? When Spark throws an exception like this, it should also have a stack trace in the driver.

I am using structured streaming to process delta lake data to data
lake storage gen2, the driver does not print some error messages, only the above error messages. After the above errors occur, the driver and executor still exist, but the task status of the Streaming query will change from running to finishing

**Comment by zsxwing** [comment]
I'm wondering if you are able to share the logs around the error message. In addition, could you provide your code if possible?

**Comment by kongluo** [comment]
> I'm wondering if you are able to share the logs around the error message. In addition, could you provide your code if possible?

--------------------->
    val conf: SparkConf = new SparkConf()
      .set("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
      .set("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
      .setAppName(SENSOR_STREAMING)
//          .setMaster("local[*]")

    conf.set("spark.delta.logStore.class", "org.apache.spark.sql.delta.storage.AzureLogStore")
    conf.set("fs.azure.account.auth.type." + accountName + ".dfs.core.windows.net", "SharedKey");
    conf.set("fs.azure.account.key." + accountName + ".dfs.core.windows.net", xxx);
    conf.set("fs.azure.enable.flush", "true");
    conf.set("fs.azure.enable.check.access", "true");


    val spark = SparkSession
      .builder()
      .config(conf)
      .getOrCreate()

    spark.sparkContext.setLogLevel("INFO")

    val TABLE_LOCATION: String = "abfss://xxx@xxx.dfs.core.windows.net/xxx"
    val checkpointLocation: String = "abfss://xxx@xxx.dfs.core.windows.net/xxx"

    import spark.implicits._
    val sourceDF: DataFrame = spark.readStream
      .format("kafka")
      .option("kafka.bootstrap.servers", KafkaUtil.getKafkaServers(spark))
      .option("subscribe", "xxx")
      .option("maxOffsetsPerTrigger","20000")
      .load()
      .mapPartitions(par => {
        par.map(data => {
          DeltaUtil.transformData(data) //change data
        })
      })
      .filter(_._2 != null)
      .toDF(ID, VALUE, TIMESTAMP)
      .withColumn(S_TIME, get_json_object(col(VALUE), PATH_STIME).cast(DataTypes.LongType))
      .withColumn(PRODUCT_NAME, get_json_object(col(VALUE), PATH_PRODUCTNAME))
      .withColumn(PARTITION_DAY, from_unixtime(get_json_object(col(VALUE), PATH_STIME) / 1000, YYYY_MM_DD))

    val query: StreamingQuery = sourceDF.writeStream
      .format("delta")
      .trigger(Trigger.ProcessingTime("40000"))
      .outputMode(OutputMode.Append())
      .option("mergeSchema", "true")
      .partitionBy(PRODUCT_NAME, PARTITION_DAY)
      .option("checkpointLocation", checkpointLocation)
      .start(TABLE_LOCATION)

    query.awaitTermination()
    spark.close()
  <------------------------------

I filtered out some sensitive information, the overall operation is like this, that is, structured streaming consumes the data in kafka, after some transformation of the data, it is directly stored in the data lake storage gen2 through the format of delta lake

**Comment by kongluo** [comment]
> I'm wondering if you are able to share the logs around the error message. In addition, could you provide your code if possible?

the logs is :

--------------->
	{"instant":{"epochSecond":1650520466,"nanoOfSecond":189222000},"thread":"Executor task launch worker for task 0.0 in stage 88.0 (TID 1327)","level":"INFO","loggerName":"org.apache.parquet.hadoop.ParquetOutputFormat","message":"Parquet block size to 134217728","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
	{"instant":{"epochSecond":1650520466,"nanoOfSecond":189536000},"thread":"Executor task launch worker for task 0.0 in stage 88.0 (TID 1327)","level":"INFO","loggerName":"org.apache.parquet.hadoop.ParquetOutputFormat","message":"Max row count for page size check is: 10000","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
	{"instant":{"epochSecond":1650520466,"nanoOfSecond":189469000},"thread":"Executor task launch worker for task 0.0 in stage 88.0 (TID 1327)","level":"INFO","loggerName":"org.apache.parquet.hadoop.ParquetOutputFormat","message":"Page size checking is: estimated","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
	{"instant":{"epochSecond":1650520466,"nanoOfSecond":231847000},"thread":"Executor task launch worker for task 0.0 in stage 88.0 (TID 1327)","level":"INFO","loggerName":"org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport","message":"Initialized Parquet WriteSupport with Catalyst schema:\n{\n  \"type\" : \"struct\",\n  \"fields\" : [ {\n    \"name\" : \"txn\",\n    \"type\" : {\n      \"type\" : \"struct\",\n      \"fields\" : [ {\n        \"name\" : \"appId\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"version\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"lastUpdated\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      } ]\n    },\n    \"nullable\" : true,\n    \"metadata\" : { }\n  }, {\n    \"name\" : \"add\",\n    \"type\" : {\n      \"type\" : \"struct\",\n      \"fields\" : [ {\n        \"name\" : \"path\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"partitionValues\",\n        \"type\" : {\n          \"type\" : \"map\",\n          \"keyType\" : \"string\",\n          \"valueType\" : \"string\",\n          \"valueContainsNull\" : true\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"size\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"modificationTime\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"dataChange\",\n        \"type\" : \"boolean\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"tags\",\n        \"type\" : {\n          \"type\" : \"map\",\n          \"keyType\" : \"string\",\n          \"valueType\" : \"string\",\n          \"valueContainsNull\" : true\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"stats\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"partitionValues_parsed\",\n        \"type\" : {\n          \"type\" : \"struct\",\n          \"fields\" : [ {\n            \"name\" : \"product_name\",\n            \"type\" : \"string\",\n            \"nullable\" : true,\n            \"metadata\" : { }\n          }, {\n            \"name\" : \"partition_day\",\n            \"type\" : \"string\",\n            \"nullable\" : true,\n            \"metadata\" : { }\n          } ]\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      } ]\n    },\n    \"nullable\" : true,\n    \"metadata\" : { }\n  }, {\n    \"name\" : \"remove\",\n    \"type\" : {\n      \"type\" : \"struct\",\n      \"fields\" : [ {\n        \"name\" : \"path\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"deletionTimestamp\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"dataChange\",\n        \"type\" : \"boolean\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"extendedFileMetadata\",\n        \"type\" : \"boolean\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"partitionValues\",\n        \"type\" : {\n          \"type\" : \"map\",\n          \"keyType\" : \"string\",\n          \"valueType\" : \"string\",\n          \"valueContainsNull\" : true\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"size\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"tags\",\n        \"type\" : {\n          \"type\" : \"map\",\n          \"keyType\" : \"string\",\n          \"valueType\" : \"string\",\n          \"valueContainsNull\" : true\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      } ]\n    },\n    \"nullable\" : true,\n    \"metadata\" : { }\n  }, {\n    \"name\" : \"metaData\",\n    \"type\" : {\n      \"type\" : \"struct\",\n      \"fields\" : [ {\n        \"name\" : \"id\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"name\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"description\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"format\",\n        \"type\" : {\n          \"type\" : \"struct\",\n          \"fields\" : [ {\n            \"name\" : \"provider\",\n            \"type\" : \"string\",\n            \"nullable\" : true,\n            \"metadata\" : { }\n          }, {\n            \"name\" : \"options\",\n            \"type\" : {\n              \"type\" : \"map\",\n              \"keyType\" : \"string\",\n              \"valueType\" : \"string\",\n              \"valueContainsNull\" : true\n            },\n            \"nullable\" : true,\n            \"metadata\" : { }\n          } ]\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"schemaString\",\n        \"type\" : \"string\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"partitionColumns\",\n        \"type\" : {\n          \"type\" : \"array\",\n          \"elementType\" : \"string\",\n          \"containsNull\" : true\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"configuration\",\n        \"type\" : {\n          \"type\" : \"map\",\n          \"keyType\" : \"string\",\n          \"valueType\" : \"string\",\n          \"valueContainsNull\" : true\n        },\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"createdTime\",\n        \"type\" : \"long\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      } ]\n    },\n    \"nullable\" : true,\n    \"metadata\" : { }\n  }, {\n    \"name\" : \"protocol\",\n    \"type\" : {\n      \"type\" : \"struct\",\n      \"fields\" : [ {\n        \"name\" : \"minReaderVersion\",\n        \"type\" : \"integer\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      }, {\n        \"name\" : \"minWriterVersion\",\n        \"type\" : \"integer\",\n        \"nullable\" : true,\n        \"metadata\" : { }\n      } ]\n    },\n    \"nullable\" : true,\n    \"metadata\" : { }\n  } ]\n}\nand corresponding Parquet message type:\nmessage spark_schema {\n  optional group txn {\n    optional binary appId (UTF8);\n    optional int64 version;\n    optional int64 lastUpdated;\n  }\n  optional group add {\n    optional binary path (UTF8);\n    optional group partitionValues (MAP) {\n      repeated group key_value {\n        required binary key (UTF8);\n        optional binary value (UTF8);\n      }\n    }\n    optional int64 size;\n    optional int64 modificationTime;\n    optional boolean dataChange;\n    optional group tags (MAP) {\n      repeated group key_value {\n        required binary key (UTF8);\n        optional binary value (UTF8);\n      }\n    }\n    optional binary stats (UTF8);\n    optional group partitionValues_parsed {\n      optional binary product_name (UTF8);\n      optional binary partition_day (UTF8);\n    }\n  }\n  optional group remove {\n    optional binary path (UTF8);\n    optional int64 deletionTimestamp;\n    optional boolean dataChange;\n    optional boolean extendedFileMetadata;\n    optional group partitionValues (MAP) {\n      repeated group key_value {\n        required binary key (UTF8);\n        optional binary value (UTF8);\n      }\n    }\n    optional int64 size;\n    optional group tags (MAP) {\n      repeated group key_value {\n        required binary key (UTF8);\n        optional binary value (UTF8);\n      }\n    }\n  }\n  optional group metaData {\n    optional binary id (UTF8);\n    optional binary name (UTF8);\n    optional binary description (UTF8);\n    optional group format {\n      optional binary provider (UTF8);\n      optional group options (MAP) {\n        repeated group key_value {\n          required binary key (UTF8);\n          optional binary value (UTF8);\n        }\n      }\n    }\n    optional binary schemaString (UTF8);\n    optional group partitionColumns (LIST) {\n      repeated group list {\n        optional binary element (UTF8);\n      }\n    }\n    optional group configuration (MAP) {\n      repeated group key_value {\n        required binary key (UTF8);\n        optional binary value (UTF8);\n      }\n    }\n    optional int64 createdTime;\n  }\n  optional group protocol {\n    optional int32 minReaderVersion;\n    optional int32 minWriterVersion;\n  }\n}\n\n       ","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
{"instant":{"epochSecond":1650520466,"nanoOfSecond":335283000},"thread":"Executor task launch worker for task 0.1 in stage 88.0 (TID 1328)","level":"INFO","loggerName":"org.apache.spark.executor.Executor","message":"Running task 0.1 in stage 88.0 (TID 1328)","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
{"instant":{"epochSecond":1650520466,"nanoOfSecond":334983000},"thread":"dispatcher-Executor","level":"INFO","loggerName":"org.apache.spark.executor.CoarseGrainedExecutorBackend","message":"Got assigned task 1328","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
{"instant":{"epochSecond":1650520466,"nanoOfSecond":336527000},"thread":"Executor task launch worker for task 0.1 in stage 88.0 (TID 1328)","level":"INFO","loggerName":"org.apache.spark.broadcast.TorrentBroadcast","message":"Started reading broadcast variable 154 with 1 pieces (estimated total size 4.0 MiB)","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
{"instant":{"epochSecond":1650520466,"nanoOfSecond":335899000},"thread":"Executor task launch worker for task 0.1 in stage 88.0 (TID 1328)","level":"INFO","loggerName":"org.apache.spark.MapOutputTrackerWorker","message":"Updating epoch to 54 and clearing cache","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
	org.apache.hadoop.fs.azurebfs.contracts.exceptions.ConfigurationPropertyNotFoundException: Configuration property xxx.dfs.core.windows.net not found.
	at org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:342) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:812) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:149) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:108) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.spark.sql.delta.util.DeltaFileOperations$.$anonfun$registerTempFileDeletionTaskFailureListener$1(DeltaFileOperations.scala:331) ~[?:?]
	at org.apache.spark.sql.delta.util.DeltaFileOperations$.$anonfun$registerTempFileDeletionTaskFailureListener$1$adapted(DeltaFileOperations.scala:328) ~[?:?]
	at org.apache.spark.TaskContext$$anon$2.onTaskFailure(TaskContext.scala:141) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.TaskContextImpl.$anonfun$markTaskFailed$1(TaskContextImpl.scala:115) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.TaskContextImpl.$anonfun$markTaskFailed$1$adapted(TaskContextImpl.scala:115) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1(TaskContextImpl.scala:137) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1$adapted(TaskContextImpl.scala:135) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49) ~[scala-library-2.12.10.jar:?]
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:135) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.TaskContextImpl.markTaskFailed(TaskContextImpl.scala:115) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:136) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
{"instant":{"epochSecond":1650520466,"nanoOfSecond":338821000},"thread":"Executor task launch worker for task 0.1 in stage 88.0 (TID 1328)","level":"INFO","loggerName":"org.apache.spark.storage.memory.MemoryStore","message":"Block broadcast_154_piece0 stored as bytes in memory (estimated size 82.3 KiB, free 3.7 GiB)","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
{"instant":{"epochSecond":1650520466,"nanoOfSecond":339448000},"thread":"Executor task launch worker for task 0.1 in stage 88.0 (TID 1328)","level":"INFO","loggerName":"org.apache.spark.broadcast.TorrentBroadcast","message":"Reading broadcast variable 154 took 2 ms","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
org.apache.hadoop.fs.azurebfs.contracts.exceptions.ConfigurationPropertyNotFoundException: Configuration property xxx.dfs.core.windows.net not found.
	at org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:342) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:812) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:149) ~[?:?]
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:108) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361) ~[hadoop-common-3.2.0.jar:?]
	at org.apache.parquet.hadoop.util.HadoopOutputFile.fromPath(HadoopOutputFile.java:58) ~[parquet-hadoop-1.10.1.jar:1.10.1]
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:389) ~[parquet-hadoop-1.10.1.jar:1.10.1]
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:349) ~[parquet-hadoop-1.10.1.jar:1.10.1]
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetOutputWriter.scala:36) ~[spark-sql_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anon$1.newInstance(ParquetFileFormat.scala:149) ~[spark-sql_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.sql.delta.Checkpoints$.$anonfun$writeCheckpoint$2(Checkpoints.scala:286) ~[?:?]
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:131) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
{"instant":{"epochSecond":1650520466,"nanoOfSecond":340008000},"thread":"Executor task launch worker for task 0.1 in stage 88.0 (TID 1328)","level":"INFO","loggerName":"org.apache.spark.storage.memory.MemoryStore","message":"Block broadcast_154 stored as values in memory (estimated size 323.2 KiB, free 3.7 GiB)","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":13,"threadPriority":5}
<-------------

I also desensitized the log, and our log is converted into json format. I shared the log before and after the error report.

**Comment by zsxwing** [comment]
@kongluo thanks for the stack trace. I think you are hitting a issue that has been fixed in 1.0.1: https://github.com/delta-io/delta/commit/61763fe9d404532b534ac1e16998a0d6e905bbba Could you try 1.0.1 and see if the issue still happens?

**Comment by zsxwing** [comment]
Closing this as the issue has been fixed in 1.0.1. Feel free to re-open this issue if you still see the issue after upgrading to 1.0.1.

**Comment by kongluo** [comment]
> @kongluo thanks for the stack trace. I think you are hitting a issue that has been fixed in 1.0.1: [61763fe](https://github.com/delta-io/delta/commit/61763fe9d404532b534ac1e16998a0d6e905bbba) Could you try 1.0.1 and see if the issue still happens?

After I upgraded to 1.0.1, I observed it for a few days, and no errors were reported so far. Thank you very much for your reply.
