### ISSUE TITLE
[Feature Request] Spark 3.3 support

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [delta-io/delta#1217]
Spark 3.3 support :)

**Comment by harupy** [comment]
Not sure if this is an incompatibility with spark 3.3, but the following code

```python
from pyspark.sql import SparkSession

spark_session = (
    SparkSession.builder.master("local[*]")
    .config("spark.jars.packages", "io.delta:delta-core_2.12:1.2.1")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .getOrCreate()
)

d = [{"name": "Alice", "age": 1}]
df1 = spark_session.createDataFrame(d)
df1.createOrReplaceTempView("table1")
spark_session.sql("SELECT * from table1").show()
```

fails with:

```
#10 15.50 Traceback (most recent call last):
#10 15.50   File "a.py", line 13, in <module>
#10 15.50     spark_session.sql("SELECT * from table1").show()
#10 15.50   File "/usr/local/lib/python3.7/site-packages/pyspark/sql/session.py", line 1034, in sql
#10 15.50     return DataFrame(self._jsparkSession.sql(sqlQuery), self)
#10 15.50   File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
#10 15.50     answer, self.gateway_client, self.target_id, self.name)
#10 15.50   File "/usr/local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
#10 15.50     return f(*a, **kw)
#10 15.50   File "/usr/local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
#10 15.50     format(target_id, ".", name), value)
#10 15.50 py4j.protocol.Py4JJavaError: An error occurred while calling o31.sql.
#10 15.50 : java.lang.NoSuchMethodError: 'java.lang.Object org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(org.antlr.v4.runtime.ParserRuleContext, scala.Function0)'
#10 15.50       at io.delta.sql.parser.DeltaSqlAstBuilder.visitSingleStatement(DeltaSqlParser.scala:233)
#10 15.50       at io.delta.sql.parser.DeltaSqlAstBuilder.visitSingleStatement(DeltaSqlParser.scala:146)
#10 15.50       at io.delta.sql.parser.DeltaSqlBaseParser$SingleStatementContext.accept(DeltaSqlBaseParser.java:165)
#10 15.50       at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
#10 15.50       at io.delta.sql.parser.DeltaSqlParser.$anonfun$parsePlan$1(DeltaSqlParser.scala:74)
#10 15.50       at io.delta.sql.parser.DeltaSqlParser.parse(DeltaSqlParser.scala:103)
#10 15.50       at io.delta.sql.parser.DeltaSqlParser.parsePlan(DeltaSqlParser.scala:73)
#10 15.50       at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:620)
#10 15.50       at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
#10 15.50       at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:620)
#10 15.50       at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
#10 15.50       at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
#10 15.50       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#10 15.50       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#10 15.50       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#10 15.50       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#10 15.50       at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
#10 15.50       at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
#10 15.50       at py4j.Gateway.invoke(Gateway.java:282)
#10 15.50       at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
#10 15.50       at py4j.commands.CallCommand.execute(CallCommand.java:79)
#10 15.50       at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
#10 15.50       at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
#10 15.50       at java.base/java.lang.Thread.run(Thread.java:829)
#10 15.50 
#10 ERROR: executor failed running [/bin/sh -c python a.py]: exit code: 1
```

**Comment by tdas** [comment]
Yeah, we will start working on this soon :)
