### ISSUE TITLE
[BUG] throw error when creating DeltaTable by `file://` uri

### ISSUE THREAD

**Issue by HuaHuaY** [delta-io/delta#1523]
### Describe the problem

As the title. When creating DeltaTable by `DeltaTable.createIfNotExists(spark).location("file://xxx")`, program will throw error.

#### Steps to reproduce

run this program:
```java
import io.delta.tables.*;
import org.apache.spark.sql.*;
import java.nio.file.Paths;

public class Main {
    public static void main(String[] args) {
        SparkSession spark = SparkSession.builder().master("local")
                .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
                .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
                .getOrCreate();
        String location = "file://" + Paths.get("delta").toAbsolutePath();
        DeltaTable deltaTable = DeltaTable.createIfNotExists(spark)
                .location(location)
                .addColumn("id", "INT")
                .execute();
    }
}
```

#### Observed results

throw error.
```java
Exception in thread "main" org.apache.spark.sql.delta.DeltaAnalysisException: CREATE TABLE contains two different locations: file:///Users/xxx/test_delta_lake_java/delta and file:/Users/xxx/test_delta_lake_java/delta.
You can remove the LOCATION clause from the CREATE TABLE statement, or set
spark.databricks.delta.legacy.allowAmbiguousPathsInCreateTable to true to skip this check.

	at org.apache.spark.sql.delta.DeltaErrorsBase.ambiguousPathsInCreateTableException(DeltaErrors.scala:2031)
	at org.apache.spark.sql.delta.DeltaErrorsBase.ambiguousPathsInCreateTableException$(DeltaErrors.scala:2030)
	at org.apache.spark.sql.delta.DeltaErrors$.ambiguousPathsInCreateTableException(DeltaErrors.scala:2489)
	at org.apache.spark.sql.delta.catalog.DeltaCatalog.$anonfun$createDeltaTable$1(DeltaCatalog.scala:112)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:139)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:137)
	at org.apache.spark.sql.delta.catalog.DeltaCatalog.recordFrameProfile(DeltaCatalog.scala:58)
	at org.apache.spark.sql.delta.catalog.DeltaCatalog.org$apache$spark$sql$delta$catalog$DeltaCatalog$$createDeltaTable(DeltaCatalog.scala:86)
	at org.apache.spark.sql.delta.catalog.DeltaCatalog.$anonfun$createTable$1(DeltaCatalog.scala:255)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:139)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:137)
	at org.apache.spark.sql.delta.catalog.DeltaCatalog.recordFrameProfile(DeltaCatalog.scala:58)
	at org.apache.spark.sql.delta.catalog.DeltaCatalog.createTable(DeltaCatalog.scala:247)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:45)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:121)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:118)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:136)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:154)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:151)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:106)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at io.delta.tables.DeltaTableBuilder.execute(DeltaTableBuilder.scala:362)
	at org.example.Main.main(Main.java:17)
```

#### Expected results

run successfully

#### Further details

To trigger this bug, several conditions need to be met:
1. There is not a old table at this path.
    It only happens when creating table but not opening table.
2. Uri starts from `file://` but not `file:`
    For example, it will throw error when using "file:///Users/xxx", but run successfully when using "file:/Users/xxx"
3. The table created doesn't have table name.
    It will run successfully if we change the last line code:
    ```java
        DeltaTable deltaTable = DeltaTable.createIfNotExists(spark)
        .location(location)
        .addColumn("id", "INT")
        .tableName("tmp")
        .execute();
    ```

### Environment information

* Delta Lake version: 2.2.0
* Spark version:
* Scala version:

maven file:
```maven
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>test_delta_lake_java</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-core_2.12</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.12</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-aws</artifactId>
            <version>3.3.1</version>
        </dependency>
    </dependencies>
</project>
```

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

**Comment by allisonport-db** [comment]
Thanks for the details. Not sure on a timeline for investigating this but will try to take a look!

**Comment by brayanjuls** [comment]
@allisonport-db  - hey! are you already working on this issue? I would like to help solve this issue.

**Comment by allisonport-db** [comment]
Not at the moment, please go ahead and take a look @brayanjuls

**Comment by brayanjuls** [comment]
@allisonport-db - I manage to reproduce the error and tracked the issue back to spark.

First I want to mention that the actual URI starts like this "file:///" because the call to `Paths.get("delta").toAbsolutePath()` adds an additional slash. If the URI starts with only two slashes "file://" it would throw the following error, `Wrong FS: file://....., expected: file:///`.

 Going back to the error shown in this issue, In spark 3.3.x when the logical plan uses the [DataSourceV2Strategy](https://github.com/apache/spark/blob/7e90f4226dd5e4fae1af5e88a334d87b330019cb/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DataSourceV2Strategy.scala#L171) strategy and calls the function [qualifyLocInTableSpec](https://github.com/apache/spark/blob/7e90f4226dd5e4fae1af5e88a334d87b330019cb/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DataSourceV2Strategy.scala#L101), it changes(qualify) the location property from a string to a Hadoop path object and then turns it back into a string, that removes two slashes from the URI schema and makes it different from the location that it stored in the identifier object, that's why [this validation fails](https://github.com/delta-io/delta/blob/1c18c1d972e37d314711b3a485e6fb7c98fce96d/core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala#L105) because the location in the table property is different from the location in the identifier. 

This happens for createIfNotExists, createOrReplace, and create operation.

Maybe we could qualify the identifier location as well to avoid this error, what do you think?

**Comment by foss-contributor** [comment]
@HuaHuaY, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
