### ISSUE TITLE
How to create delta table with existing parquet file.

### ISSUE THREAD

**Issue by sanjiv1980** [delta-io/delta#157]
I have existing parquet file , when I am creating delta-table out of that and trying to update one of the column , Its giving me error below
```
Exception in thread "main" org.apache.spark.sql.catalyst.analysis.UnresolvedException: Invalid call to dataType on unresolved object, tree: 'Hello
	at org.apache.spark.sql.catalyst.analysis.UnresolvedAttribute.dataType(unresolved.scala:105)
	at org.apache.spark.sql.catalyst.expressions.BinaryArithmetic.dataType(arithmetic.scala:119)
	at org.apache.spark.sql.delta.UpdateExpressionsSupport$class.castIfNeeded(UpdateExpressionsSupport.scala:43)
	at org.apache.spark.sql.delta.PreprocessTableUpdate.castIfNeeded(PreprocessTableUpdate.scala:26)
	at org.apache.spark.sql.delta.UpdateExpressionsSupport$$anonfun$generateUpdateExpressions$2.apply(UpdateExpressionsSupport.scala:111)
	at org.apache.spark.sql.delta.UpdateExpressionsSupport$$anonfun$generateUpdateExpressions$2.apply(UpdateExpressionsSupport.scala:91)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at org.apache.spark.sql.delta.UpdateExpressionsSupport$class.generateUpdateExpressions(UpdateExpressionsSupport.scala:91)
	at org.apache.spark.sql.delta.PreprocessTableUpdate.generateUpdateExpressions(PreprocessTableUpdate.scala:26)
	at org.apache.spark.sql.delta.UpdateExpressionsSupport$class.generateUpdateExpressions(UpdateExpressionsSupport.scala:152)
	at org.apache.spark.sql.delta.PreprocessTableUpdate.generateUpdateExpressions(PreprocessTableUpdate.scala:26)
	at org.apache.spark.sql.delta.PreprocessTableUpdate.apply(PreprocessTableUpdate.scala:38)
	at io.delta.tables.execution.DeltaTableOperations$class.executeUpdate(DeltaTableOperations.scala:88)
	at io.delta.tables.DeltaTable.executeUpdate(DeltaTable.scala:41)
	at io.delta.tables.DeltaTable.updateExpr(DeltaTable.scala:358)
	at com.espn.deltalake.Test.main(Test.java:99)```

It seems like I am comparing binary to string , It seems like parquet compression happened twiced .

**Comment by marmbrus** [comment]
Can you please include the code that you are running as well?

**Comment by sanjiv1980** [comment]
Please find the below code.
```
SparkSession spark = SparkSession
	            .builder()
	            .config(conf)
	            .getOrCreate();
DataFrameReader dataFrameReader = spark.read();
Dataset<Row> pData = dataFrameReader.parquet("/Users/part-00000-2880a70c-5498-4678-838b-5c55e72d7ee0-c000.snappy.parquet");
		pData.write().format("delta").save("delta-table");
		DeltaTable deltaTable = DeltaTable.forPath("delta-table");
		Map<String,String> updateRecords = new HashMap<String, String>();	
		updateRecords.put("myid", "Hello-world");
		deltaTable.updateExpr("myid == \"BDBDEDF3-1166-ABCDEABD\"", updateRecords );
```

**Comment by tdas** [comment]
Since you are using the string version update, that is, deltaTable.updateExpr(), you have think every string as a  sql expression."Hello-world" is interpreted as an expression, i.e., interpreted as column names, and is throwing a resolution error. Please wrap the string value in single quotes within the java string. So use one of the approaches

'''
// Option 1: wrap string value in single quotes
Map<String,String> updateRecords = new HashMap<String, String>();	
updateRecords.put("myid", "  'Hello-world' ");    // single quotes

// Option 2: use SQL functions
import org.apache.spark.sql.functions._

Map<String,Column> updateRecords = new HashMap<String, Column>();	
updateRecords.put("myid",  lit("Hello-world"));    // lit() is a spark sql function
```

**Comment by sanjiv1980** [comment]
Thanks @tdas
