### ISSUE TITLE
[BUG]: Unable to update schema using DeltaLake DeltaMergeBuilder (Python API v2.2.0)

### ISSUE THREAD

**Issue by keenborder786** [delta-io/delta#1619]
I am using DeltaMergeBuilder to perform upsert operation on my delta lake table. However, the source schema can change i.e new columns can be added to my source data frame. Therefore my delta lake tables need to update themselves and add the new underlying columns. According to the ![documentation](https://docs.delta.io/latest/delta-update.html#automatic-schema-evolution), I need to update my spark configuration which I did and use 'insertAll'/'updateAll' operation.

 ```python 
delta_lake_table.alias("main_table").merge(
            latest_changes_delete_create_df.alias(
                "update_table"), merge_condition
        ).whenMatchedDelete(condition="update_table.op = 'd'").whenNotMatchedInsertAll(
            condition="update_table.op = 'c' OR update_table.op = 'r'"
        ).execute()
        # update operation
        delta_lake_table.alias("main_table").merge(
            latest_changes_update_df.alias("update_table"), merge_condition
        ).whenMatchedUpdateAll(
            condition="update_table.op = 'u' OR update_table.op = 'r'"
        ).execute()
```

- ***delta_lake_table***: My target Dataframe
- ***latest_changes_delete_create_df***: My target Dataframe consists of ids that need to be either deleted or inserted.
- ***latest_changes_update_df***: My target Dataframe consists of ids whose values need to be updated.

***FYI*** : You might think why I am performing delete/insert and updates in two different actions. This is because each of my sources Dataframe contains streaming **CDC** data, therefore, performing a delete/insert and updates independently is a necessity otherwise I might lose data.

#### Observed results
Now when a new column comes in despite all of the right configurations, I am facing the following error:

```
 pyspark.sql.utils.AnalysisException: The schema of your Delta table has changed in an incompatible way since your DataFrame
or DeltaTable object was created. Please redefine your DataFrame or DeltaTable object.
Changes:
Latest schema has additional field(s): new_col
```
#### Expected results

new_col gets added to the underlying delta lake table without any error.

#### Further details

The above DeltaMergeBuilder is being called in ![foreachBatch](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.streaming.DataStreamWriter.foreachBatch.html#pyspark.sql.streaming.DataStreamWriter.foreachBatch) function where source Dataframe is a streaming data frame for which a foreachBatch function is called.

### Environment information

* Delta Lake version: 2.2.0
* Python version: 3.9.1.5
* Spark version: 3.3.1
* Scala version: 2.12.15
* Delta Lake tables are being stored on Minio Storage (RELEASE.2022-11-26)

### Willingness to contribute

- No. I cannot contribute a bug fix at this time.

**Comment by keenborder786** [comment]
any updates.

**Comment by scottsand-db** [comment]
Hi @keenborder786 - thanks for making this issue. Would you mind providing a small mock data set for us to reproduce this issue?

**Comment by watfordkcf** [comment]
We had _exactly_ this same error with a CDC workflow, and the fix was the following:
```patch
       delta_lake_table.alias("main_table").merge(
           latest_changes_delete_create_df.alias(
               "update_table"), merge_condition
       ).whenMatchedDelete(condition="update_table.op = 'd'").whenNotMatchedInsertAll(
           condition="update_table.op = 'c' OR update_table.op = 'r'"
       ).execute()
+
+      delta_lake_table = DeltaTable.forPath(spark, path)
+
       delta_lake_table.alias("main_table").merge(
           latest_changes_update_df.alias("update_table"), merge_condition
       ).whenMatchedUpdateAll(
           condition="update_table.op = 'u' OR update_table.op = 'r'"
       ).execute()
```
Our order was `updateAll`/`insertAll` then performing the deletes, but functionally it was the same. If we reloaded the DeltaTable in between the two operations the error went away.

Our stacktrace:
```
org.apache.spark.sql.delta.DeltaAnalysisException: The schema of your Delta table has changed in an incompatible way since your DataFrame
or DeltaTable object was created. Please redefine your DataFrame or DeltaTable object.
Changes:
Latest schema has additional field(s): new_col
  at org.apache.spark.sql.delta.DeltaErrorsBase.schemaChangedSinceAnalysis(DeltaErrors.scala:548)
  at org.apache.spark.sql.delta.DeltaErrorsBase.schemaChangedSinceAnalysis$(DeltaErrors.scala:535)
  at org.apache.spark.sql.delta.DeltaErrors$.schemaChangedSinceAnalysis(DeltaErrors.scala:2489)
  at org.apache.spark.sql.delta.commands.MergeIntoCommand.$anonfun$runMerge$2(MergeIntoCommand.scala:342)
  at org.apache.spark.sql.delta.commands.MergeIntoCommand.$anonfun$runMerge$2$adapted(MergeIntoCommand.scala:340)
  at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:252)
  at org.apache.spark.sql.delta.commands.MergeIntoCommand.$anonfun$runMerge$1(MergeIntoCommand.scala:340)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:139)
  at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:137)
  ...
```

**Comment by foss-contributor** [comment]
@keenborder786, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
