### ISSUE TITLE
[BUG] Couldn't load the table due to hadoop checksum failed.

### ISSUE THREAD

**Issue by horizonzy** [delta-io/delta#1675]
### Describe the problem
I commit the AddFile actions with multi concurrently, some commit failed due to the concurrent conflict.

Then I use `DeltaLogImpl.forTable()` to load the table, it throws hadoop checksum exception. 
```
Caused by: java.io.UncheckedIOException: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/Users/horizon/IdeaProjects/pulsar/public/default/delta-topic-e/_delta_log/00000000000000000006.json at 0 exp: -814881823 got: -1152793262
	at io.delta.storage.LineCloseableIterator.hasNext(LineCloseableIterator.java:72) ~[?:?]
	at io.delta.standalone.internal.actions.CustomJsonIterator.hasNext(MemoryOptimizedLogReplay.scala:118) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.$anonfun$ensureNextIterIsReady$3(MemoryOptimizedLogReplay.scala:81) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.$anonfun$ensureNextIterIsReady$3$adapted(MemoryOptimizedLogReplay.scala:81) ~[?:?]
	at scala.Option.exists(Option.scala:376) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.ensureNextIterIsReady(MemoryOptimizedLogReplay.scala:81) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.hasNext(MemoryOptimizedLogReplay.scala:90) ~[?:?]
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45) ~[?:?]
	at scala.collection.Iterator.foreach(Iterator.scala:943) ~[?:?]
	at scala.collection.Iterator.foreach$(Iterator.scala:943) ~[?:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.loadTableProtocolAndMetadata(SnapshotImpl.scala:136) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.x$1$lzycompute(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.x$1(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.protocolScala$lzycompute(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.protocolScala(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.<init>(SnapshotImpl.scala:244) ~[?:?]
	at io.delta.standalone.internal.SnapshotManagement.createSnapshot(SnapshotManagement.scala:257) ~[?:?]
	at io.delta.standalone.internal.SnapshotManagement.getSnapshotAtInit(SnapshotManagement.scala:224) ~[?:?]
	at io.delta.standalone.internal.SnapshotManagement.$init$(SnapshotManagement.scala:37) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl.<init>(DeltaLogImpl.scala:47) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl$.apply(DeltaLogImpl.scala:263) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl$.forTable(DeltaLogImpl.scala:241) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl.forTable(DeltaLogImpl.scala) ~[?:?]
	at io.delta.standalone.DeltaLog.forTable(DeltaLog.java:164) ~[?:?]
	at io.streamnative.tieredstorage.delta.DeltaTableUtils.createTable(DeltaTableUtils.java:22) ~[?:?]
	at io.streamnative.tieredstorage.delta.reader.DeltaReader.<init>(DeltaReader.java:61) ~[?:?]
	at io.streamnative.tieredstorage.delta.DeltaOffloadWriter.lambda$getDeltaReader$5(DeltaOffloadWriter.java:193) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar:?]
	at io.streamnative.tieredstorage.delta.DeltaOffloadWriter.getDeltaReader(DeltaOffloadWriter.java:189) ~[?:?]
	at io.streamnative.tieredstorage.delta.DeltaOffloadWriter.lambda$deleteAsync$3(DeltaOffloadWriter.java:135) ~[?:?]
	... 6 more
Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/Users/horizon/IdeaProjects/pulsar/public/default/delta-topic-e/_delta_log/00000000000000000006.json at 0 exp: -814881823 got: -1152793262
	at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:347) ~[?:?]
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:303) ~[?:?]
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:252) ~[?:?]
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:197) ~[?:?]
	at java.io.DataInputStream.read(DataInputStream.java:151) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at io.delta.storage.LineCloseableIterator.hasNext(LineCloseableIterator.java:60) ~[?:?]
	at io.delta.standalone.internal.actions.CustomJsonIterator.hasNext(MemoryOptimizedLogReplay.scala:118) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.$anonfun$ensureNextIterIsReady$3(MemoryOptimizedLogReplay.scala:81) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.$anonfun$ensureNextIterIsReady$3$adapted(MemoryOptimizedLogReplay.scala:81) ~[?:?]
	at scala.Option.exists(Option.scala:376) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.ensureNextIterIsReady(MemoryOptimizedLogReplay.scala:81) ~[?:?]
	at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.hasNext(MemoryOptimizedLogReplay.scala:90) ~[?:?]
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45) ~[?:?]
	at scala.collection.Iterator.foreach(Iterator.scala:943) ~[?:?]
	at scala.collection.Iterator.foreach$(Iterator.scala:943) ~[?:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.loadTableProtocolAndMetadata(SnapshotImpl.scala:136) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.x$1$lzycompute(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.x$1(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.protocolScala$lzycompute(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.protocolScala(SnapshotImpl.scala:126) ~[?:?]
	at io.delta.standalone.internal.SnapshotImpl.<init>(SnapshotImpl.scala:244) ~[?:?]
	at io.delta.standalone.internal.SnapshotManagement.createSnapshot(SnapshotManagement.scala:257) ~[?:?]
	at io.delta.standalone.internal.SnapshotManagement.getSnapshotAtInit(SnapshotManagement.scala:224) ~[?:?]
	at io.delta.standalone.internal.SnapshotManagement.$init$(SnapshotManagement.scala:37) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl.<init>(DeltaLogImpl.scala:47) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl$.apply(DeltaLogImpl.scala:263) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl$.forTable(DeltaLogImpl.scala:241) ~[?:?]
	at io.delta.standalone.internal.DeltaLogImpl.forTable(DeltaLogImpl.scala) ~[?:?]
	at io.delta.standalone.DeltaLog.forTable(DeltaLog.java:164) ~[?:?]
	at io.streamnative.tieredstorage.delta.DeltaTableUtils.createTable(DeltaTableUtils.java:22) ~[?:?]
	at io.streamnative.tieredstorage.delta.reader.DeltaReader.<init>(DeltaReader.java:61) ~[?:?]
	at io.streamnative.tieredstorage.delta.DeltaOffloadWriter.lambda$getDeltaReader$5(DeltaOffloadWriter.java:193) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.0.1-jre.jar:?]
	at io.streamnative.tieredstorage.delta.DeltaOffloadWriter.getDeltaReader(DeltaOffloadWriter.java:189) ~[?:?]
	at io.streamnative.tieredstorage.delta.DeltaOffloadWriter.lambda$deleteAsync$3(DeltaOffloadWriter.java:135) ~[?:?]
	... 6 more
```

**Comment by horizonzy** [comment]
I guess the conflict of committing led to the CRC mismatch in the commit file.

**Comment by zsxwing** [comment]
Are you running concurrent writes using the local file system? This is not supported as the local file system doesn't guarantee mutual exclusion. Commits may be overwritten when using the local file system. We only use the local file system to write unit tests.

**Comment by horizonzy** [comment]
> Are you running concurrent writes using the local file system? This is not supported as the local file system doesn't guarantee mutual exclusion. Commits may be overwritten when using the local file system. 

Yes, I use the delta standalone to test on my laptop.

> We only use the local file system to write unit tests.

The problem already happens, is there some workaround to load the table.


Last question. The local file system didn't support the mutual exclusion. If I use the S3, GCS. The problem won't happen, right?

**Comment by zsxwing** [comment]
> The problem already happens, is there some workaround to load the table.

You can delete the checksum files created by Hadoop

> If I use the S3, GCS. The problem won't happen, right?

GCS is fine. S3 has some limitations. See https://docs.delta.io/latest/delta-storage.html#amazon-s3 for more details.
