### ISSUE TITLE
Save to HDFS throw Exception

### ISSUE THREAD

**Issue by myBigbug** [delta-io/delta#1796]
org.apache.spark.sql.delta.DeltaIllegalStateException: Unrecognized file action AddFile(part-00000-625eb71e-ea1f-4225-a0d2-4f340755f793-c000.snappy.parquet,Map(),2327,1685071775186,true,null,null) with type class org.apache.spark.sql.delta.actions.AddFile.
	at org.apache.spark.sql.delta.DeltaErrorsBase.unrecognizedFileAction(DeltaErrors.scala:1705)
	at org.apache.spark.sql.delta.DeltaErrorsBase.unrecognizedFileAction$(DeltaErrors.scala:1704)
	at org.apache.spark.sql.delta.DeltaErrors$.unrecognizedFileAction(DeltaErrors.scala:2264)

**Comment by allisonport-db** [comment]
Can you provide more information please? Full stack trace, environment information, what code you ran etc. The issue template has sections outlined

**Comment by myBigbug** [comment]
my reasons
