### ISSUE TITLE
Data merge error reporting

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/delta#180]
val deltaTable = DeltaTable.forPath(sparks, updatePath)
            deltaTable.as("t")
              .merge(
                filterSql.as("s"),
                "s." + primaryKey + " = t." + primaryKey)
              .whenMatched().updateAll()
              .whenNotMatched().insertAll()
              .execute()
error：
true), true, false), input[0, scala.collection.mutable.Map, true]) AS value#28]
+- MapPartitions <function1>, obj#27: scala.collection.mutable.Map
   +- DeserializeToObject cast(value#21 as string).toString, obj#26: java.lang.String
      +- Project [cast(value#8 as string) AS value#21]
         +- StreamingExecutionRelation KafkaV2[Subscribe[tt_03]], [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13]

	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:297)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: java.lang.UnsupportedOperationException: Cannot perform MERGE as multiple source rows matched and attempted to update the same target row in the Delta table.

**Comment by marmbrus** [comment]
Hmm, I'm not sure why that is an `UnsupportedOperationException` (which at least to me implies this is something that you might want to support eventually or in different variants of this command).

This is by design and disallowed because allowing multiple matches without an order makes the result dependent on the order processing occurs.

If you have multiple instances of the same key, you need to "pick" the winner first, as [shown in the docs for merge](https://docs.delta.io/latest/delta-update.html#write-change-data-into-a-delta-table)

**Comment by zhangxinjian123** [comment]
if (tableForm.equals("update")) {

          val updatePath = basePath + deltaDataBase + "/" + deltaTableName

          log.info("update:" + updatePath)

          if(DeltaTableUtils.isDeltaTable(sparks, new Path(updatePath))) {

            val deltaTable = DeltaTable.forPath(sparks, updatePath)

            deltaTable.as("events")
              .merge(
                filterSql.as("updates"),
                "events.primaryKey = updates.primaryKey" )
              .whenMatched().updateAll()
           //   .whenNotMatched().insertAll()
              .execute()
          }   else if (tableForm.equals("insert")) {

          val insertPath = basePath + deltaDataBase + "/" + deltaTableName
          println("insertPath:" + insertPath)
          filterSql
            .write
            .format("delta")
            .mode("append")
            .option("mergeSchema", "true")
            .partitionBy("partition")
            .save(insertPath)

        }

My primary key's schmea is primaryKey, but there are duplications, not updating according to the primary key, just inserting data. For example, the value of primaryKey is [320948874480979968]. Normally it should be one piece of data.
scala> read.show()
+--------+------+---------+--------------------+--------------------+--------------------+----------+
|dataBase|  type|tableName|               value|           timestamp|          primaryKey| partition|
+--------+------+---------+--------------------+--------------------+--------------------+----------+
|  credit|update|wf_task_1|{"id":32094887448...|2019-09-23T15:11:...|[320948874480979968]|2019-09-23|
|  credit|update|wf_task_1|{"id":32094887448...|2019-09-23T15:11:...|[320948874480979968]|2019-09-23|
|  credit|update|wf_task_1|{"id":32094887060...|2019-09-23T15:11:...|[320948870605443072]|2019-09-23|
|  credit|update|wf_task_1|{"id":32094887060...|2019-09-23T15:11:...|[320948870605443072]|2019-09-23|
|  credit|insert|wf_task_1|{"id":32094887060...|2019-09-23T15:11:...|[320948874480979968]|2019-09-23|
|  credit|insert|wf_task_1|{"id":32094887060...|2019-09-23T15:11:...|[320948870605443072]|2019-09-23|
+--------+------+---------+--------------------+--------------------+--------------------+----------+

**Comment by pranavanand** [comment]
From the docs here: https://docs.delta.io/latest/delta-update.html#upsert-into-a-table-using-merge 

"A merge operation can fail if multiple rows of the source dataset match and attempt to update the same same row of the target Delta table. By SQL semantics of merge, such an update operation is ambiguous as it is unclear which source should be used to update the matching target row. You can preprocess the source table to eliminate the possibility of multiple matches. See the change-data-capture example – it preprocesses the change dataset (that is, the source dataset) to retain only the latest change for each key before applying that change into the target Delta table."

The above section links to an example of how to remove duplicates before a merge: https://docs.delta.io/latest/delta-update.html#write-change-data-into-a-delta-table

Hope this helps!
