### ISSUE TITLE
[BUG] delta 2.4 on spark 3.4

### ISSUE THREAD

**Issue by aminebizid** [delta-io/delta#1853]
I get this error when adding delta packages 

23/06/21 15:20:17 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1107)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:244)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2088)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.rpc.RpcEnvStoppedException: RpcEnv already stopped.
	at org.apache.spark.rpc.netty.Dispatcher.postMessage(Dispatcher.scala:176)
	at org.apache.spark.rpc.netty.Dispatcher.postLocalMessage(Dispatcher.scala:144)
	at org.apache.spark.rpc.netty.NettyRpcEnv.askAbortable(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.askAbortable(NettyRpcEnv.scala:554)
	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.ask(NettyRpcEnv.scala:558)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:100)

**Comment by allisonport-db** [comment]
Hi @aminebizid can you provide more information please? Specifically, provide what you're running and where (code snippets etc)

**Comment by tdas** [comment]
This stacktrace does not have any Delta references in it. This is purely a Spark issue. Specifically, if my knowledge of Spark is still relevant, this warning happens when the Spark worker has some issue (either network connectivity, or too GC pauses) trying to talk to the Spark driver when running tasks. But often this is just a transient issue... this is a warning, not an error, which indicates that this likely a transient issue. This by itself should not cause any error in your application. Is you application crashing after this? 

Either way, if this is actually a persistent problem for you, it may also be useful to report it in the Spark mailing list.

**Comment by tdas** [comment]
Closing the issue due to lack of activity. Please reopen if this problem persists.
