### ISSUE TITLE
[BUG] "CREATE OR REPLACE TABLE ... SHALLOW CLONE ...." should overwrite the existing table instead of fail

### ISSUE THREAD

**Issue by mingdai-db** [delta-io/delta#1884]
### Describe the problem

When the target table of SHALLOW CLONE already exists, the SHLLOW CLONE will fails for the error below even CREATE OR REPLACE is used:
```
org.apache.spark.sql.delta.DeltaIllegalStateException: The clone destination table is non-empty. Please TRUNCATE or DELETE FROM the table before running CLONE.
  at org.apache.spark.sql.delta.DeltaErrorsBase.cloneReplaceNonEmptyTable(DeltaErrors.scala:2610)
  at org.apache.spark.sql.delta.DeltaErrorsBase.cloneReplaceNonEmptyTable$(DeltaErrors.scala:2609)
  at org.apache.spark.sql.delta.DeltaErrors$.cloneReplaceNonEmptyTable(DeltaErrors.scala:2681)
  at org.apache.spark.sql.delta.commands.CloneTableBase.runInternal(CloneTableBase.scala:196)
  at org.apache.spark.sql.delta.commands.CloneTableCommand.run(CloneTableCommand.scala:106)
```
I think the expected behavior is overwriting the existing table (i.e., drop it and create a new one with the latest SHALLOW CLONE)

#### Steps to reproduce

Run the same SHALLOW CLONE commands on the same target table twice, e.g.,
```
CREATE OR REPLACE TABLE <target> SHALLOW CLONE <source>
```

### Environment information

* Delta Lake version: 2.3
* Spark version: 3.3.2
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by bgribaudo** [comment]
I hit this issue recently, too. 

Interestingly, there's a [test](https://github.com/delta-io/delta/blob/23a7f9013a075b82c011b66585c2f46794cb49d2/spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/MaterializedColumnSuite.scala#L246-L262) asserting that `CREATE OR REPLACE TABLE ... SHALLOW CLONE ...` should raise the error you mentioned if the table exists, so maybe this behavior is by design?

**Comment by foss-contributor** [comment]
@mingdai-db, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
