### ISSUE TITLE
[BUG] Mima checking for incorrect delta-spark (should be core) package name?

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#2173]
Seems like something is wrong with our Mima build?

- build failure: https://github.com/delta-io/delta/actions/runs/6488854954/job/17622068368?pr=2166
- PR that triggered that build (but, I think it is unrelated): https://github.com/delta-io/delta/pull/2166

```
[error] sbt.librarymanagement.ResolveException: Error downloading io.delta:delta-spark_2.12:2.4.0
[error]   Not found
[error]   not found: /home/runner/.ivy2/localio.delta/delta-spark_2.12/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/2.4.0/delta-spark_2.12-2.4.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at com.typesafe.tools.mima.plugin.SbtMima$.getPreviousArtifact(SbtMima.scala:98)
[error] 	at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$projectSettings$5(MimaPlugin.scala:50)
[error] 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:648)
[error] 	at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:595)
[error] 	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:372)
[error] 	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:370)
[error] 	at scala.collection.AbstractIterator.toMap(Iterator.scala:1431)
[error] 	at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$projectSettings$4(MimaPlugin.scala:51)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (spark / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: Error downloading io.delta:delta-spark_2.12:2.4.0
```

**Comment by scottsand-db** [comment]
```
build/sbt spark/mimaPreviousClassfiles
```

**Comment by scottsand-db** [comment]
There is some issue since we have updated the version to 3.0.1-SNAPSHOT

```
SCOTT: getPrevSparkName >>> currentVersion: 3.0.1-SNAPSHOT -> result: delta-spark
SCOTT: getPrevSparkVersion >>> currentVersion: 3.0.1-SNAPSHOT -> result: 2.4.0
```

**Comment by foss-contributor** [comment]
@scottsand-db, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
