### ISSUE TITLE
 Cannot perform MERGE as multiple source rows matched and attempted to update the same target row in the Delta table.

### ISSUE THREAD

**Issue by sanjiv1980** [delta-io/delta#218]
```
9/10/17 00:34:02 INFO DAGScheduler: ResultStage 9 (apply at DatabricksLogging.scala:77) finished in 0.026 s
19/10/17 00:34:02 INFO DAGScheduler: Job 4 finished: apply at DatabricksLogging.scala:77, took 137.754938 s
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot perform MERGE as multiple source rows matched and attempted to update the same target row in the Delta table.
	at org.apache.spark.sql.delta.DeltaErrors$.multipleSourceRowMatchingTargetRowInMergeException(DeltaErrors.scala:416)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.org$apache$spark$sql$delta$commands$MergeIntoCommand$$findTouchedFiles(MergeIntoCommand.scala:218)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1$$anonfun$1.apply(MergeIntoCommand.scala:125)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1$$anonfun$1.apply(MergeIntoCommand.scala:125)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordOperation(MergeIntoCommand.scala:88)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordDeltaOperation(MergeIntoCommand.scala:88)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1.apply(MergeIntoCommand.scala:124)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1.apply(MergeIntoCommand.scala:121)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:386)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1.apply(MergeIntoCommand.scala:121)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1.apply(MergeIntoCommand.scala:120)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordOperation(MergeIntoCommand.scala:88)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordDeltaOperation(MergeIntoCommand.scala:88)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.run(MergeIntoCommand.scala:120)
	at io.delta.tables.DeltaMergeBuilder.execute(DeltaMergeBuilder.scala:233)
	at com.espn.deltalake.InsertUpdateRecords.main(InsertUpdateRecords.java:46)
19/10/17 00:34:02 INFO SparkContext: Invoking stop() from shutdown hook

```

**Comment by sanjiv1980** [comment]
here is my code , which try to update 

```
Dataset<Row> updatesDF = spark.read().csv("update-records/updates.csv");

		DeltaTable.forPath(spark, "delta-table/source").as("source")
				.merge(
						updatesDF.as("updates"),
						"source.id = source.id"
					  )
				.whenMatched()
				.updateExpr(new HashMap<String, String>() {
					/**
					 * 
					 */
					private static final long serialVersionUID = 1L;

					{
						//put("id", "'fake-id-id'");
						put("visitor_id", "'fake-visitor_id-id'");
						put("maid", "'fake-maid-id'");
					}
				}).execute();
	}```

**Comment by mukulmurthy** [comment]
Hi @sanjiv1980 ,

That happens when your source table (`updatesDF`) has multiple rows trying to update the same target row. This could happen if your `updatesDF` table has records with the same ID, but I think in this case it also might be your match condition: `"source.id = source.id"` should be `"updates.id = source.id"`

**Comment by sanjiv1980** [comment]
Thanks ,It's my bad . Now it's working fine .

**Comment by Mageswaran1989** [comment]
For those who hit this page, make sure there is no duplicate records in new/source data frame before you attempt to merge the data with the exisitng Delta table

**Comment by Mageswaran1989** [comment]
I haven't followed Delta lake for some time now.
