### ISSUE TITLE
[BUG][Standalone] Cannot read delta table using delta standalone

### ISSUE THREAD

**Issue by snleee** [delta-io/delta#2243]
## Bug

I created the delta table with the protocol version of `minReader=3, minWriter=7`.

```
df = spark.read.csv(csvfile)
df.write.format("delta").saveAsTable("MyFirstDeltaTable")
dt = DeltaTable.forPath(spark,'/path/for/table') 
dt.upgradeTableProtocol(3, 7)
```

I'm trying to read the table using delta-standalone (3.0.0).
```
    Map<String, String> config = new HashMap<>();
    config.put("fs.s3a.access.key", "");
    config.put("fs.s3a.secret.key", "");
    config.put("fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider");
    Configuration configuration = new Configuration();
    config.forEach(configuration::set);

    DeltaLog deltaLog = DeltaLog.forTable(configuration, "s3a://path/to/table");
```

And, I'm getting the following error.
```
Exception in thread "main" io.delta.standalone.internal.exception.DeltaErrors$InvalidProtocolVersionException: 
Delta protocol version (3,7) is too new for this version of Delta
Standalone Reader/Writer (1,2). Please upgrade to a newer release.

	at io.delta.standalone.internal.DeltaLogImpl.assertProtocolRead(DeltaLogImpl.scala:214)
	at io.delta.standalone.internal.SnapshotImpl.<init>(SnapshotImpl.scala:345)
	at io.delta.standalone.internal.SnapshotManagement.createSnapshot(SnapshotManagement.scala:287)
	at io.delta.standalone.internal.SnapshotManagement.getSnapshotAtInit(SnapshotManagement.scala:232)
	at io.delta.standalone.internal.SnapshotManagement.$init$(SnapshotManagement.scala:37)
	at io.delta.standalone.internal.DeltaLogImpl.<init>(DeltaLogImpl.scala:47)
	at io.delta.standalone.internal.DeltaLogImpl$.apply(DeltaLogImpl.scala:263)
	at io.delta.standalone.internal.DeltaLogImpl$.forTable(DeltaLogImpl.scala:241)
	at io.delta.standalone.internal.DeltaLogImpl.forTable(DeltaLogImpl.scala)
	at io.delta.standalone.DeltaLog.forTable(DeltaLog.java:164)

```
Can someone let me know the supported reader/writer protocol versions for delta-standalone?

**Comment by vkorukanti** [comment]
@snleee Standalone isn't up to date with the latest protocol changes. Currently, the community is focussing on the [Delta Kernel](https://github.com/delta-io/delta/tree/master/kernel) to support the latest protocol versions and provide simpler APIs for connectors. 

The current version of Kernel supports reads, but there is no write support yet (coming soon!). Is there any missing feature in Kernel that blocks you from using it?

Related: https://github.com/delta-io/delta/issues/2254

**Comment by snleee** [comment]
@vkorukanti We have built the connector around delta-standalone lib. Our connector is ingesting files incrementally based on the delta logs. We need to fetch the log entry to detect the added files/deleted files compared to the last snapshot that we ingested.

Does Delta Kernel expose APIs the certain level of lower level information? We would eventually need sth like the following:

1. Access to delta commit logs (added/deleted files)
2. Stats metadata for each file (e.g. min/max timestamp)

**Comment by vkorukanti** [comment]
> 1. Access to delta commit logs (added/deleted files)
We have an [issue](https://github.com/delta-io/delta/issues/2233) to support getting actions (adds/removes etc) between versions. We want to eventually support it for streaming usecases, it isn't prioritized yet.

> 2. Stats metadata for each file (e.g. min/max timestamp)

To clarify you are talking about the column level statistics in each `AddFile`? If that is what you mean, do have plan to support it as part of #2229. There is a work item to expose the stats in each scan file.

**Comment by snleee** [comment]
@vkorukanti Thank you for sharing details. In this case, what would be the recommended path forward to support to read delta tables that are written based on writerVersion=7? 

1. We cannot read the table using `delta-standalone`
2. We cannot migrate to `delta-kernel` because it's not supporting to fetch adds/removes from the delta log. 

Also, may I ask what is the max version of writer that `delta-standalone:3.0.0` can read?

**Comment by vkorukanti** [comment]
> @vkorukanti Thank you for sharing details. In this case, what would be the recommended path forward to support to read delta tables that are written based on the newer delta protocol version?
> 
> 1. We cannot read the table using `delta-standalone` because it's not supporting the latest protocol.
> 2. We cannot migrate to `delta-kernel` because it's not supporting to fetch adds/removes from the delta log.
> 
> Also, may I ask what is the max version of writer that `delta-standalone:3.0.0` can read?

Delta Kernel support protocol version (3, 7) with reader features `columnMapping` (`name` mode) and `deletionVectors`. 

Are you interested a sync (may be zoom) to understand your requirements better. It will also help us prioritize the missing features in Kernel.

**Comment by snleee** [comment]
> > @vkorukanti Thank you for sharing details. In this case, what would be the recommended path forward to support to read delta tables that are written based on the newer delta protocol version?
> > 
> > 1. We cannot read the table using `delta-standalone` because it's not supporting the latest protocol.
> > 2. We cannot migrate to `delta-kernel` because it's not supporting to fetch adds/removes from the delta log.
> > 
> > Also, may I ask what is the max version of writer that `delta-standalone:3.0.0` can read?
> 
> Delta Kernel support protocol version (3, 7) with reader features `columnMapping` (`name` mode) and `deletionVectors`.
> 
> Are you interested a sync (may be zoom) to understand your requirements better. It will also help us prioritize the missing features in Kernel.

Sure, I can do the sync meeting 1-5pm tomorrow. Will you be available any time slot? `seunghyun@startree.ai` is my email address.

**Comment by vkorukanti** [comment]
> Sure, I can do the sync meeting 1-5pm tomorrow. Will you be available any time slot? `seunghyun@startree.ai` is my email address.

Sent a meeting request.

**Comment by dingxiaobo** [comment]
I have same issue when using 
```
<dependency>
    <groupId>io.delta</groupId>
    <artifactId>delta-flink</artifactId>
    <version>3.3.2</version>
</dependency>
```

does delta-flink is deprecated for new delta table ?

**Comment by foss-contributor** [comment]
@snleee, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
