### ISSUE TITLE
[BUG] Some DV tests takes hours and timeout when --coverage is set

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#2358]
#### Which Delta project/connector is this regarding?
- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem
When --coverage is set these 2 tests takes hours. In my local machine it took more than 4 hours and failed. The error message says 20 minutes timeout, but it takes hours.

#### Steps to reproduce
You can run using the run-test.py or java command directly to filter this test only. I tested the java command without the flags set by python script, and the issue persists:

`python run-tests.py --group spark --coverage`

or

```
java -jar build/sbt-launch-1.5.5.jar clean coverage "++ 2.12.17" "spark/testOnly org.apache.spark.sql.delta.deletionvectors.DeletionVectorsSuite -- -z 'huge table: read from tables of 2B rows with existing DV of many zero
s'" coverageReport
```

or

```
sbt
coverage
project spark
testOnly org.apache.spark.sql.delta.deletionvectors.DeletionVectorsSuite -- -z "huge table: read from tables of 2B rows with existing DV of many zeros"
```

#### Observed results

[info] - **huge table: read from tables of 2B rows with existing DV of many zeros** *** FAILED ***
[info]   The code passed to failAfter did not complete within 20 minutes. (DeletionVectorsSuite.scala:628)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
[info]   at org.scalatest.concurrent.TimeLimits$.failAfterImpl(TimeLimits.scala:277)

[info] - **huge table: delete a small number of rows from tables of 2B rows with DVs** *** FAILED ***
[info]   The code passed to failAfter did not complete within 20 minutes. (DeletionVectorsSuite.scala:714)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
[info]   at org.scalatest.concurrent.TimeLimits$.failAfterImpl(TimeLimits.scala:277)

#### Expected results

Takes few minutes to complete

### Environment information

* Delta Lake version:3.0.0
* Spark version:3.5
* Scala version:2.12.17

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [X] No. I cannot contribute a bug fix at this time.

**Comment by foss-contributor** [comment]
@felipepessoto, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

**Comment by felipepessoto** [comment]
This is still valid
