### ISSUE TITLE
[BUG][Spark] Exception while using 3-layer-namespace on Spark

### ISSUE THREAD

**Issue by rosspalmer** [delta-io/delta#2434]
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem

As of Spark 3.4.0, native support for 3-layer-namespaces for tables was added into SQL API, allowing multiple catalogs to be accessed through using a full table name of the `<catalog>.<schema>.<table>` convention. Multiple catalogs can be set using the `spark.sql.catalog.<catalog_name>=...` spark config.

- [3-layer-namespace Ticket](https://issues.apache.org/jira/browse/SPARK-39235)
- [Spark 3.4.0 release notes](https://spark.apache.org/releases/spark-release-3-4-0.html)

This works when using the Apache Iceberg example below, but does not work when utilizing multiple Delta catalogs. While the SparkSession is initiated with the catalog present in the session, when a second, non `spark_catalog` catalog is referenced, the following exception is thrown.

`[INTERNAL_ERROR] The Spark SQL phase analysis failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace.`

- [Iceberg Multiple Catalog Example](https://iceberg.apache.org/docs/latest/spark-configuration/)

Here is a recent StackOverflow post experiencing the same issue with PySpark: https://stackoverflow.com/questions/77751057/multiple-catalogs-in-spark

#### Steps to reproduce

I am running this on my local machine, in client mode, using my local filesystem to host data.

Here is my SparkSession generator:

```scala
override lazy val spark = SparkSession.builder()
      .master("local")
      .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
      .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
      .config("spark.sql.catalog.catalog_b", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
      .enableHiveSupport()
      .getOrCreate()
```

Here is a batch of testing code:

```scala
import spark.implicits._

val df = Seq(
  ("A", 1, 2.3),
  ("B", 4, 5.6)
).toDF("X", "Y", "Z")

spark.sql("create schema here")

df.write.mode(SaveMode.Overwrite).saveAsTable("here.now")

val df2 = df.union(Seq(("C", 7, 8.9)).toDF("X", "Y", "Z"))
df2.write.mode(SaveMode.Overwrite).saveAsTable("spark_catalog.here.now2")

spark.catalog.setCurrentCatalog("catalog_b")
spark.sql("create schema here")

val df3 = df2.union(Seq(("D", 10, 11.12)).toDF("X", "Y", "Z"))
df3.write.mode(SaveMode.Overwrite).saveAsTable("catalog_b.here.now")
```

#### Observed results

When running with the example above, the `spark.catalog.setCurrentCatalog("catalog_b")` command works but then the following `spark.sql("create schema here")` command throws the exception below:

```scala
[INTERNAL_ERROR] The Spark SQL phase analysis failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace.
org.apache.spark.SparkException: [INTERNAL_ERROR] The Spark SQL phase analysis failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace.
	at org.apache.spark.SparkException$.internalError(SparkException.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$.toInternalError(QueryExecution.scala:536)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:548)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:691)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
	at com.hungryroot.ThreeLayerDeltaTest.$anonfun$new$2(ThreeLayerNamespaceTest.scala:94)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1832)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1686)
	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1830)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1842)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1842)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1824)
	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1686)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1900)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1900)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1899)
	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1686)
	at org.scalatest.Suite.run(Suite.scala:1114)
	at org.scalatest.Suite.run$(Suite.scala:1096)
	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1686)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1945)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1945)
	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1943)
	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1686)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:47)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1321)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1315)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1315)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:43)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:26)
Caused by: java.lang.NullPointerException
	at org.apache.spark.sql.connector.catalog.DelegatingCatalogExtension.name(DelegatingCatalogExtension.java:50)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.isSessionCatalog(CatalogV2Util.scala:374)
	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog$DatabaseNameInSessionCatalog$.unapply(ResolveSessionCatalog.scala:628)
	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog$$anonfun$apply$1.applyOrElse(ResolveSessionCatalog.scala:231)
	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog$$anonfun$apply$1.applyOrElse(ResolveSessionCatalog.scala:52)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:134)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:130)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:111)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:110)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog.apply(ResolveSessionCatalog.scala:52)
	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog.apply(ResolveSessionCatalog.scala:46)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:226)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:222)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:173)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:222)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:188)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:209)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:208)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:77)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
	... 65 more
```

#### Expected results

I would expect this to create a schema `here` in the catalog `catalog_b` and allow me to save data to it.

#### Further details

This is an effort to create a local "delta lake" for testing which can be compatible with Databrick's three layer namepace used by their Unity Catalog.

### Environment information

* Delta Lake version: 3.0.0
* Spark version: 3.4.1
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by jelmerk** [comment]
+1 this makes it hard to create tests for code that uses multiple catalogs in production

**Comment by ezu-mutt** [comment]
+1

**Comment by boittega** [comment]
+1
Any workaround to be able to test 3-layer-namespace?

**Comment by meharanjan318** [comment]
+1

**Comment by rosspalmer** [comment]
Just confirming I am still being blocked by this. We have a "workaround" where we squish the catalog and database names together when running locally but its not pretty...

**Comment by flaviokr** [comment]
I am also facing this issue

**Comment by faltesekATG** [comment]
I'd also like to see this address for unit tests

**Comment by scottsand-db** [comment]
I've confirmed that
(1) using Delta catalog and an Iceberg catalog works ✅ 
(2) using two Iceberg catalogs works ✅ 
(3) using two Delta catalogs fails ❌ 

WIP investigating why

**Comment by carloshhelt** [comment]
+1 i'm facing the same problem while using 2 delta catalogs

**Comment by keanuxr** [comment]
+1

**Comment by daniel-vizcaino** [comment]
+1

**Comment by denisoliveirac** [comment]
+1

**Comment by abutala** [comment]
+1

**Comment by wysisoft** [comment]
is there any feedback on this? seems like iceberg is the only way to do this?

**Comment by johnh1989** [comment]
+1

**Comment by nemenko** [comment]
+1

**Comment by mahic** [comment]
@scottsand-db I've tested this with Spark 4.0-preview2 and Delta Lake 4.0 preview, same issue. This should be fixed before shipping Delta for 4.0 at least.

**Comment by moritzmeister** [comment]
Has there been any fix for this, I am still observing the issue when writing tests.

**Comment by sadowskik** [comment]
Are there any new on that? It's super important to have this aligned. There seems to be nor progress on that for over a year! I'm seriously thinking of fully switching to Iceberg as it seems to emerge as the only viable option now.

**Comment by rosspalmer** [comment]
@raveeram-db I'll have to refresh myself on the specifics but do have some upcoming available time. I'll follow up next week.

**Comment by raveeram-db** [comment]
Thanks @rosspalmer, appreciate it! @LukasRupprecht is an expert in this area and should be able to help out with any questions

**Comment by rosspalmer** [comment]
@LukasRupprecht Would it be possible to set up the situation in the OP as test suite for `spark.org.apache.spark.sql.delta.catalog.DeltaCatalog`? Are there any base classes that would be helpful in setting up the test?

**Comment by LukasRupprecht** [comment]
@rosspalmer You could add the test case to `CustomCatalogSuite`. That suite already has several test case for testing a different catalog implementations so should provide some examples. We can add a test that has two `DeltaCatalog`s with different names configured.

**Comment by rosspalmer** [comment]
figured out #1 ^^ All setup now in Intellij and have added the failing test. I am working on debugging the issue now

**Comment by raveeram-db** [comment]
Thanks for working on this @rosspalmer !

**Comment by rosspalmer** [comment]
I've identified the issue but unsure of the best avenue to attempt a fix. @LukasRupprecht Could you advise on the situation below?

**Background:**

The `DeltaCatalog` is an extension of Spark's `DelegatingCatalogExtension` which allows for overriding specific methods of a base `CatalogPlugin`, any methods that are not overwritten get called on the `delegate` base catalog. For `spark.sql.catalog.spark_catalog`, the default Spark `V2SessionCatalog` is set as the `delegate` automatically the first time this catalog is utilized.

For catalogs not named `spark_catalog`, this call to set a delegate doesn't happen naturally and thus when `catalog_b` is called in the example above,  the `.name()` method is passed to the `delegate` which is null and throws the NullPointerException.

**Issue:**

The `DelegatingCatalogExtension` class sets the `initialize` method as **final** which prevents us from passing the catalog name (`catalog_b` in my example) to the class when it's being generated (`Catalogs.load()` method). From my initial review, I don't know of another way to pass the name after the catalog is initially loaded

**Question:**

What would be the best way to tackle this? 

1. Looking at the [Iceberg catalog](https://github.com/apache/iceberg/blob/cc4fe4cc50043ccba89700f7948090ff87a5baee/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java#L123) example, they don't use the `DelegatingCatalogExtension` and pull the `name`, plus other configs, in the `initialize` call. Is this an option?
2. Theoretically we should be able to set a `delegate` like in the default `spark_catalog` but I don't know how to do this while getting the secondary name. Would it be usefully to create a class like `DummyCatalog` in the test suite that would wrap an internal `DeltaCatalog`?

**Comment by LukasRupprecht** [comment]
Thanks @rosspalmer for debugging this!

On the Spark side, it looks like CatalogExtension specifically exists to "[extend the Spark built-in session catalog](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/java/org/apache/spark/sql/connector/catalog/CatalogExtension.java#L24)", which would explain why the delegate is only set on `spark_catalog`. It also makes sense as we should only have one catalog forwarding things to the built-in session catalog as otherwise, different catalogs would share the same state such as temp views.

Regarding Option 1: That's possible but it seems hard because DeltaCatalog relies on the delegate quite a bit. So just pulling in the name doesn't seem sufficient and we'd need to implement everything that is currently done by the delegate (like loadTable, alterTable, etc.).

Regarding Option 2: Can you expand on how the wrapping catalog would help in this case? In general, it looks like what we could do is in `initialize`, we'd need to create a new V2SessionCatalog that wraps a new SessionCatalog and then set that as the delegate but I don't know how hard that would be. Maybe that's an option to explore?

**Comment by raveeram-db** [comment]
Also looping in @cloud-fan to see if he can advise here.

**Comment by wysisoft** [comment]
I could be mistaken but I believe I had problems referencing iceberg
catalog items from spark (hive?) views, and so much tooling works through
views, like odbc connectors. Can you make sure whatever solution you
choose, the table can be referenced in a view?

**Comment by rosspalmer** [comment]
@LukasRupprecht In regards to option 2, I was thinking about a wrapper because I am unsure of how to get access to the `initialize` call since the underlying `DelegatingCatalogExtension.java` Spark class seems to lock out the ability to override this method because of the `final`:

```java
@Evolving
public abstract class DelegatingCatalogExtension implements CatalogExtension {

  private CatalogPlugin delegate;

  @Override
  public final void setDelegateCatalog(CatalogPlugin delegate) {
    this.delegate = delegate;
  }

  @Override
  public String name() {
    return delegate.name();
  }

  @Override
  public final void initialize(String name, CaseInsensitiveStringMap options) {}
```

A wrapper is not a great option so I'm all ears. I would agree with your plan of attack on generating the V2SessionCatalog and then setting it as a delegate, do you know of potential ways to mess with `initialize`?

**Comment by rosspalmer** [comment]
excellent, thats good news! I'll see if I was pulling in an older version and try out the overwrite solution

**Comment by tpang-cxl** [comment]
@rosspalmer It looks like Spark 3.5.1 still has the final modifier, but is dropped since 3.5.2

**Comment by adith-os** [comment]
Hi, I was also facing this issue and trying out the approaches mentioned above, Here's what I tried :

```
class DeltaCatalog extends DelegatingCatalogExtension
  with StagingTableCatalog
  with SupportsPathIdentifier
  with DeltaLogging {

  val spark = SparkSession.active
  var catalogName: String = ""

  override def initialize(name: String, options: CaseInsensitiveStringMap): Unit = {
    catalogName = name
    super.initialize(name, options)
    val v2Catalog = new V2SessionCatalog(
      SparkSession.active.sessionState.catalogManager.v1SessionCatalog)
    setDelegateCatalog(v2Catalog)
    println(s"DeltaSessionCatalog initialized with name: $name")
  }
  override def name: String = catalogName
  ...
}
```
This allows me to have any catalog name but the fundamental issue here is that it is still using `spark_catalog` under the hood which as far as I understand might be because I'm using the existing   `SparkSession.active.sessionState.catalogManager.v1SessionCatalog`. This would mean that we cannot have  `spark_catalog.db1.table1` and `catalog_c.db1.table1`. Also, I could only override `initialize` in spark 3.5.4 version.

**Comment by tpang-cxl** [comment]
@rosspalmer any update about when the fix can be available?

**Comment by rosspalmer** [comment]
@tpang-cxl 
I had a job switch so I've been away for a bit but looking into this again! No ETA but I'll summarize where we are currently at below.

@LukasRupprecht 
As @adith-os stated, the ability to override `initialize` is first available in Spark 3.5.4, it looks like Delta (as of 3.3)  is set  to Spark 3.5.3 in the repo, is this something that can get updated?

@adith-os 
Thank you for the the approach, this was good to plug in and play around with : ) 

As you point out, I think we need to get a `SessionCatalog` (V1) that can be set as a delegate but using the active catalog will reference to the default `spark_catalog`, I might try and look to see how the default gets generated and if that can be replicated.

**Comment by rosspalmer** [comment]
For reference, I have a test going in `CustomCatalogSuite` that will test using another catalog and triggers the namespace error @adith-os  describes above using their code.

```scala
  test("switch to secondary DeltaCatalog") {

    // Reset catalog manager so that the new `spark_catalog` implementation can apply.
    withSQLConf("spark.sql.catalog.other_catalog" -> classOf[DeltaCatalog].getName) {
      withTable("t") {
        // Start by using default `spark_catalog` and test SHOW DATABASES command
        sql("SET CATALOG spark_catalog")
        sql("CREATE DATABASE test")
        sql("USE DATABASE test")
        sql("CREATE TABLE t (id LONG) USING DELTA")

        // Switch to second `other_catalog` catalog and test SHOW DATABASES command

        sql("SET CATALOG other_catalog")
        sql("CREATE DATABASE test")
        sql("USE DATABASE test")
        sql("CREATE TABLE t (id LONG) USING DELTA")

      }
    }
  }
}
```

**Comment by rosspalmer** [comment]
One note on the `V2SessionCatalog`,  it seems to always point back to `spark_catalog`, at least in catalog name. The `SESSION_CATALOG_NAME` looks to be hardcoded into the class, although maybe it can be overridden as an anonymous class. 

```scala
private[sql] object CatalogManager {
  val SESSION_CATALOG_NAME: String = "spark_catalog"
}

/**
 * A [[TableCatalog]] that translates calls to the v1 SessionCatalog.
 */
class V2SessionCatalog(catalog: SessionCatalog)
  extends TableCatalog with FunctionCatalog with SupportsNamespaces with SQLConfHelper {
  import V2SessionCatalog._

  override val defaultNamespace: Array[String] = Array(SQLConf.get.defaultDatabase)

  override def name: String = CatalogManager.SESSION_CATALOG_NAME
...
}
```

**Comment by rosspalmer** [comment]
Leaving another note for reference, in the spark library the `BaseSessionStateBuilder` generates V1Catalog for the V2Catalog set to default `spark_default`. This may be able to be emulated in the `initialize` method.

Starting at line 145:
```scala
  /**
   * Catalog for managing table and database states. If there is a pre-existing catalog, the state
   * of that catalog (temp tables & current database) will be copied into the new catalog.
   *
   * Note: this depends on the `conf`, `functionRegistry` and `sqlParser` fields.
   */
  protected lazy val catalog: SessionCatalog = {
    val catalog = new SessionCatalog(
      () => session.sharedState.externalCatalog,
      () => session.sharedState.globalTempViewManager,
      functionRegistry,
      tableFunctionRegistry,
      SessionState.newHadoopConf(session.sparkContext.hadoopConfiguration, conf),
      sqlParser,
      resourceLoader,
      new SparkUDFExpressionBuilder)
    parentState.foreach(_.catalog.copyStateTo(catalog))
    catalog
  }

  protected lazy val v2SessionCatalog = new V2SessionCatalog(catalog)

  protected lazy val catalogManager = new CatalogManager(v2SessionCatalog, catalog)
```

**Comment by tpang-cxl** [comment]
thank @rosspalmer for the update

**Comment by LukasRupprecht** [comment]
> As @adith-os stated, the ability to override initialize is first available in Spark 3.5.4, it looks like Delta (as of 3.3) is set to Spark 3.5.3 in the repo, is this something that can get updated?

@rosspalmer `master` also builds against Spark 4.0 so you could test your fix that way initially. Once everything works, we can add a shim to `spark/src/main/scala-spark-3.5/shims/` to make the change also compile for Delta 3.3. Let me know if that makes sense.

**Comment by williamcyoung** [comment]
Any update on this? This is blocking us from onboarding to Delta as our storage layer is multi-format.

**Comment by joaoe** [comment]
Hi.
To whom it may concern, so I'm trying to setup to independent catalogs in a local containerized spark instance for unit tests.
I ended up injecting my own custom Catalog java class that I build and deploy with the dockerfile.
Given I was not really having a good day with this, I vibe coded all the way into this monster having to go back and forth giving cue to the bot from what I saw in the spark source code.

```

import org.apache.spark.sql.classic.SparkSession;
import org.apache.spark.sql.catalyst.analysis.*;
import org.apache.spark.sql.catalyst.catalog.*;
import org.apache.spark.sql.connector.catalog.*;
import org.apache.spark.sql.delta.catalog.DeltaCatalog;
import org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog;
import org.apache.spark.sql.internal.SessionState;
import org.apache.spark.sql.internal.SessionStateBuilder;
import org.apache.spark.sql.types.StructType;
import org.apache.spark.sql.util.CaseInsensitiveStringMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;

public class VibeCatalog extends DeltaCatalog implements SupportsNamespaces {

    private static final Logger LOG = LoggerFactory.getLogger(VibeCatalog.class);
    private String name;

    @Override
    public String name() { return this.name; }

    @Override
    public void initialize(String name, CaseInsensitiveStringMap options) {
        LOG.info("VibeCatalog.initialize({}, {})", name, options);
  
        try {
            this.name= name;
            super.initialize(name, options);

            SparkSession session = SparkSession.active();
            SessionStateBuilder builder = new SessionStateBuilder(session, scala.Option.apply(session.sessionState()));
            
            SessionCatalog isolatedV1Catalog = builder.build().catalog();

            String defaultDbName = isolatedState.conf().defaultDatabase();
            String defaultPath = options.get("warehouse")+ "/" + defaultDbName;
            
            CatalogDatabase defaultDb = new CatalogDatabase(
                defaultDbName,
                "Isolated default for " + name,
                new java.net.URI("file:" + defaultPath),
                scala.collection.immutable.Map$.MODULE$.empty()
            );
            
            isolatedV1Catalog.createDatabase(defaultDb, true);
            isolatedV1Catalog.setCurrentDatabase(defaultDbName);

            V2SessionCatalog isolatedV2Delegate = new V2SessionCatalog(isolatedV1Catalog);
            isolatedV2Delegate.initialize(name, options);
            this.setDelegateCatalog(isolatedV2Delegate);

            LOG.info("VibeCatalog.initialize done. Catalog: {} | Default DB: {}", 
                     this.catalogName, defaultDbName);
            
        } catch (Exception e) {
            LOG.error("VibeCatalog: Critical failure during isolated initialization", e);
            throw new RuntimeException(e);
        }
    }
}
```
and it still does not work. 
If I do a simple "CREATE TABLE ...." followed by sdf.writeTo(name).append() fails with table not found.

The v1catalog and v2catalog are the objects that are created for the default spark_catalog by CatalogManager and BaseSessionStateBuilder.
The whole code in SessionCatalog has the string spark_catalog hardcoded all over the place.
All the v1 APIs still return spark_catalog.
From the python side listDatabases just mixes all schemas for all catalogs. 

It's a mess. The feature to have many catalogs is half-baked and still needs a lot of work.

I give up.

**Comment by foss-contributor** [comment]
@rosspalmer, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

**Comment by felipepessoto** [comment]
The issue was confirmed by Scott, but no indication it was fixed. Not stale
