### ISSUE TITLE
[BUG][Spark] DeltaIllegalStateException: [DELTA_SPARK_SESSION_NOT_SET] Active SparkSession not set on Spark 3.5.0/Delta 3.0.0

### ISSUE THREAD

**Issue by vvararu** [delta-io/delta#2665]
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem
Working on the migration of a Delta/Spark job from EMR 6.12.0/Delta 2.4.0/Spark 3.4.0 to EMR 7.0.0/Delta 3.0.0/Spark 3.5.0. 
The job works perfect on EMR 6.12.0/Delta 2.4.0/Spark 3.4.0 and fails on the latest.

#### Steps to reproduce

1. Deploy and run the Spark/Delta job on EMR 7.0.0/Spark 3.5.0/Delta 3.0.0

2. The job fails on this line of code:
```
DeltaLog.forTable (jobContext.sparkSession (), outputPath).currentSnapshot ().snapshot ().numOfFiles ();
```

#### Observed results

The exception is thrown on the line from above:
```
org.apache.spark.sql.delta.DeltaIllegalStateException: [DELTA_SPARK_SESSION_NOT_SET] Active SparkSession not set.
	at org.apache.spark.sql.delta.DeltaErrorsBase.sparkSessionNotSetException(DeltaErrors.scala:1501) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.DeltaErrorsBase.sparkSessionNotSetException$(DeltaErrors.scala:1500) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.DeltaErrors$.sparkSessionNotSetException(DeltaErrors.scala:3039) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.util.NonFateSharingFuture.get(DeltaThreadPool.scala:94) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.CheckpointProvider$$anon$2.createCheckpointProvider(CheckpointProvider.scala:128) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.LazyCompleteCheckpointProvider.underlyingCheckpointProvider$lzycompute(CheckpointProvider.scala:409) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.LazyCompleteCheckpointProvider.underlyingCheckpointProvider(CheckpointProvider.scala:409) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.LazyCompleteCheckpointProvider.allActionsFileIndexes(CheckpointProvider.scala:415) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.fileIndices$lzycompute(Snapshot.scala:125) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.fileIndices(Snapshot.scala:124) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.loadActions(Snapshot.scala:303) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.$anonfun$stateReconstruction$1(Snapshot.scala:255) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:140) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:138) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.recordFrameProfile(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.stateReconstruction(Snapshot.scala:239) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.$anonfun$cachedState$1(Snapshot.scala:111) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:140) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:138) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.recordFrameProfile(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.cachedState$lzycompute(Snapshot.scala:109) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.cachedState(Snapshot.scala:109) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.$anonfun$stateDF$1(Snapshot.scala:177) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:140) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:138) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.recordFrameProfile(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.stateDF(Snapshot.scala:177) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.SnapshotStateManager.$anonfun$computedState$2(SnapshotState.scala:80) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:140) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:138) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.recordFrameProfile(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.SnapshotStateManager.$anonfun$computedState$1(SnapshotState.scala:78) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.util.DeltaProgressReporter.withJobDescription(DeltaProgressReporter.scala:53) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.util.DeltaProgressReporter.withStatusCode(DeltaProgressReporter.scala:32) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.util.DeltaProgressReporter.withStatusCode$(DeltaProgressReporter.scala:27) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.withStatusCode(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.SnapshotStateManager.computedState(SnapshotState.scala:78) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.SnapshotStateManager.computedState$(SnapshotState.scala:76) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.computedState$lzycompute(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.computedState(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.SnapshotStateManager.numOfFiles(SnapshotState.scala:159) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.SnapshotStateManager.numOfFiles$(SnapshotState.scala:159) ~[delta-spark.jar:3.0.0]
	at org.apache.spark.sql.delta.Snapshot.numOfFiles(Snapshot.scala:69) ~[delta-spark.jar:3.0.0]
	at com.myjobs.jobs.Ingest.call(Ingest.java:25) ~[ingestion-1.0.11.jar:?]
	at com.myjobs.jobs.Ingest.call(Ingest.java:7) ~[ingestion-1.0.11.jar:?]
	at org.apache.livy.rsc.driver.BypassJob.call(BypassJob.java:40) ~[livy-rsc-0.7.1-incubating.jar:0.7.1-incubating]
	at org.apache.livy.rsc.driver.BypassJob.call(BypassJob.java:27) ~[livy-rsc-0.7.1-incubating.jar:0.7.1-incubating]
	at org.apache.livy.rsc.driver.JobWrapper.call(JobWrapper.java:64) [livy-rsc-0.7.1-incubating.jar:0.7.1-incubating]
	at org.apache.livy.rsc.driver.BypassJobWrapper.call(BypassJobWrapper.java:45) [livy-rsc-0.7.1-incubating.jar:0.7.1-incubating]
	at org.apache.livy.rsc.driver.BypassJobWrapper.call(BypassJobWrapper.java:27) [livy-rsc-0.7.1-incubating.jar:0.7.1-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

From the exception it seems that there is no an active spark session set here (DeltaThreadPool.scala):

```
    SparkSession.getActiveSession match {
      case Some(spark) => f(spark)
      case _ => throw DeltaErrors.sparkSessionNotSetException()
    }
```

To be mentioned that such a line of code works well:
```
DeltaTable.forPath (jobContext.sparkSession (), outputPath).toDF ().count ();
```

so, it seems that there is something fishy in the:
```
DeltaLog.forTable (jobContext.sparkSession (), outputPath)...;
```

#### Expected results

The job (the line from above) to work on EMR 7.0.0/Delta 3.0.0/Spark 3.5.0 as it works on EMR 6.12.0/Delta 2.4.0/Spark 3.4.0

### Environment information

* Delta Lake version: 3.0.0
* Spark version: 3.5.0
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

**Comment by Jiaweihu08** [comment]
Any update on this issue?

**Comment by foss-contributor** [comment]
@vvararu, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
