### ISSUE TITLE
[BUG] delta lake 2.3.0 and delta-hive-assembly 0.6.0 issue

### ISSUE THREAD

**Issue by dishkakrauch** [delta-io/delta#2725]
#### Which Delta project/connector is this regarding?

- [ ] Spark 3.3.4
- [ ] delta-lake 2.3.0
- [ ] hive 3.1.3
- [ ] delta-hive-assembly 0.6.0
- [ ] scala 2.12
- [ ] hadoop/hdfs 3.2.4
- [ ] Other (fill in here)

#### Observed results

We have used hadoop/hdfs 3.1.2, spark 3.3.1, hive 3.1.3, delta lake 2.2.0, scala 2.12 and delta hive connector 0.5.0 previously and got no errors.

#### Expected results

External table shoud be created without any exception.

### Environment information

* Delta Lake version: 2.3.0
* Spark version: 3.3.4
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] No. I cannot contribute a bug fix at this time.

**Comment by sborshikovpa** [comment]
Yeah, we have the same issue!

**Comment by dishkakrauch** [comment]
I've found that hadoop 3.2.4 is using guava-27.0-jre.jar but spark 3.3.4 pom.xml still has dependency to guava-14.0.1. Is it a bug?

**Comment by dishkakrauch** [comment]
We've rebuild spark 3.5.1 with guava-27.0-jre dependency and upgraded to delta 3.1.0. Unfortunatelly, delta-hive-assembly for delta 3.1.0 throws same error.

**Comment by dishkakrauch** [comment]
BTW what is for delta-hive.jar https://github.com/delta-io/delta/tree/master/connectors#hive-connector? I saw notes about it in root delta repo but it can't find it anymore. Links here https://github.com/delta-io/delta/tree/master/connectors#hive-connector are throwing 404 error - is it okay?

**Comment by dishkakrauch** [comment]
As I see hive 3.1.3 has dependency to guava 19.0  but our hadoop was built with guava 27.0-jre - this is the main problem. Is it possible to build delta-hive-assembly with sbt and include certain guava jar to it? Didn't find any solution at documentation.

**Comment by dishkakrauch** [comment]
I've changed few rows in built.sbt delta file https://github.com/delta-io/delta/blob/master/build.sbt

```
// Versions for Hive 3
val hadoopVersionForHive3 = "3.2.4"
val hiveVersion = "3.1.3"
```

Unfortunatelly there is still error related to the unreleased method when I run hive3 test with command `build/sbt hiveMR/test hiveTez/test`

```
[info] io.delta.hive.HiveMRSuite *** ABORTED ***
[info]   java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
[info]   at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
[info]   at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
[info]   at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:536)
[info]   at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:554)
[info]   at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:448)
[info]   at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5144)
[info]   at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5102)
[info]   at io.delta.hive.test.HiveTest.beforeAll(HiveTest.scala:52)
[info]   at io.delta.hive.test.HiveTest.beforeAll$(HiveTest.scala:47)
[info]   at io.delta.hive.HiveConnectorTest.beforeAll(HiveConnectorTest.scala:29)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at io.delta.hive.HiveConnectorTest.run(HiveConnectorTest.scala:29)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:750)
[error] Uncaught exception when running io.delta.hive.HiveMRSuite: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
[error]         at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
[error]         at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
[error]         at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:536)
[error]         at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:554)
[error]         at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:448)
[error]         at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5144)
[error]         at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5102)
[error]         at io.delta.hive.test.HiveTest.beforeAll(HiveTest.scala:52)
[error]         at io.delta.hive.test.HiveTest.beforeAll$(HiveTest.scala:47)
[error]         at io.delta.hive.HiveConnectorTest.beforeAll(HiveConnectorTest.scala:29)
[error]         at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[error]         at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[error]         at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[error]         at io.delta.hive.HiveConnectorTest.run(HiveConnectorTest.scala:29)
[error]         at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[error]         at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[error]         at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[info] Run completed in 2 seconds, 456 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error]         io.delta.hive.HiveMRSuite
[error] (hiveMR / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 36 s, completed Mar 14, 2024 9:21:37 PM
```

Do anybody use delta 3.x with hdfs below 3.3.x and hive 3.1.3? I still can't build it for our cluster.

**Comment by foss-contributor** [comment]
@dishkakrauch, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
