### ISSUE TITLE
Failed to merge incompatible data types TimestampType and DateType;

### ISSUE THREAD

**Issue by abrahamdu** [delta-io/delta#320]
I am using Pyspark to load csv file to delta lake.

Here is the schema of each file after reading into cloud.

```python
root
 |-- loan_id: string (nullable = true)
 |-- origination_channel: string (nullable = true)
 |-- seller_name: string (nullable = true)
 |-- original_interest_rate: double (nullable = true)
 |-- original_upb: double (nullable = true)
 |-- original_loan_term: double (nullable = true)
 |-- origination_date: date (nullable = true)
 |-- first_payment_date: date (nullable = true)
 |-- original_ltv: double (nullable = true)
 |-- original_cltv: double (nullable = true)
 |-- number_of_borrowers: integer (nullable = true)
 |-- original_dti: double (nullable = true)
 |-- borrower_fico_at_origination: integer (nullable = true)
 |-- first_time_home_buyer_indicator: string (nullable = true)
 |-- loan_purpose: string (nullable = true)
 |-- property_type: string (nullable = true)
 |-- number_of_units: string (nullable = true)
 |-- occupancy_type: string (nullable = true)
 |-- property_state: string (nullable = true)
 |-- zip_code_short: string (nullable = true)
 |-- primary_mortgage_insurance_percent: double (nullable = true)
 |-- product_type: string (nullable = true)
 |-- coborrower_fico_at_origination: integer (nullable = true)
 |-- mortgage_insurance_type: string (nullable = true)
 |-- relocation_mortgage_indicator: string (nullable = true)
```

However, when I tried to convert each spark dataframe into delta, it shows the error message:

```python
Py4JJavaError                             Traceback (most recent call last)
/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o1977.save.
: org.apache.spark.sql.AnalysisException: Failed to merge fields 'origination_date' and 'origination_date'. Failed to merge incompatible data types TimestampType and DateType;;
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$$anonfun$18.apply(SchemaUtils.scala:685)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$$anonfun$18.apply(SchemaUtils.scala:674)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$.com$databricks$sql$transaction$tahoe$schema$SchemaUtils$$merge$1(SchemaUtils.scala:674)
	at com.databricks.sql.transaction.tahoe.schema.SchemaUtils$.mergeSchemas(SchemaUtils.scala:750)
	at com.databricks.sql.transaction.tahoe.schema.ImplicitMetadataOperation$class.updateMetadata(ImplicitMetadataOperation.scala:64)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.updateMetadata(WriteIntoDelta.scala:50)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.write(WriteIntoDelta.scala:91)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta$$anonfun$run$1$$anonfun$apply$1.apply(WriteIntoDelta.scala:71)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta$$anonfun$run$1$$anonfun$apply$1.apply(WriteIntoDelta.scala:70)
	at com.databricks.sql.transaction.tahoe.DeltaLog.withNewTransaction(DeltaLog.scala:409)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta$$anonfun$run$1.apply(WriteIntoDelta.scala:70)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta$$anonfun$run$1.apply(WriteIntoDelta.scala:69)
	at com.databricks.sql.acl.CheckPermissions$.trusted(CheckPermissions.scala:824)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.run(WriteIntoDelta.scala:69)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:128)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:147)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:188)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:184)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:118)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:710)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:710)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:240)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:97)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:170)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:710)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:306)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:292)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

AnalysisException                         Traceback (most recent call last)
<command-2501331846522968> in <module>
      6     fnma_orig_final = fnma_orig_final.withColumn('first_payment_date', to_date(unix_timestamp(col('first_payment_date'), 'MM/yyyy').cast("timestamp")))
      7     if i == 0:
----> 8       fnma_orig_final.write.format("delta").mode("overwrite").save("/mnt/mi-sa-armor/data/delta/fnma/orig")
      9     else:
     10       fnma_orig_final.write.format("delta").mode("append").save("/mnt/mi-sa-armor/data/delta/fnma/orig")

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    737             self._jwrite.save()
    738         else:
--> 739             self._jwrite.save(path)
    740 
    741     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     67                                              e.java_exception.getStackTrace()))
     68             if s.startswith('org.apache.spark.sql.AnalysisException: '):
---> 69                 raise AnalysisException(s.split(': ', 1)[1], stackTrace)
     70             if s.startswith('org.apache.spark.sql.catalyst.analysis'):
     71                 raise AnalysisException(s.split(': ', 1)[1], stackTrace)

AnalysisException: "Failed to merge fields 'origination_date' and 'origination_date'. Failed to merge incompatible data types TimestampType and DateType;;"
```

This is the code I am using:

```python
 if i == 0:
      fnma_orig_final.write.format("delta").mode("overwrite").save("/mnt/.../orig")
    else:
      fnma_orig_final.write.format("delta").mode("append").save("/mnt/.../orig")
i += 1
```

Please guide and advise. Thanks.

**Comment by tdas** [comment]
Verify what is the type of column `origination_date` in the DataFrame `fnma_orig_final`. That must be the same type as the column `origination_date` in the Delta table.

**Comment by abrahamdu** [comment]
They should be the same types as I use the same code to read into Spark for conversion.

```python
while i < len(orig_files_fnma):
    fnma_orig_final = spark.read.load(orig_files_fnma[i], format="csv", sep="|", header="false", schema=fnma_orig_schema)
    fnma_orig_final = fnma_orig_final.withColumn('origination_date', to_date(unix_timestamp(col('origination_date'), 'MM/yyyy').cast("timestamp")))
    fnma_orig_final = fnma_orig_final.withColumn('first_payment_date', to_date(unix_timestamp(col('first_payment_date'), 'MM/yyyy').cast("timestamp")))
    if i == 0:
      fnma_orig_final.write.format("delta").mode("overwrite").save("/mnt/.../orig")
    else:
      fnma_orig_final.write.format("delta").mode("append").save("/mnt/.../orig")
    i += 1
```

**Comment by tdas** [comment]
I would still print the schema to double-check. So can you print and paste the following here, so that I can see what is difference between them. 

table schema - `fnma_orig_final.read.format("delta").load("/mnt/.../orig").schema`
df schema = `fnma_orig_final.schema`

**Comment by tdas** [comment]
@abrahamdu were you able to resolve this? or get more information?

**Comment by abrahamdu** [comment]
Yes, the issue is resolved. I can append now. BTW, if I use overwrite mode, can I still use time travel to get back to old version of data?

**Comment by tdas** [comment]
Yes. Overwrites do not overwrite the table history. So you can still use time travel. 

I am closing this issue.

**Comment by asingh2796** [comment]
can you share of did you resolve this issue @abrahamdu

**Comment by scottsand-db** [comment]
@abrahamdu - are you able to share?

**Comment by mbabatope** [comment]
I literally have the same problem. How did you resolve this?

**Comment by scottsand-db** [comment]
@mbabatope can you post some details of your problem? What query are you running? What are the schemas?
