### ISSUE TITLE
Delta Azure Blob Storage **wasbs** issue

### ISSUE THREAD

**Issue by polyzos** [delta-io/delta#331]
When using spark submit to connect to the azure blob storage using **wasbs** my job fails when trying to read files as **delta** giving me the following exception:

```
20/02/27 13:22:07 WARN DeltaLog: Failed to parse wasbs://[path_to_datalake]/_delta_log/_last_checkpoint. This may happen if there was an error during read operation, or a file appears to be partial. Sleeping and trying again.
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.Wasbs not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
	at org.apache.hadoop.fs.AbstractFileSystem.createFileSystem(AbstractFileSystem.java:158)
	at org.apache.hadoop.fs.AbstractFileSystem.get(AbstractFileSystem.java:249)
	at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:334)
	at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:331)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.fs.FileContext.getAbstractFileSystem(FileContext.java:331)
	at org.apache.hadoop.fs.FileContext.getFileContext(FileContext.java:448)
	at org.apache.spark.sql.delta.storage.HDFSLogStore.getFileContext(HDFSLogStore.scala:53)
	at org.apache.spark.sql.delta.storage.HDFSLogStore.read(HDFSLogStore.scala:57)
	at org.apache.spark.sql.delta.Checkpoints$class.loadMetadataFromFile(Checkpoints.scala:139)
	at org.apache.spark.sql.delta.Checkpoints$class.lastCheckpoint(Checkpoints.scala:133)
	at org.apache.spark.sql.delta.DeltaLog.lastCheckpoint(DeltaLog.scala:58)
	at org.apache.spark.sql.delta.DeltaLog.<init>(DeltaLog.scala:139)
	at org.apache.spark.sql.delta.DeltaLog$$anon$3$$anonfun$call$1$$anonfun$apply$9.apply(DeltaLog.scala:718)
	at org.apache.spark.sql.delta.DeltaLog$$anon$3$$anonfun$call$1$$anonfun$apply$9.apply(DeltaLog.scala:718)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.delta.DeltaLog$$anon$3$$anonfun$call$1.apply(DeltaLog.scala:717)
	at org.apache.spark.sql.delta.DeltaLog$$anon$3$$anonfun$call$1.apply(DeltaLog.scala:717)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.DeltaLog$.recordOperation(DeltaLog.scala:645)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.DeltaLog$.recordDeltaOperation(DeltaLog.scala:645)
	at org.apache.spark.sql.delta.DeltaLog$$anon$3.call(DeltaLog.scala:716)
	at org.apache.spark.sql.delta.DeltaLog$$anon$3.call(DeltaLog.scala:714)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
	at org.apache.spark.sql.delta.DeltaLog$.apply(DeltaLog.scala:714)
	at org.apache.spark.sql.delta.DeltaLog$.forTable(DeltaLog.scala:686)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:167)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at tech.metis.bde.jobs.ParquetToDelta$.delayedEndpoint$tech$metis$bde$jobs$ParquetToDelta$1(ParquetToDelta.scala:14)
	at tech.metis.bde.jobs.ParquetToDelta$delayedInit$body.apply(ParquetToDelta.scala:9)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at tech.metis.bde.jobs.ParquetToDelta$.main(ParquetToDelta.scala:9)
	at tech.metis.bde.jobs.ParquetToDelta.main(ParquetToDelta.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azure.Wasbs not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
	at org.apache.hadoop.conf.Configurati
```

I have no idea why this happens, only for delta, since i thought its a class/connectivity issue, but if i change `.format("delta")` to `.format("parquet")` everything works as expected

Also this deployment is with spark-operator, from the databricks azure everything works correctly

**Comment by tdas** [comment]
This is because you are not configuring AzureLogStore when writing to Azure. See the required storage configration - https://docs.delta.io/latest/delta-storage.html . You are using the default HDFSLogStore which uses the new Hadoop FileContext APIs, not the old FileSystem APIs. When you are attempting to read wasbs using HDFSLogStore, it is failing because it wasbs does not have a FileContext implementation.

**Comment by polyzos** [comment]
@tdas Thanks a lot, everything works now.. just a question in the docs it says it needs hadoop-azure 2.9.1+ versions... I'm using 2.7.1 but everything works. Is it ok to leave it that way, or should i update it?

**Comment by tdas** [comment]
The docs talks about it directly. Specifically, Delta Lake requires the implementation of FileSystem.rename() to be atomic, which is only supported in newer Hadoop versions 
So with Hadoop 2.7.1, it will seem to work because it will write the log files, etc. but ACID properties will be broken. So you may loose data with concurrent operation because without atomic renames, the concurrent operations may overwrite each others changes when updating the transaction log.

**Comment by polyzos** [comment]
Thanks a lot for the insight
