### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crackedperson** [delta-io/delta#3372]
Delta Error Log 13-07-2024 22:07:07

File Name: C:\Users\sushi\AppData\Roaming\delta_core\error_logs\ERROR_LOG_59827037.4691.txt
HResult: -2147467259
Exception Data: System.Collections.ListDictionaryInternal
Causing Func: GetModuleInfos
Target Site: System.Diagnostics.ModuleInfo[] GetModuleInfos(Int32, Boolean)
Outer Exception Message: A 32 bit processes cannot access modules of a 64 bit process.
Outer Exception Source: System

Exception as String: System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Delta.XWindow.Inject()
   at Delta.XWindow.Button_Click_7(Object sender, RoutedEventArgs e)

**Comment by Crackedperson** [comment]
Pls tell me how to fix it

**Comment by MrPowers** [comment]
Can you please add your OS version, the Delta Lake version, and the code you're running?

This error message seems useful: "A 32 bit processes cannot access modules of a 64 bit process"

Does [this StackOverflow response](https://stackoverflow.com/questions/13974653/system-componentmodel-win32exception-when-starting-process-file-not-found-but) help?

**Comment by allisonport-db** [comment]
Closing this due to inactivity (and not sure this is even a Delta Lake bug?)
