### ISSUE TITLE
[BUG]write_delta({'custom_metadata':str}) cannot be converted. str to pyDict error (0.18.2_DeltaPython/Windows10)

### ISSUE THREAD

**Issue by starzar** [delta-io/delta#3375]
#### 0.18.2_DeltaPython/Windows10 

- [ ] Spark
- [x ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem
    write_deltalake_pyarrow(TypeError: argument 'custom_metadata': 'str' object cannot be converted to 'PyDict'
#### Steps to reproduce

```
import polars as pl
import datetime
datetime_cur = datetime.datetime.now()
datetime_cur_str = datetime_cur.strftime("%Y-%m-%d")
data = {
    "timestamp": [datetime_cur, datetime_cur + datetime.timedelta(days=1)],
    "alphabet": ["A", "B"]
}

_df = pl.DataFrame(data)

print(_df)
print('datetime_cur_str')
print(type(datetime_cur_str))
print(datetime_cur_str)
_deltapath = r'Others/Polars/tests'

# error occurs for both engines : 'engine': 'pyarrow'/'rust'
_df.write_delta(target=_deltapath, mode="overwrite", overwrite_schema=False,
                            delta_write_options={'engine': 'pyarrow', 'custom_metadata': datetime_cur_str})
```
-->

#### Observed results
```
Traceback (most recent call last):
  File "C:\Users\User_0\Documents\Code\Python\NseScraping\Others\Polars\tests\deltalake1.py", line 20, in <module>
    _df.write_delta(target=_deltapath, mode="overwrite", overwrite_schema=False,
  File "C:\Users\User_0\AppData\Local\Programs\Python\Python312\Lib\site-packages\polars\dataframe\frame.py", line 3877, in write_delta
    write_deltalake(
  File "C:\Users\User_0\AppData\Local\Programs\Python\Python312\Lib\site-packages\deltalake\writer.py", line 543, in write_deltalake
    write_deltalake_pyarrow(
TypeError: argument 'custom_metadata': 'str' object cannot be converted to 'PyDict'
```
### Environment information

* Delta Lake version:
* Spark version:
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by MrPowers** [comment]
Thanks for opening this!  Looks like this is for the delta-rs repo, going to transfer this issue now.
