### ISSUE TITLE
Unable to write on Spark Jupyter (toree) notebook

### ISSUE THREAD

**Issue by btbbass** [delta-io/delta#364]
I have a simple example that fail on a Jupyter Spark 2.4.4./Scala 2.11.12/ Java 1.8 notebook, 
trying to **write a dataframe**.
With the same notebook, **I can succesfully read a delta dataset** (created with a fat jar job)

Code:

``` scala
%AddDeps io.delta delta-core_2.11 0.5.0 --transitive --repository <myrepositories>

val data = spark.range(0, 5)
data.write.format("delta").mode("append").save("/tmp/test_1")  -> this fails

val read = spark.read.format("delta").load("/tmp/test_2") -> this is ok
```

The error stack is:

```
Name: org.apache.spark.SparkException
Message: Job aborted.
StackTrace:   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:198)
  at org.apache.spark.sql.delta.files.TransactionalWrite$$anonfun$writeFiles$1.apply(TransactionalWrite.scala:138)
  at org.apache.spark.sql.delta.files.TransactionalWrite$$anonfun$writeFiles$1.apply(TransactionalWrite.scala:130)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.delta.files.TransactionalWrite$class.writeFiles(TransactionalWrite.scala:130)
  at org.apache.spark.sql.delta.OptimisticTransaction.writeFiles(OptimisticTransaction.scala:77)
  at org.apache.spark.sql.delta.files.TransactionalWrite$class.writeFiles(TransactionalWrite.scala:103)
  at org.apache.spark.sql.delta.OptimisticTransaction.writeFiles(OptimisticTransaction.scala:77)
  at org.apache.spark.sql.delta.commands.WriteIntoDelta.write(WriteIntoDelta.scala:104)
  at org.apache.spark.sql.delta.commands.WriteIntoDelta$$anonfun$run$1.apply(WriteIntoDelta.scala:65)
  at org.apache.spark.sql.delta.commands.WriteIntoDelta$$anonfun$run$1.apply(WriteIntoDelta.scala:64)
  at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:388)
  at org.apache.spark.sql.delta.commands.WriteIntoDelta.run(WriteIntoDelta.scala:64)
  at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:131)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
  ... 44 elided
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: ClassNotFound with classloader: scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@583dc3ca
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:167)
```

Do you have any hints on what could be the root cause ?

**Comment by pranavanand** [comment]
Does this issue occur if you specify the format as something other than delta, for example could you try:

`spark.range(5).write.format("parquet").mode("append").save("/tmp/test_3")`

**Comment by btbbass** [comment]
> Does this issue occur if you specify the format as something other than delta, for example could you try:
> 
> `spark.range(5).write.format("parquet").mode("append").save("<path>")`

Hi, well this work just fine indeed!

**Comment by tdas** [comment]
This is weird. Here are a few follow up questions. 

1. Are you running your job in local spark or in a cluster? If you are trying this in a cluster, can you try it with local Spark? This would narrow down the problem to a cluster setup / spark version problem or otherwise.

2. Do you see any more errors and stack traces in the log4j logs? This stack trace does not seem to be provide the actual failure, only the follow on failure. There might other error message + stack traces saying some task failed due to this. 

3. Can you try the same with spark 2.4.3?

**Comment by apascali-1A** [comment]
1. I am running the job in a spark cluster via Jupiter notebook with Apache Toree (that provide scala spark in a notebook), that I cannot really control. I can ask for support, but it will take some time I think. I do not know how to try local Spark (unless it means on my PC with Spark 2.4.4 , this of course works just fine ). I suspect indeed that is a behaviour related to the specific configuration, even if with other libraries added (I was told, not direct experience) it works just fine.

2. In the Driver logs, the only thing I can see is:
```
ERROR FileFormatWriter: Aborting job  <UUID>
org.apache.spark.SparkException: Job aborted due to stage failure: ClassNotFound with classloader: scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@6d8346bd
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
```

No Error in the executor logs. 
**The .parquet files are correctly written as output.** 
The only missing part is the log inside the _delta_log folder (that has been created)

As a side note, I see this in the executors logs:

```
20/04/03 09:28:38 INFO Executor: Fetching spark://<host>:<port>/jars/delta-core_2.11-0.5.0.jar with timestamp 1585906110697
20/04/03 09:28:38 INFO Utils: Fetching spark://<host>:<port>/jars/delta-core_2.11-0.5.0.jar to /var/data/spark-b2820cae-c23b-43ba-8093-a261bc78137b/spark-2ac98d2b-5023-442e-bfb3-3f37cbbbfca3/fetchFileTemp3445760503930481428.tmp
20/04/03 09:28:38 INFO Utils: Copying /var/data/spark-b2820cae-c23b-43ba-8093-a261bc78137b/spark-2ac98d2b-5023-442e-bfb3-3f37cbbbfca3/-3185472021585906110697_cache to /usr/local/spark-2.4.4/work-dir/./delta-core_2.11-0.5.0.jar
20/04/03 09:28:38 INFO Executor: Adding file:/usr/local/spark-2.4.4/work-dir/./delta-core_2.11-0.5.0.jar to class loader
```
I do not know if this method differ from the **--packages** option in a spark-submit or spark-shell invocation.

3. I think it will be difficult to obtain that configuration, but I can try asking for it.

The bizarre thing is, 
**all the parquet file are written to disk but the _delta_log directory is empty.**
Error appears to be in the driver.
