### ISSUE TITLE
[Feature Request] 4.0.0rc2 release on Spark 4.0.0-preview2

### ISSUE THREAD

**Issue by Kimahriman** [delta-io/delta#3785]
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Overview

It would be great to have a new Delta release to run on Spark 4.0.0-preview2, as 4.0.0rc1 is not compatible with some new breaking changes.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by SimonYang-CS** [comment]
+1.

We can run delta 4.0.0rc1 with Spark 4.0.0-preview1, but we encounter the following error with Spark 4.0.0-preview2.

Caused by: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.Column.<init>(org.apache.spark.sql.catalyst.expressions.Expression)'

**Comment by Bidek56** [comment]
Any resolution to this error, this is the full ST. It's happening in `4.0.0rc1` Thx

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.spark.sql.Column.<init>(org.apache.spark.sql.catalyst.expressions.Expression)'
        at org.apache.spark.sql.delta.stats.DataSkippingReader$.col(DataSkippingReader.scala:173)
        at org.apache.spark.sql.delta.stats.DataSkippingReader$.<clinit>(DataSkippingReader.scala:177)
        at org.apache.spark.sql.delta.DeltaConfigsBase.$init$(DeltaConfig.scala:529)
        at org.apache.spark.sql.delta.DeltaConfigs$.<clinit>(DeltaConfig.scala:798)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.$anonfun$createDeltaTable$1(DeltaCatalog.scala:115)
        at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:168)
        at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:166)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.recordFrameProfile(DeltaCatalog.scala:65)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.org$apache$spark$sql$delta$catalog$DeltaCatalog$$createDeltaTable(DeltaCatalog.scala:95)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.$anonfun$createTable$1(DeltaCatalog.scala:321)
        at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:168)
        at org.apache.spark.sql.delta.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:166)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.recordFrameProfile(DeltaCatalog.scala:65)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.createTable(DeltaCatalog.scala:313)
        at org.apache.spark.sql.delta.catalog.DeltaCatalog.createTable(DeltaCatalog.scala:304)
        at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:46)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$2(QueryExecution.scala:126)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$6(SQLExecution.scala:155)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:267)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$1(SQLExecution.scala:118)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:742)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId0(SQLExecution.scala:74)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:222)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:126)
        at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:608)
        at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$eagerlyExecute$1(QueryExecution.scala:125)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$3.applyOrElse(QueryExecution.scala:140)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$3.applyOrElse(QueryExecution.scala:135)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:470)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:86)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:470)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:37)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:330)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:326)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:37)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:37)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:446)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:135)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:100)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:98)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:245)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$3(Dataset.scala:121)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:742)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:117)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:562)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:742)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:553)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:568)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:578)
        at spark.delta.App$.queryDelta(App.scala:89)
        at spark.delta.App$.main(App.scala:71)
        at spark.delta.App.main(App.scala)
```

**Comment by robertofierimonte** [comment]
+1

This is also impacting us.

**Comment by zcking** [comment]
+1

Not a contributor to delta or spark (but would love to be 🤗), but I'm currently trying to make a workaround locally to experiment with some of the new features using only open-source Spark + Delta.

The missing method on `Column` is may be just the tip of the iceberg, but I'll share my findings so far. From what I can tell, Spark make removed the `Column.apply(e: Expression)` constructor in the following change: https://github.com/apache/spark/commit/8fbbcb09454cbd62fdc7514ad2365200e7b123fb

The commit also mentions: 

> "This has been replaced in the source by the `ExpressionUtils.column` (implicit) method, or by the use of `Column`."

Looking further at the source, that change is _merged_ into both Spark's 1st & 2nd release candidates, **v4.0.0-rc1** and **v4.0.0-rc2**. However, [4.0.0-preview1](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/4.0.0-preview1) was _published_ June 3, 2024, before this change.

Hopefully, updating these Column constructions in the delta project and recompiling it will work 🤞

**Comment by Kimahriman** [comment]
4.0.0 is close to release so I don't think there will be any delta release at this point for preview 2. The work to get Delta compatible with latest Spark is being done in https://github.com/delta-io/delta/pull/3928 I think. Hopefully that can get merged soon and then at least Delta could be custom built with the newer spark until the official release
