### ISSUE TITLE
UNsupport create empty table with none exist location path

### ISSUE THREAD

**Issue by kaidata** [delta-io/delta#385]
just create empty by execute sql,
``` sql
CREATE TABLE events (
  date DATE,
  eventId STRING,
  eventType STRING,
  data STRING)
USING DELTA
```
error infos output like follow:
``` basic
20/04/13 11:38:00 ERROR SparkSQLDriver: Failed in [CREATE TABLE dev_lk.events124 (date DATE, eventId STRING, eventType STRING, data STRING) USING DELTA]
java.lang.IllegalArgumentException: 'path' is not specified
  at org.apache.spark.sql.delta.DeltaErrors$.pathNotSpecifiedException(DeltaErrors.scala:249)
  at org.apache.spark.sql.delta.sources.DeltaDataSource$$anonfun$9.apply(DeltaDataSource.scala:142)
  at org.apache.spark.sql.delta.sources.DeltaDataSource$$anonfun$9.apply(DeltaDataSource.scala:142)
```

- i just want to create table by schema and no data, i try to only write metadata to hdfs and create table by sql, it success; some main step like this:

- construct delta lake metadata and save to concrete path of hdfs,
```scala
import java.sql.Timestamp

import com.fasterxml.jackson.annotation.JsonInclude.Include
import com.fasterxml.jackson.databind.{DeserializationFeature, ObjectMapper}
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.fs.Path
import org.apache.spark.SparkConf
import org.apache.spark.sql.delta.actions.{CommitInfo, Metadata, SingleAction}
import org.apache.spark.sql.delta.storage.HDFSLogStore

object DeltaLogDemo {
  val hadoopConfHome = "H:\\tmp\\124hadoopConf"
  val conf = new Configuration()
  conf.addResource(new Path(String.format("file:///%s/hdfs-site.xml", hadoopConfHome)))
  conf.addResource(new Path(String.format("file:///%s/core-site.xml", hadoopConfHome)))
  val sparkConf = new SparkConf(false)
  
	// 本来可以直接调用org.apache.spark.sql.delta.util.JsonUtils#toJson, 当前出现init异常;
  val mapper = new ObjectMapper with ScalaObjectMapper
  mapper.setSerializationInclusion(Include.NON_ABSENT)
  mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
  mapper.registerModule(DefaultScalaModule)

  def main(args: Array[String]): Unit = {
    run()
  }

  def run(): Unit = {

    val commitInfo = CommitInfo(
      version = None,
      timestamp = new Timestamp(System.currentTimeMillis()),
      userId = None,
      userName = None,
      operation = "WRITE",
      operationParameters = Map("mode" -> "ErrorIfExists"
        , "partitionBy" -> "[]"
      ),
      job = None,
      notebook = None,
      clusterId = None,
      readVersion = None,
      isolationLevel = None,
      isBlindAppend = Some(true)
    )

    val metadata = Metadata(schemaString = "{\"type\":\"struct\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}}]}")
    
    val commitAction = SingleAction(commitInfo = commitInfo)
    val metadataAction = SingleAction(metaData = metadata)
    val actionIterator = Iterable(commitAction, metadataAction).iterator.map(mapper.writeValueAsString(_))

    val logStore = new HDFSLogStore(sparkConf, conf)
    val path = new Path("/tmp/delta-table/by_code/_delta_log/00000000000000000000.json")

    logStore.write(path, actionIterator, true)
  }
}
```

- create table by sql in sparksql
```sql
CREATE TABLE dev_lk.by_code USING DELTA LOCATION '/tmp/delta-table/by_code';
desc table dev_lk.by_code;
select * from dev_lk.by_code limit 3;
```
- write data to table of delta lake
```scala
println("Upsert new data")
val newData = spark.range(0, 200).toDF
val deltaTable = DeltaTable.forPath("/tmp/delta-table/by_code")

deltaTable.as("oldData").merge(newData.as("newData"), "oldData.id = newData.id")
.whenMatched.update(Map("id" -> col("newData.id")))
.whenNotMatched.insert(Map("id" -> col("newData.id"))).execute()

// 执行SQL查询数据: select * from dev_lk.by_code limit 3;
```

[the detail infos record on this blog](https://www.yuque.com/kaidata/data2prediction/gzfrys)

**Comment by kaidata** [comment]
just want to support DDL to delta lake, current design by the way of "sparksql SparkSessionExtensions"; Imitate 'io.delta.sql.parser.DeltaSqlParser'

**Comment by kaidata** [comment]
```sql
CREATE TABLE demo.empty_table (date DATE, eventId STRING, eventType STRING, data STRING) USING DELTA LOCATION '/user/spark/deltalake/demo.db/empty_table'; 
```
i think the sql should be successed, and write metadata on path `/user/spark/deltalake/demo.db/empty_table/_delta_log/00000000000000000000.json`

**Comment by brkyvz** [comment]
@kaidata Support for Hive metastore tables will be added in Spark 3.0. Older Spark versions do not have an API where Delta is passed the information that a table is being created in the Hive MetaStore such that it can create a log entry in the transaction log. With Spark 3.0 and DataSourceV2 this will be possible. 

The moment that 0.6.0 is released, we will start building Delta with Spark 3.0-preview and you'll be able to test these out.

**Comment by kaidata** [comment]
ths your point;

but how can to write dataframe to delta lake(some delta api(merge etc)) by spark sql table api(the facade)

i hava changed "org.apache.spark.sql.delta.sources.DeltaDataSource" and implement this method;
```scala
  override def createRelation(sqlContext: SQLContext,
                              parameters: Map[String, String],
                              schema: StructType): BaseRelation = {

    val path = parameters.getOrElse("path", {
      s"/tmp/delta-table/${System.currentTimeMillis()}"
    })

    val commitInfo = CommitInfo(
      time = System.currentTimeMillis(),
      operation = "WRITE",
      operationParameters = Map("mode" -> "ErrorIfExists"
        , "partitionBy" -> "[]"
      ),
      commandContext = Map.empty[String, String],
      None,
      None,
      None,
      None
    )

    val metadata = Metadata(schemaString = schema.json)

    val commitAction = SingleAction(commitInfo = commitInfo)
    val metadataAction = SingleAction(metaData = metadata)
    val actionIterator = Iterable(commitAction, metadataAction).iterator.map(JsonUtils.toJson(_))

    /**
     * dataPath, 构造元素(root_dir/db_dir/table_dir)
     */
    val logStore = DeltaLog.forTable(sqlContext.sparkSession, path)

    if (!logStore.fs.exists(logStore.logPath)) logStore.fs.mkdirs(logStore.logPath)

    logStore.store.write(FileNames.deltaFile(logStore.logPath, 0L), actionIterator, true)

    createRelation(sqlContext, parameters ++ Map("path" -> path))
  }
```

**Comment by kaidata** [comment]
i can not find a way to get database and table name, if exist the way, i can create deltalog on the path with db\table name; that i can write data to delta lake table path(eg: /root_dir/db_name/table_name); 
or other way, create table and special the location(/root_dir/db_name/table_name)

**Comment by kaidata** [comment]
if this "org.apache.spark.sql.execution.datasources.DataSource#resolveRelation" to invoke special datasource and tranform catalogTable param info, that we can do more

**Comment by kaidata** [comment]
- org.apache.spark.sql.execution.datasources.DataSource#resolveRelation
```scala
  /**
   * Create a resolved [[BaseRelation]] that can be used to read data from or write data into this
   * [[DataSource]]
   *
   * @param checkFilesExist Whether to confirm that the files exist when generating the
   *                        non-streaming file based datasource. StructuredStreaming jobs already
   *                        list file existence, and when generating incremental jobs, the batch
   *                        is considered as a non-streaming file based data source. Since we know
   *                        that files already exist, we don't need to check them again.
   */
  def resolveRelation(checkFilesExist: Boolean = true): BaseRelation = {
    val catalogTableMap = if (catalogTable.isDefined) Map("table" -> catalogTable.get.identifier.table, "database" -> catalogTable.get.database)
    else Map.empty[String, String]

    val relation = (providingClass.newInstance(), userSpecifiedSchema) match {
      // TODO: Throw when too much is given.
      case (dataSource: SchemaRelationProvider, Some(schema)) =>
        dataSource.createRelation(sparkSession.sqlContext, caseInsensitiveOptions ++ catalogTableMap, schema)
      case (dataSource: RelationProvider, None) =>
        dataSource.createRelation(sparkSession.sqlContext, caseInsensitiveOptions)
	
```

- org.apache.spark.sql.delta.sources.DeltaDataSource#createRelation
```scala
  override def createRelation(sqlContext: SQLContext,
                              parameters: Map[String, String],
                              schema: StructType): BaseRelation = {
    val db = parameters.get("database")
    val tablename = parameters.get("table")


    /**
     * dataPath, 构造元素(root_dir/db_dir/table_dir)
     */
    val path = parameters.getOrElse("path", {
      s"/user/hive/warehouse/${db.get}.db/${tablename.get}"
    })

    val commitInfo = CommitInfo(
      time = System.currentTimeMillis(),
      operation = "WRITE",
      operationParameters = Map("mode" -> "ErrorIfExists"
        , "partitionBy" -> "[]"
      ),
      commandContext = Map.empty[String, String],
      None,
      None,
      None,
      None
    )

    val metadata = Metadata(schemaString = schema.json)

    val commitAction = SingleAction(commitInfo = commitInfo)
    val metadataAction = SingleAction(metaData = metadata)
    val actionIterator = Iterable(commitAction, metadataAction).iterator.map(JsonUtils.toJson(_))

    val logStore = DeltaLog.forTable(sqlContext.sparkSession, path)

    if (!logStore.fs.exists(logStore.logPath)) logStore.fs.mkdirs(logStore.logPath)

    logStore.store.write(FileNames.deltaFile(logStore.logPath, 0L), actionIterator, true)

    createRelation(sqlContext, parameters ++ Map("path" -> path))
  }
```

**Comment by zsxwing** [comment]
Closing this. The Hive Metastore support is in 0.7.0.
