### ISSUE TITLE
[BUG] MERGE operation fails due to AnalysisException when target table contains CHAR(N) columns

### ISSUE THREAD

**Issue by clee704** [delta-io/delta#3868]
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

#### Steps to reproduce

```
create table target (id char(10), value char(10)) using delta;
create table source (id char(10), value char(10)) using parquet;
merge into target
using source on target.id = source.id
when matched then update set target.value = source.value;
```

#### Observed results

```
org.apache.spark.sql.delta.DeltaAnalysisException: [DELTA_MERGE_RESOLVED_ATTRIBUTE_MISSING_FROM_INPUT] Resolved attribute(s) id#878,id#880,value#887,id#892,value#893 missing from id#872,value#873,id#874,value#875 in operator !DeltaMergeInto (id#878 = id#880), [Update [actions: [`value` = value#887]]], [Insert [actions: [`id` = id#892, `value` = value#893]]], false, StructType(StructField(id,StringType,true),StructField(value,StringType,true)); line 2 pos 0
at org.apache.spark.sql.delta.ResolveDeltaMergeInto$.resolveReferencesAndSchema(ResolveDeltaMergeInto.scala:335)                                                                                                                                                                          at org.apache.spark.sql.delta.DeltaAnalysis$$anonfun$apply$1.applyOrElse(DeltaAnalysis.scala:547)                                                                                                                                                                                         at org.apache.spark.sql.delta.DeltaAnalysis$$anonfun$apply$1.applyOrElse(DeltaAnalysis.scala:81)
at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170)
...
```

#### Expected results

MERGE should be performed.

### Environment information

* Delta Lake version: latest (860438f97bc209296f6b55ab5311d7f3d2bf6d25)
* Spark version: 3.5.3
* Scala version: 2.12.18

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by foss-contributor** [comment]
@clee704, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

**Comment by felipepessoto** [comment]
Not stale, PR is still open
