### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.delta.util.JsonUtils$

### ISSUE THREAD

**Issue by igreenfield** [delta-io/delta#437]
When using delta to write I get that error:
```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.delta.util.JsonUtils$
	at org.apache.spark.sql.delta.DeltaOperations$Write.$anonfun$parameters$1(DeltaOperations.scala:58)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.delta.DeltaOperations$Write.<init>(DeltaOperations.scala:58)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:66)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1$adapted(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:188)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.run(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:134)
```
Using:
1. spark 2.4.5 
1. scala: 2.12 
1. delta io.delta:delta-core_2.12:0.6.1
1. Jackson 2.10.2

**Comment by liwensun** [comment]
Do you have your own Jackson dependency? Were you simply following the quick start guide or is there anything more custom to your project?

**Comment by zsxwing** [comment]
In addition, could you post the full stack trace? This error is because we fail to initialize `object com.databricks.sql.transaction.tahoe.util.JsonUtils`. Such error usually should come with a cause.

**Comment by igreenfield** [comment]
> Do you have your own Jackson dependency? Were you simply following the quick start guide or is there anything more custom to your project?

Yes we are using version 2.10.2

**Comment by igreenfield** [comment]
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.delta.util.JsonUtils$
	at org.apache.spark.sql.delta.DeltaOperations$Write.$anonfun$parameters$1(DeltaOperations.scala:58)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.delta.DeltaOperations$Write.<init>(DeltaOperations.scala:58)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:66)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1$adapted(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:188)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.run(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:134)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:677)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:677)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at com.axiomsl.execution.engine.executor.output.DeltaResultHandler.writeToDelta(DeltaResultHandler.scala:69)
	at com.axiomsl.execution.engine.executor.output.DeltaResultHandler.$anonfun$writeResult$1(DeltaResultHandler.scala:19)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.axiomsl.execution.engine.executor.output.DeltaResultHandler.writeResult(DeltaResultHandler.scala:17)
	at com.axiomsl.execution.engine.executor.graph.node.GraphExecutionNode$.$anonfun$handleWriteCommand$2(GraphExecutionNode.scala:117)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.axiomsl.execution.commons.LoggingContext.withMDC(LoggingContext.scala:29)
	at com.axiomsl.execution.engine.executor.graph.node.GraphExecutionNode$.$anonfun$handleWriteCommand$1(GraphExecutionNode.scala:115)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at com.axiomsl.common.AxiomContextExecutor$$anon$1.run(AxiomContextExecutor.scala:27)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Antauri** [comment]
Same here, prevents writing local Spark tests with Delta. Same versions as above.

**Comment by rafaelhbarros** [comment]
Facing the same error with spark 3.0.0 in EMR 6.1

**Comment by zsxwing** [comment]
@rafaelhbarros what's the version of `jackson-module-scala` and the version of Delta Lake in your environment?

**Comment by zsxwing** [comment]
I made #552 to make it easier to debug such issue.

**Comment by zsxwing** [comment]
> * delta io.delta:delta-core_2.12:0.6.1
> * Jackson 2.10.2

I recently did some work regarding this and found jackson-module-scala 2.10.0 is not binary compatible with 2.6.7.1. Delta Lake 0.6.1 was compiled with jackson-module-scala 2.6.7.1. The binary codes generated from the following line in JsonUtils cannot run with jackson-module-scala 2.10.0.

```
val mapper = new ObjectMapper with ScalaObjectMapper
```

You need to use a jackson-module-scala version that's binary compatible with 2.6.7.1.

**Comment by igreenfield** [comment]
@zsxwing Which version is binary compatible with 2.6.7.1 ??

**Comment by zsxwing** [comment]
The binary incompatibility was introduced by this change: https://github.com/FasterXML/jackson-module-scala/commit/408b5bf259bd23db67f3ddc104326dc422499dfc which was a new change in 2.10.0. Versions before 2.10.0 should work.

**Comment by zsxwing** [comment]
Closing the stale ticket. This is caused by a binary incompatibility issue from https://github.com/FasterXML/jackson-module-scala/commit/408b5bf259bd23db67f3ddc104326dc422499dfc

The solution is using a compatible jackson-module-scala version.

**Comment by kikalyan** [comment]
When writing to Delta, getting this error @zsxwing - Can you help on this?

spark 2.4.4
scala: 2.11
delta io.delta:delta-core_2.11:0.6.1
Jackson-module 2.6.7.1 or 2.9.10 (both give out same errors)

Exception:Some(java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.delta.util.JsonUtils$
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaEvent(DeltaLogging.scala:62)
	at org.apache.spark.sql.delta.DeltaOptions$.recordDeltaEvent(DeltaOptions.scala:141)
	at org.apache.spark.sql.delta.DeltaOptions$.verifyOptions(DeltaOptions.scala:183)
	at org.apache.spark.sql.delta.DeltaOptions.<init>(DeltaOptions.scala:136)
	at org.apache.spark.sql.delta.DeltaOptions.<init>(DeltaOptions.scala:138)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:131)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at com.microsoft.aip.RatedUsageStreaming.StreamProcessor.RatedUsageEventStreamProcessor$$anonfun$process$1.apply(RatedUsageEventStreamProcessor.scala:82)
	at com.microsoft.aip.RatedUsageStreaming.StreamProcessor.RatedUsageEventStreamProcessor$$anonfun$process$1.apply(RatedUsageEventStreamProcessor.scala:73)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
)
