### ISSUE TITLE
Automatic Schema Evolution issue - scala Merge API with non-trivial join condition 

### ISSUE THREAD

**Issue by rohansarin1** [delta-io/delta#473]
**Created table with schema:**
root
 |-- id: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- modifieddate: timestamp (nullable = true)

**Created a df with incremental update**
root
 |-- id: integer (nullable = false)
 |-- name: string (nullable = true)
 |-- type: string (nullable = true)
 |-- modifieddate: timestamp (nullable = true)

**When trying to merge using non-trivial join condition, it FAILS:**
df_gold.as("t")
    .merge(
      deltadf.as("s"),
      "rtrim(ltrim(lower(t.id))) = rtrim(ltrim(lower(s.id)))")
    .whenMatched().updateAll()
    .whenNotMatched().insertAll()
    .execute()

**However with a simplified condition, it works:**
   df_gold.as("t")
    .merge(
      deltadf.as("s"),
      "rtrim(t.id) = rtrim(s.id)")
    .whenMatched().updateAll()
    .whenNotMatched().insertAll()
    .execute()

**Comment by pranavanand** [comment]
How does the first case fail? Can you post a full stack trace?

**Comment by rohansarin1** [comment]
@pranavanand updated the stack trace

org.apache.spark.sql.AnalysisException: cannot resolve `type` in UPDATE clause given columns t.`id`, t.`name`, t.`modifieddate`;
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.plans.logical.DeltaMergeInto$.$anonfun$resolveReferences$3(deltaMerge.scala:276)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.sql.catalyst.plans.logical.DeltaMergeInto$.resolveOrFail$1(deltaMerge.scala:272)
	at org.apache.spark.sql.catalyst.plans.logical.DeltaMergeInto$.$anonfun$resolveReferences$9(deltaMerge.scala:384)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.catalyst.plans.logical.DeltaMergeInto$.resolveClause$1(deltaMerge.scala:311)
	at org.apache.spark.sql.catalyst.plans.logical.DeltaMergeInto$.$anonfun$resolveReferences$22(deltaMerge.scala:404)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at org.apache.spark.sql.catalyst.plans.logical.DeltaMergeInto$.resolveReferences(deltaMerge.scala:403)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$12.applyOrElse(Analyzer.scala:1609)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$12.applyOrElse(Analyzer.scala:1533)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$3(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:79)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:1533)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:1343)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:152)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:149)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:141)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:141)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:184)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:178)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:136)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:119)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:119)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:162)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:161)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:90)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:162)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:828)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:162)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:90)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:88)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:80)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:94)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:828)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:92)
	at io.delta.tables.DeltaMergeBuilder.$anonfun$execute$1(DeltaMergeBuilder.scala:239)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:230)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:18)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:275)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:268)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:18)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags0(DatabricksSparkUsageLogger.scala:59)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.withAttributionTags(DatabricksSparkUsageLogger.scala:116)
	at com.databricks.spark.util.UsageLogging.withAttributionTags(UsageLogger.scala:411)
	at com.databricks.spark.util.UsageLogging.withAttributionTags$(UsageLogger.scala:410)
	at io.delta.tables.DeltaMergeBuilder.withAttributionTags(DeltaMergeBuilder.scala:124)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordAPILang(DeltaLogging.scala:117)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordAPILang$(DeltaLogging.scala:112)
	at io.delta.tables.DeltaMergeBuilder.recordAPILang(DeltaMergeBuilder.scala:124)
	at io.delta.tables.DeltaMergeBuilder.execute(DeltaMergeBuilder.scala:239)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:4)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:72)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:74)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:76)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:78)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:80)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-185453484086206:82)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw$$iw.<init>(command-185453484086206:84)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw$$iw.<init>(command-185453484086206:86)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw$$iw.<init>(command-185453484086206:88)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$$iw.<init>(command-185453484086206:90)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read.<init>(command-185453484086206:92)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$.<init>(command-185453484086206:96)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$read$.<clinit>(command-185453484086206)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$eval$.$print$lzycompute(<notebook>:7)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$eval$.$print(<notebook>:6)
	at line3af0682478c34c3f90c47a5fbf96e8c173.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:202)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:714)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:667)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$10(DriverLocal.scala:396)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:275)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:373)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:653)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:645)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:486)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:598)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:391)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pranavanand** [comment]
What version of Delta and Spark is being used for this?
