### ISSUE TITLE
Error with Spark 3.0 & Delta table 0.7.0

### ISSUE THREAD

**Issue by junmuz** [delta-io/delta#481]
Recently I was trying updating my application to Apache 3.0 + delta table 0.7.0 relying over Scala 2.12. I have started facing this issue during the update process. Any clues? Does it refer to some bug in the library?

```
ERROR yarn.ApplicationMaster: User class threw exception: java.lang.AbstractMethodError: Receiver class org.apache.spark.sql.delta.sources.DeltaDataSource does not define or inherit an implementation of the resolved method abstract getTable(Lorg/apache/spark/sql/util/CaseInsensitiveStringMap;)Lorg/apache/spark/sql/connector/catalog/Table; of interface org.apache.spark.sql.connector.catalog.TableProvider.
java.lang.AbstractMethodError: Receiver class org.apache.spark.sql.delta.sources.DeltaDataSource does not define or inherit an implementation of the resolved method abstract getTable(Lorg/apache/spark/sql/util/CaseInsensitiveStringMap;)Lorg/apache/spark/sql/connector/catalog/Table; of interface org.apache.spark.sql.connector.catalog.TableProvider.
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:220)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:206)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)
	at io.delta.tables.DeltaTable$.forPath(DeltaTable.scala:635)
	at io.delta.tables.DeltaTable.forPath(DeltaTable.scala)
```

**Comment by zsxwing** [comment]
This looks like some classpath issue. The classpath may have multiple Delta Lake versions or Spark versions.

Are you using open source Apache Spark 3.0.0?  Line 220 in DataFrameReader.scala is a comment: https://github.com/apache/spark/blob/v3.0.0/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L220

**Comment by junmuz** [comment]
I am using open source version. Here's how my POM looks like w.r.t Spark & Pom.xml, there are some other dependencies as well.

```
<dependency>
          <groupId>io.delta</groupId>
          <artifactId>delta-core_2.12</artifactId>
          <version>0.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.12</artifactId>
            <version>3.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>2.8.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.12</artifactId>
            <version>3.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.arrow</groupId>
                    <artifactId>arrow-vector</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.arrow</groupId>
            <artifactId>arrow-vector</artifactId>
            <version>0.15.0</version>
        </dependency>
```

**Comment by zsxwing** [comment]
Could you print `spark.sparkContext.version` in your codes to show the real version used in the runtime?

**Comment by junmuz** [comment]
It appears that I was using `spark-3.0-rel` version along with the new `spark-3.0.0`, which was causing this issue. Moving to consistent version solved the problem.

**Comment by junmuz** [comment]
Thanks @zsxwing for the pointer that helped in resolving the problem.
