### ISSUE TITLE
delta log FileAlreadyExistsException on S3 delta table due to last_checkpoint

### ISSUE THREAD

**Issue by arnisd** [delta-io/delta#509]
Hi, 

I have encountered an issue in my application that updates a delta table stored in s3. EMR processes the script on a AWS cluster. 
Delta - 0.6.1
delta config - io.delta:delta-core_2.11:0.6.1
EMR - 5.30.1
Spark - 2.4.5

Application reads in a delta table, then uses a delta merge to update the table. No other script touches this table. Sample code posted below as well as the full stack trace. 

I have browsed the docs for [s3](https://docs.delta.io/latest/delta-storage.html#configure-for-s3) and viewed other issues like  #354 and #324 but this issue is occurring on writes in the middle of a merge.

Thank you. 

```

def create_or_update_visitor_lkup(views):
    visitor_lkup = views.select('visitorid', 'customer_indvid', 'customer_leadid', 'event_date').dropDuplicates(['visitorid'])
    
    try: # update the current delta table 
        
        deltaTable = DeltaTable.forPath(spark, xxxxxxxx_visitor_lkup_path)
        deltaTable.alias("old").merge(
            source = visitor_lkup.alias("updates"),
            condition = "old.visitorid = updates.visitorid"
          ).whenMatchedUpdate(set =
            {
              "customer_indvid": "updates.customer_indvid",
              "customer_leadid": "updates.customer_leadid",
              "event_date": "updates.event_date",
            }
          ).whenNotMatchedInsertAll().execute()
        print('updated visitor lkup table')
        cwlogger.write_message({"type":app_name, 
                                "group":"visitor_lkup", 
                                "message":"updated visitor lookup table",
                               })

```
`An error occurred while calling o461.execute.
: java.nio.file.FileAlreadyExistsException: s3://xxxxxxxxxxxxx-curated-prd/external/xxxxxxxx_visitor_lkup/_delta_log/_last_checkpoint
	at org.apache.spark.sql.delta.storage.HDFSLogStore.writeInternal(HDFSLogStore.scala:100)
	at org.apache.spark.sql.delta.storage.HDFSLogStore.write(HDFSLogStore.scala:64)
	at org.apache.spark.sql.delta.Checkpoints$$anonfun$checkpoint$1.apply$mcV$sp(Checkpoints.scala:122)
	at org.apache.spark.sql.delta.Checkpoints$$anonfun$checkpoint$1.apply(Checkpoints.scala:119)
	at org.apache.spark.sql.delta.Checkpoints$$anonfun$checkpoint$1.apply(Checkpoints.scala:119)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.DeltaLog.recordOperation(DeltaLog.scala:59)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.DeltaLog.recordDeltaOperation(DeltaLog.scala:59)
	at org.apache.spark.sql.delta.Checkpoints$class.checkpoint(Checkpoints.scala:119)
	at org.apache.spark.sql.delta.DeltaLog.checkpoint(DeltaLog.scala:59)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$class.postCommit(OptimisticTransaction.scala:397)
	at org.apache.spark.sql.delta.OptimisticTransaction.postCommit(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$$anonfun$commit$1.apply$mcJ$sp(OptimisticTransaction.scala:328)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$$anonfun$commit$1.apply(OptimisticTransaction.scala:284)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$$anonfun$commit$1.apply(OptimisticTransaction.scala:284)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.OptimisticTransaction.recordOperation(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.OptimisticTransaction.recordDeltaOperation(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$class.commit(OptimisticTransaction.scala:284)
	at org.apache.spark.sql.delta.OptimisticTransaction.commit(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1.apply(MergeIntoCommand.scala:160)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1.apply(MergeIntoCommand.scala:134)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:188)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1.apply(MergeIntoCommand.scala:134)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1.apply(MergeIntoCommand.scala:133)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordOperation(MergeIntoCommand.scala:93)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordDeltaOperation(MergeIntoCommand.scala:93)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.run(MergeIntoCommand.scala:133)
	at io.delta.tables.DeltaMergeBuilder.execute(DeltaMergeBuilder.scala:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Traceback (most recent call last):
  File "view_generator.py", line 625, in create_or_update_visitor_lkup
    "event_date": "updates.event_date",
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1598989274131_0413/container_1598989274131_0413_01_000001/io.delta_delta-core_2.11-0.6.1.jar/delta/tables.py", line 589, in execute
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1598989274131_0413/container_1598989274131_0413_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1598989274131_0413/container_1598989274131_0413_01_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/mnt1/yarn/usercache/hadoop/appcache/application_1598989274131_0413/container_1598989274131_0413_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o461.execute.
: java.nio.file.FileAlreadyExistsException: s3://xxxxxxxxxxx-curated-prd/external/xxxxxx_visitor_lkup/_delta_log/_last_checkpoint
	at org.apache.spark.sql.delta.storage.HDFSLogStore.writeInternal(HDFSLogStore.scala:100)
	at org.apache.spark.sql.delta.storage.HDFSLogStore.write(HDFSLogStore.scala:64)
	at org.apache.spark.sql.delta.Checkpoints$$anonfun$checkpoint$1.apply$mcV$sp(Checkpoints.scala:122)
	at org.apache.spark.sql.delta.Checkpoints$$anonfun$checkpoint$1.apply(Checkpoints.scala:119)
	at org.apache.spark.sql.delta.Checkpoints$$anonfun$checkpoint$1.apply(Checkpoints.scala:119)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.DeltaLog.recordOperation(DeltaLog.scala:59)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.DeltaLog.recordDeltaOperation(DeltaLog.scala:59)
	at org.apache.spark.sql.delta.Checkpoints$class.checkpoint(Checkpoints.scala:119)
	at org.apache.spark.sql.delta.DeltaLog.checkpoint(DeltaLog.scala:59)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$class.postCommit(OptimisticTransaction.scala:397)
	at org.apache.spark.sql.delta.OptimisticTransaction.postCommit(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$$anonfun$commit$1.apply$mcJ$sp(OptimisticTransaction.scala:328)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$$anonfun$commit$1.apply(OptimisticTransaction.scala:284)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$$anonfun$commit$1.apply(OptimisticTransaction.scala:284)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.OptimisticTransaction.recordOperation(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.OptimisticTransaction.recordDeltaOperation(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl$class.commit(OptimisticTransaction.scala:284)
	at org.apache.spark.sql.delta.OptimisticTransaction.commit(OptimisticTransaction.scala:80)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1.apply(MergeIntoCommand.scala:160)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1$$anonfun$apply$1.apply(MergeIntoCommand.scala:134)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:188)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1.apply(MergeIntoCommand.scala:134)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand$$anonfun$run$1.apply(MergeIntoCommand.scala:133)
	at com.databricks.spark.util.DatabricksLogging$class.recordOperation(DatabricksLogging.scala:77)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordOperation(MergeIntoCommand.scala:93)
	at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaOperation(DeltaLogging.scala:103)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.recordDeltaOperation(MergeIntoCommand.scala:93)
	at org.apache.spark.sql.delta.commands.MergeIntoCommand.run(MergeIntoCommand.scala:133)
	at io.delta.tables.DeltaMergeBuilder.execute(DeltaMergeBuilder.scala:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by liwensun** [comment]
@arnisd From the stack trace you are still using HDFSLogStore, have you tried to the s3 log store as suggested here:
https://github.com/delta-io/delta/issues/354#issuecomment-600245270

**Comment by travis-c-lagrone** [comment]
This issue manifests with Azure Data Lake Store as well.

**Comment by arnisd** [comment]
This has been resolved in S3 at least with the new Strong Read-After-Write Consistency addition. Thanks.
