### ISSUE TITLE
Delta Update Command Exception Cannot assign instance of scala.collection.immutable.List$SerializationProxy

### ISSUE THREAD

**Issue by cekicbaris** [delta-io/delta#620]
Hey Folks,

We tried Delta lake 0.8 for table `write` and `update` with Spark 3.0.1 in K8s. `Write` works as expected but we can not update the Delta Table and having the following error. 
```java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy 
to field org.apache.spark.sql.catalyst.expressions.objects.NewInstance.arguments of type scala.collection.Seq 
in instance of org.apache.spark.sql.catalyst.expressions.objects.NewInstance at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2372)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
at java.io.ObjectInputStream.skipCustomData(ObjectInputStream.java:2332)
...

```

Here is the environment.
`Spark 3.0.1 with Hadoop 3.2.0`
`io.delta:delta-core_2.12:0.8.0`
`org.apache.hadoop:hadoop-aws:3.2.0`
`com.amazonaws:aws-java-sdk-bundle:1.11.974`

```
import time
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = ( SparkSession.builder
         .config("spark.hadoop.fs.s3a.access.key", "<redacted>")
         .config("spark.hadoop.fs.s3a.secret.key", "<redacted>" )
         .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
         .config("spark.hadoop.fs.s3a.multiobjectdelete.enable", "false") 
         .config('spark.jars.packages', 'com.amazonaws:aws-java-sdk-bundle:1.11.974')
         .config('spark.jars.packages', 'org.apache.hadoop:hadoop-aws:3.2.0')
         .config("spark.jars.packages", "io.delta:delta-core_2.12:0.8.0") 
         .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") 
         .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
         .config("spark.delta.logStore.class","org.apache.spark.sql.delta.storage.S3SingleDriverLogStore")
         .getOrCreate()  
        )

from delta.tables import *

fileStr =  '<path>'

deltaTable = DeltaTable.forPath(spark, fileStr)
deltaTable.update("country = 'abc'", { "country": "'abc-updated'" } )

deltaTable.generate("symlink_format_manifest")
```

Could you please take a look at this?

**Comment by rahulsmahadev** [comment]
Hi @cekicbaris could you please provide the full stack trace, that would help debug the issue.

**Comment by cekicbaris** [comment]
Sure , here it is
[spark-driver.log](https://github.com/delta-io/delta/files/6150630/spark-driver.log)

**Comment by cekicbaris** [comment]
I have also tested with spark 3.1.1 but got another error. here are the driver logs. 

```
Traceback (most recent call last):
  File "/tmp/spark-a245f411-277e-4864-8082-e17dfa8e1596/job.py", line 33, in <module>
    deltaTable.update("country = 'UK'", { "country": "'UK-Updated'" } )
  File "/var/data/spark-136a45f9-8a6a-4fcb-b099-efe101bc92ca/spark-a359fd74-c5d7-4351-8804-776a94ab61c0/userFiles-8a41b87d-7a12-43bb-b222-8e777257f007/delta-core_2.12-0.8.0.jar/delta/tables.py", line 129, in update
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o82.update.
: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.catalyst.expressions.Alias.<init>(org.apache.spark.sql.catalyst.expressions.Expression, java.lang.String, org.apache.spark.sql.catalyst.expressions.ExprId, scala.collection.Seq, scala.Option)'
	at org.apache.spark.sql.delta.commands.UpdateCommand.$anonfun$buildUpdatedColumns$1(UpdateCommand.scala:221)
	``` 
[spark-311-log.log](https://github.com/delta-io/delta/files/6151413/spark-311-log.log)

**Comment by cekicbaris** [comment]
The issue is resolved by using **com.amazonaws:aws-java-sdk-bundle:1.11.974**.  It wasn't in my spark submit earlier. Sorry for the false signal.
