### ISSUE TITLE
Syntax error when navigate to another version

### ISSUE THREAD

**Issue by richiesgr** [delta-io/delta#634]
Hi

Created a table all is fine.
but when I try this 

`df_history1 = spark.sql("SELECT * FROM agg VERSION AS OF 1")`

I get 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/richardg/dist/spark-3.0.2-bin-hadoop3.2/python/pyspark/sql/session.py", line 649, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
  File "/Users/richardg/dist/spark-3.0.2-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/Users/richardg/dist/spark-3.0.2-bin-hadoop3.2/python/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "/Users/richardg/dist/spark-3.0.2-bin-hadoop3.2/python/pyspark/sql/utils.py", line 33, in raise_from
    raise e
pyspark.sql.utils.ParseException:
mismatched input 'AS' expecting {<EOF>, ';'}(line 1, pos 26)

== SQL ==
SELECT * FROM agg VERSION AS OF 1
```

working with pySpark on Spark 3.0.2 and delta lake 0.8.0.
Seems strange because all other feature works as they should 
Any idea ?

**Comment by zsxwing** [comment]
`VERSION AS OF` in SQL command is not supported in OSS Delta Lake because Spark's SQL parser doesn't support it yet. As a workaround, you can use the DataFrame APIs to do the time travel. See https://docs.delta.io/latest/quick-start.html#read-older-versions-of-data-using-time-travel

**Comment by richiesgr** [comment]
Hi
Thanks for the help. 
But I've defined the delta as hive table and I cannot see how to use API instead of SQL in this case do you have any idea ?
Thanks

**Comment by richiesgr** [comment]
Hi
I've found the way to use it on hive table you just have to know the location of the table by making 
DESCRIBE FORMATTED <table>
Then you got the data Location and you can use the API
Thanks

**Comment by taylor-schneider** [comment]
There is a relate issue tracking the addition of this feature:
https://github.com/delta-io/delta/issues/128
