### ISSUE TITLE
Unable to Update Delta Table without Columnar Predicates Created on Location with non-Safe ASCII Characters

### ISSUE THREAD

**Issue by osuleiman** [delta-io/delta#724]
When we create a Delta table on Azure (using Azure Databricks or Azure Synapse) with a location that has a non-safe ASCII character in it (e.g. space character), and then we try to run an UPDATE query on the table without using predicates or using static predicates as follows:

Statement that FAIL
UPDATE unmanaged_dummy_table SET ID = ID + 10;
UPDATE unmanaged_dummy_table SET ID = ID + 10 WHERE true;
UPDATE unmanaged_dummy_table SET ID = ID + 10 WHERE 1=1;

Statement that work
UPDATE unmanaged_dummy_table SET ID = ID + 10 WHERE ID = ID;

We received an error message which looks as follows:
```
Error: File (abfss://user@StorageName.dfs.core.windows.net/**Martin%20Bode**/Test_SparkTable/DeltaTable/part-00000-4cd8e691-f4b0-44bd-8ff4-e9ee71638932-c000.snappy.parquet) to be rewritten not found among candidate files:
abfss://user@st2xlake001x5maqlzg6ijzc.dfs.core.windows.net/Martin Bode/Test_SparkTable/DeltaTable/part-00000-4cd8e691-f4b0-44bd-8ff4-e9ee71638932-c000.snappy.parquet
abfss://user@st2xlake001x5maqlzg6ijzc.dfs.core.windows.net/Martin Bode/Test_SparkTable/DeltaTable/part-00000-7e40cddb-044c-4b50-9f5f-c09f7e76f565-c000.snappy.parquet
org.apache.spark.sql.delta.commands.DeltaCommand.$anonfun$getTouchedFile$1(DeltaCommand.scala:156)
scala.collection.immutable.Map$Map2.getOrElse(Map.scala:147)
org.apache.spark.sql.delta.commands.DeltaCommand.getTouchedFile(DeltaCommand.scala:155)
org.apache.spark.sql.delta.commands.DeltaCommand.getTouchedFile$(DeltaCommand.scala:149)
org.apache.spark.sql.delta.commands.UpdateCommand.getTouchedFile(UpdateCommand.scala:45)

As can be seen in the error, the space character was encoded into %20 in the location URI causing the comparison to fail resulting in the UPDATE command to fail. I have attached a repro IPython notebook.

[Delta_Update_Issue_Repro.zip](https://github.com/delta-io/delta/files/6901036/Delta_Update_Issue_Repro.zip)

**Comment by zsxwing** [comment]
Good catch. This is a bug in `getTouchedFile` when a Delta table path contains space characters.

**Comment by JarredParrettDickinson** [comment]
If this is still available, I would love to pick it up.

**Comment by JarredParrettDickinson** [comment]
Hi, I ended up running with it and put the following together. I have not made a formal PR yet, so any feedback is much appreciated. 

Test to replicate issue:
```scala
    @Test
    public void testUpdateTableWhenSpaceInPath() {
        Dataset<Row> targetTable = createKVDataSet(
                Arrays.asList(tuple2(1, 10), tuple2(2, 20), tuple2(3, 30), tuple2(4, 40)),
                "key", "value");
        String javaIoTmpdir = System.getProperty("java.io.tmpdir");
        String dirWithNonAscii = "/test with space/";
        String tmpDirFullPath= javaIoTmpdir.concat(dirWithNonAscii);
        String dir = Utils.createTempDir(tmpDirFullPath, "spark").toString();
        targetTable.write().format("delta").save(dir);
        spark.sql("CREATE TABLE test USING DELTA LOCATION '" +dir+ "'");
        spark.sql("UPDATE test SET key = key + 10");
        spark.sql("UPDATE test SET key = key + 10 WHERE true");
        spark.sql("UPDATE test SET key = key + 10 WHERE 1 = 1");
        spark.sql("UPDATE test SET key = key + 10 WHERE key = key");
        DeltaTable target = DeltaTable.forPath(spark, dir);
        List<Row> expectedAnswer = createKVDataSet(
                Arrays.asList(tuple2(41,10),tuple2(42, 20), tuple2(43, 30), tuple2(44, 40))).collectAsList();
        QueryTest$.MODULE$.checkAnswer(target.toDF(), expectedAnswer);
    }

```

Pre-change result: Fails on first spark SQL. Note, I included some print statements for debugging and will remove in PR
```
printing **basePath**: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-28957153-243f-40f3-bfa5-4658c0b1d52b
printing **filePath**: part-00000-c351bac6-4b39-45eb-b927-eccfda5ddec1-c000.snappy.parquet
printing **absolutePath**: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/**test%20with%20space**/spark-28957153-243f-40f3-bfa5-4658c0b1d52b/part-00000-c351bac6-4b39-45eb-b927-eccfda5ddec1-c000.snappy.parquet

java.lang.IllegalStateException: File (file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test%20with%20space/spark-28957153-243f-40f3-bfa5-4658c0b1d52b/part-00000-c351bac6-4b39-45eb-b927-eccfda5ddec1-c000.snappy.parquet) to be rewritten not found among candidate files:
file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-28957153-243f-40f3-bfa5-4658c0b1d52b/part-00000-c351bac6-4b39-45eb-b927-eccfda5ddec1-c000.snappy.parquet
file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-28957153-243f-40f3-bfa5-4658c0b1d52b/part-00001-8831b45f-fe8c-46b1-b02d-df2df4734f9f-c000.snappy.parquet

	at org.apache.spark.sql.delta.commands.DeltaCommand.$anonfun$getTouchedFile$1(DeltaCommand.scala:175)
	at scala.collection.immutable.Map$Map2.getOrElse(Map.scala:147)
	at org.apache.spark.sql.delta.commands.DeltaCommand.getTouchedFile(DeltaCommand.scala:174)
	at org.apache.spark.sql.delta.commands.DeltaCommand.getTouchedFile$(DeltaCommand.scala:165)
	at org.apache.spark.sql.delta.commands.UpdateCommand.getTouchedFile(UpdateCommand.scala:45)
```

Post-change result: For this, you will see that all cases succeed. Again, I included some print statements for debugging and will remove in PR
```
printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: part-00000-491d6b3b-782f-4ef7-b4dc-43e630641164-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-491d6b3b-782f-4ef7-b4dc-43e630641164-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: part-00001-cb4ffdc1-f893-4d40-8990-fcf97750b80b-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-cb4ffdc1-f893-4d40-8990-fcf97750b80b-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: part-00000-7e9f7bc8-aaf3-4ea7-9e79-fc9bd474e3c7-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-7e9f7bc8-aaf3-4ea7-9e79-fc9bd474e3c7-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: part-00001-12ffd4e6-3d88-4950-908a-f65e7bb63c10-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-12ffd4e6-3d88-4950-908a-f65e7bb63c10-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: part-00000-5eb26652-196c-4664-96e6-a152a8197c9b-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-5eb26652-196c-4664-96e6-a152a8197c9b-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: part-00001-eb2355c4-100b-4011-8474-91e3cc0d1db1-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-eb2355c4-100b-4011-8474-91e3cc0d1db1-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test%20with%20space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-df2d6018-861c-49c7-95cd-02c74a011781-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-df2d6018-861c-49c7-95cd-02c74a011781-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test%20with%20space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-2950eb50-f703-4561-bb58-2e83f9922af0-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-2950eb50-f703-4561-bb58-2e83f9922af0-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test%20with%20space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-df2d6018-861c-49c7-95cd-02c74a011781-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00000-df2d6018-861c-49c7-95cd-02c74a011781-c000.snappy.parquet

printing basePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe
printing filePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test%20with%20space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-2950eb50-f703-4561-bb58-2e83f9922af0-c000.snappy.parquet
printing absolutePath: file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test with space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-2950eb50-f703-4561-bb58-2e83f9922af0-c000.snappy.parquet

Process finished with exit code 0
```

My questions:

- Why does it provide the particular file name (_part-00000-491d6b3b-782f-4ef7-b4dc-43e630641164-c000.snappy.parquet_) while at other points and full file path (_file:/private/var/folders/3t/cmv_671x15s4s4lbjzb59j0h0000gn/T/test%20with%20space/spark-9b04208d-01cf-4167-8f21-01e260821dfe/part-00001-2950eb50-f703-4561-bb58-2e83f9922af0-c000.snappy.parquet_)

**Comment by zsxwing** [comment]
@JarredParrettDickinson In Delta transaction logs, we store relative paths such as `part-00000-491d6b3b-782f-4ef7-b4dc-43e630641164-c000.snappy.parquet`. When we try to find the touched files, we will use Spark's `input_file_name` function will will return a full file path.

You test case looks good. Could you write it in Scala and submit a PR?

**Comment by JarredParrettDickinson** [comment]
Sure, though it does not look like the rest in the ```UpdateScalaSuite``` as they employ the append function defined in ```UpdateSuiteBase``` that handles writes to java.io.tmpdir and the delta log created in at before each. I thought about overloading that append function with an additional param for custom path but not sure about its use beyond this. If this is clean enough, will submit a PR.

Scala version of test:
```scala
  test("update usage test - with space in path") {
    val tmpDirForTest = System.getProperty("java.io.tmpdir").concat("test with space/")
    val dirFile = Utils.createTempDir(tmpDirForTest, "spark")
    val dir = dirFile.toString
    val df = Seq((1, 10), (2, 20), (3, 30), (4, 40)).toDF("key", "value")
    val writer = df.write.format("delta").mode("append")
    writer.save(dir)
    spark.sql("CREATE TABLE test USING DELTA LOCATION '" + dir + "'")
    spark.sql("UPDATE test SET key = key + 10")
    spark.sql("UPDATE test SET key = key + 10 WHERE true")
    spark.sql("UPDATE test SET key = key + 10 WHERE 1 = 1")
    spark.sql("UPDATE test SET key = key + 10 WHERE key = key")
    checkAnswer(readDeltaTable(dir),
      Row(41, 10) :: Row(42, 20) :: Row(43, 30) :: Row(44, 40) :: Nil)
    Utils.deleteRecursively(dirFile)
  }
```

**Comment by JarredParrettDickinson** [comment]
PR made https://github.com/delta-io/delta/pull/737
