### ISSUE TITLE
Support VACUUM for Spark Thrift Server

### ISSUE THREAD

**Issue by dnskr** [delta-io/delta#739]
I run Spark Thrift Server with Delta Lake extension enabled
```
spark.sql.extensions                 io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog      org.apache.spark.sql.delta.catalog.DeltaCatalog
```
I'm able to run delta specific queries using beeline, for example
```sql
SELECT * FROM DELTA.`s3a://data/table_a`;
CREATE TABLE table_a USING DELTA LOCATION 's3a://data/table_a';
DESCRIBE HISTORY table_a;
```

But If I run `VACUUM table_a` I get the following error:
```
org.apache.hive.service.cli.HiveSQLException:
   Error running query: org.apache.spark.sql.catalyst.parser.ParseException: mismatched input 'VACUUM'
     expecting {'(', 'ADD', 'ALTER', 'ANALYZE', 'CACHE', 'CLEAR', 'COMMENT', 'COMMIT', 'CREATE', 'DELETE', 'DESC',
     'DESCRIBE', 'DFS', 'DROP', 'EXPLAIN', 'EXPORT', 'FROM', 'GRANT', 'IMPORT', 'INSERT', 'LIST', 'LOAD', 'LOCK', 'MAP', 
     'MERGE', 'MSCK', 'REDUCE', 'REFRESH', 'REPLACE', 'RESET', 'REVOKE', 'ROLLBACK', 'SELECT', 'SET', 'SHOW', 'START',
     'TABLE', 'TRUNCATE', 'UNCACHE', 'UNLOCK', 'UPDATE', 'USE', 'VALUES', 'WITH'}(line 1, pos 0)
   == SQL ==
   VACUUM table_a
```

Is it possible to avoid this exception and be able to use VACUUM command in Spark Thrift Server?

**Environment**
 - Spark 3.1.2
 - Delta Lake 1.0.0
 - Java 11

**Comment by Yaohua628** [comment]
Could you paste the full stack trace? It could be something Spark Thrift Server side should do.

**Comment by dnskr** [comment]
Hi @Yaohua628,

Sure, the full stack trace from logs:
```
21/08/10 08:01:44 INFO SparkExecuteStatementOperation: Submitting query 'VACUUM test DRY RUN;' with 94c834e3-d7b9-450e-a6bd-05d748adf6c1
21/08/10 08:01:44 INFO SparkExecuteStatementOperation: Running query with 94c834e3-d7b9-450e-a6bd-05d748adf6c1
21/08/10 08:01:44 INFO DAGScheduler: Asked to cancel job group 94c834e3-d7b9-450e-a6bd-05d748adf6c1
21/08/10 08:01:44 ERROR SparkExecuteStatementOperation: Error executing query with 94c834e3-d7b9-450e-a6bd-05d748adf6c1, currentState RUNNING, 
org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input 'VACUUM' expecting {'(', 'ADD', 'ALTER', 'ANALYZE', 'CACHE', 'CLEAR', 'COMMENT', 'COMMIT', 'CREATE', 'DELETE', 'DESC', 'DESCRIBE', 'DFS', 'DROP', 'EXPLAIN', 'EXPORT', 'FROM', 'GRANT', 'IMPORT', 'INSERT', 'LIST', 'LOAD', 'LOCK', 'MAP', 'MERGE', 'MSCK', 'REDUCE', 'REFRESH', 'REPLACE', 'RESET', 'REVOKE', 'ROLLBACK', 'SELECT', 'SET', 'SHOW', 'START', 'TABLE', 'TRUNCATE', 'UNCACHE', 'UNLOCK', 'UPDATE', 'USE', 'VALUES', 'WITH'}(line 1, pos 0)
== SQL ==
VACUUM test DRY RUN;
^^^
	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:255)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:124)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:49)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:75)
	at io.delta.sql.parser.DeltaSqlParser.$anonfun$parsePlan$1(DeltaSqlParser.scala:72)
	at io.delta.sql.parser.DeltaSqlParser.parse(DeltaSqlParser.scala:99)
	at io.delta.sql.parser.DeltaSqlParser.parsePlan(DeltaSqlParser.scala:69)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:616)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:616)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:325)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:263)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties(SparkOperation.scala:78)
	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties$(SparkOperation.scala:62)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:43)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:263)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:258)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
21/08/10 08:01:44 INFO DAGScheduler: Asked to cancel job group 94c834e3-d7b9-450e-a6bd-05d748adf6c1
21/08/10 08:01:44 INFO SparkExecuteStatementOperation: Close statement with 94c834e3-d7b9-450e-a6bd-05d748adf6c1
```

Looks like `io.delta.sql.parser.DeltaSqlParser` delegates parsing to Spark built-in parsers which don't have (and should not?) VACUUM support.

**Comment by zsxwing** [comment]
Just tested it. It's working for me:
```
Connected to: Spark SQL (version 3.1.2)
Driver: Hive JDBC (version 2.3.7)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://localhost:10000> create table myfoo using delta location '/tmp/foo';
+---------+
| Result  |
+---------+
+---------+
No rows selected (13.586 seconds)
0: jdbc:hive2://localhost:10000> vacuum myfoo;
+----------------+
|      path      |
+----------------+
| file:/tmp/foo  |
+----------------+
1 row selected (15.503 seconds)
```

My hunch is you may have multiple delta lake jars on the classpath of Spark Thrift Server. One of jars is very old is doesn't support vacuum SQL command.

**Comment by dnskr** [comment]
Thank you, @zsxwing!
I have checked it with `beeline` and it works for me as well.
My fault, I'm getting the error when I run `vacuum <table>` in IntelliJ IDEA built-in database browser. So reason of the issue is in IDE.
