### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.delta.util.JsonUtils$

### ISSUE THREAD

**Issue by kikalyan** [delta-io/delta#743]
Hello,

I was trying to use delta lake 0.6.1 on Spark 2.4 and ended up running into errors when writing to Delta table.

spark 2.4.4
scala: 2.11
delta io.delta:delta-core_2.11:0.6.1
Jackson-module 2.6.7.1 or 2.9.10 (both give out same errors)

Exception:Some(java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.delta.util.JsonUtils$
at org.apache.spark.sql.delta.metering.DeltaLogging$class.recordDeltaEvent(DeltaLogging.scala:62)
at org.apache.spark.sql.delta.DeltaOptions$.recordDeltaEvent(DeltaOptions.scala:141)
at org.apache.spark.sql.delta.DeltaOptions$.verifyOptions(DeltaOptions.scala:183)
at org.apache.spark.sql.delta.DeltaOptions.(DeltaOptions.scala:136)
at org.apache.spark.sql.delta.DeltaOptions.(DeltaOptions.scala:138)
at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:131)
at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
at com.microsoft.aip.RatedUsageStreaming.StreamProcessor.RatedUsageEventStreamProcessor$$anonfun$process$1.apply(RatedUsageEventStreamProcessor.scala:82)
at com.microsoft.aip.RatedUsageStreaming.StreamProcessor.RatedUsageEventStreamProcessor$$anonfun$process$1.apply(RatedUsageEventStreamProcessor.scala:73)
at scala.collection.Iterator$class.foreach(Iterator.scala:891)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
)

**Comment by Yaohua628** [comment]
Seems duplicate with this one: https://github.com/delta-io/delta/issues/437

**Comment by zsxwing** [comment]
@kikalyan Yep. This looks like the same as #437. What's the `jackson-module-scala` version in your project? One quick check whether you are using a correct version would be adding the following code in your application for Delta Lake 0.6 and below:

```
Class.forName("com.fasterxml.jackson.module.scala.ScalaObjectMapper")
```

This should fail if you are using a correct `jackson-module-scala` version.

**Comment by zsxwing** [comment]
Closing this due to no update
