### ISSUE TITLE
Does delta need to rely on hive to create a table? What are the requirements for hive if necessary?

### ISSUE THREAD

**Issue by study-day** [delta-io/delta#751]
question1  Does delta need to rely on hive to create a table? What are the requirements for hive if necessary?
question2  "ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8"  What is the reason for this log?

[hdfs@node-1 spark-3.1.2-bin-hadoop2.7]$ bin/spark-submit --class com.studydeltalake.Demo2 --master local[*] --jars /home/hdfs/deltalake/delta-core_2.12-1.0.0.jar  /home/hdfs/deltalake/study-deltalake-1.0-SNAPSHOT.jar
21/08/11 15:17:02 INFO SharedState: Warehouse path is 'file:/home/hdfs/spark-3.1.2-bin-hadoop2.7/spark-warehouse/'.
ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.821/08/11 15:17:03 INFO SparkUI: Stopped Spark web UI at http://hadoop-node-1:4040
21/08/11 15:17:03 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/08/11 15:17:03 INFO MemoryStore: MemoryStore cleared
21/08/11 15:17:03 INFO BlockManager: BlockManager stopped
21/08/11 15:17:03 INFO BlockManagerMaster: BlockManagerMaster stopped
21/08/11 15:17:03 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/08/11 15:17:03 INFO SparkContext: Successfully stopped SparkContext
Exception in thread "main" org.apache.spark.sql.catalyst.parser.ParseException:
no viable alternative at input 'CREATE IF'(line 1, pos 7)

== SQL ==
CREATE IF NOT EXISTS TABLE events (
-------^^^
  date DATE,
  eventId STRING,
  eventType STRING,
  data STRING)
  USING DELTA

        at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:255)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:124)
        at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:49)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:75)
        at io.delta.sql.parser.DeltaSqlParser.$anonfun$parsePlan$1(DeltaSqlParser.scala:72)
        at io.delta.sql.parser.DeltaSqlParser.parse(DeltaSqlParser.scala:99)
        at io.delta.sql.parser.DeltaSqlParser.parsePlan(DeltaSqlParser.scala:69)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:616)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:616)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/08/11 15:17:03 INFO ShutdownHookManager: Shutdown hook called
21/08/11 15:17:03 INFO ShutdownHookManager: Deleting directory /tmp/spark-0e5be116-e94e-4bb2-adf4-de42cece1a29
21/08/11 15:17:03 INFO ShutdownHookManager: Deleting directory /tmp/spark-42ee85a8-6b24-4395-8648-7e39f346c4ea

**Comment by study-day** [comment]
If hive is used, please explain directly in the docs instead of letting developers guess.
in the hive 1.2.1 it is not support  IF NOT EXISTS  ,so delta not support ?

**Comment by study-day** [comment]
If hive is used, please explain directly in the docs instead of letting developers guess.
in the hive 1.2.1 it is not support  IF NOT EXISTS  ,so delta not support ?
