### ISSUE TITLE
Confusing discrepancy between `replace` and `createOrReplace`.

### ISSUE THREAD

**Issue by madten** [delta-io/delta#827]
If I create a table like this:

```scala
import io.delta.tables._

DeltaTable
  .create(spark)
  .location("/tmp/foo")
  .addColumn("x", "integer")
  .execute()
```

I can use `replace` with different schema:

```scala
DeltaTable
  .replace(spark)
  .location("/tmp/foo")
  .addColumn("y", "string")
  .execute()
``` 

which will execute just fine and replace schema.

However, if I try `createOrReplace`:

```scala
DeltaTable
  .createOrReplace(spark)
  .location("/tmp/foo")
  .addColumn("z", "boolean")
  .execute()
```

it fails with

```
  org.apache.spark.sql.AnalysisException: The specified schema does not match the existing schema at /tmp/foo.

  == Specified ==
  root
  -- z: boolean (nullable = true)


  == Existing ==
  root
  -- y: string (nullable = true)


  == Differences==
  - Specified schema is missing field(s): y
  - Specified schema has additional field(s): z

  If your intention is to keep the existing schema, you can omit the
  schema from the create table command. Otherwise please ensure that
  the schema matches.
```

Personally, I find this behavior confusing and would expect that both would behave the same, as long as table exists.

**Comment by scottsand-db** [comment]
Hi @madten, thanks for making this issue! Would you like to make a PR to implement your suggested fix, as well as test cases to support it?

**Comment by madten** [comment]
Hi @scottsand-db. Sorry for a delayed response. I'd be happy to, but, it is the first time I am looking at the Delta source and I'd like to get some feedback from @brkyvz first. 

I checked the original commit (https://github.com/delta-io/delta/commit/5cc383496b35905d3b7911a1f3418777156464c9) but it is not exactly clear from it, why such clause was deemed to be necessary.

**Comment by brkyvz** [comment]
This does seem to be a bug. I would expect that `tableExists` returns `true` if indeed that's where the exception is thrown

**Comment by madten** [comment]
> if indeed that's where the exception is thrown

Traceback starts with

```
  at org.apache.spark.sql.delta.DeltaErrors$.createTableWithDifferentSchemaException(DeltaErrors.scala:763)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand.verifyTableMetadata(CreateDeltaTableCommand.scala:288)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand.createTransactionLogOrVerify$1(CreateDeltaTableCommand.scala:180)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand.$anonfun$run$2(CreateDeltaTableCommand.scala:194)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand$$Lambda$5173/0000000000000000.apply(Unknown Source)
  at com.databricks.spark.util.DatabricksLogging.recordOperation(DatabricksLogging.scala:77)
  at com.databricks.spark.util.DatabricksLogging.recordOperation$(DatabricksLogging.scala:67)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand.recordOperation(CreateDeltaTableCommand.scala:48)
  at org.apache.spark.sql.delta.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:106)
  at org.apache.spark.sql.delta.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:91)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand.recordDeltaOperation(CreateDeltaTableCommand.scala:48)
  at org.apache.spark.sql.delta.commands.CreateDeltaTableCommand.run(CreateDeltaTableCommand.scala:104)
  at org.apache.spark.sql.delta.catalog.DeltaCatalog.org$apache$spark$sql$delta$catalog$DeltaCatalog$$createDeltaTable(DeltaCatalog.scala:147)

```

which seems to point to `CreateDeltaTableCommand.scala:194`.

>  I would expect that `tableExists` returns `true`

This is actually confusing, because `tableExists` is define by querying the catalog, so it makes sense that it is `false` if we just have dataset written in delta format, not saves as table, right?

**Comment by pgrandjean** [comment]
Having exactly the same problem.

**Comment by pgrandjean** [comment]
I found the following solution:

```scala
import org.apache.spark.sql.connector.catalog.{Identifier, TableChange}

val spark = SparkSession.builder
          .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
          .getOrCreate()

val deltaCatalog = spark.sessionState.catalogManager.catalog("spark_catalog").asInstanceOf[DeltaCatalog]
deltaCatalog.alterTable(
  Identifier.of(Array("default"), "foo"), // changing table default.foo
  TableChange.updateColumnComment(Array("bar"), "hello") // changing column/field bar to add/update comment
)

// TableChange has methods to change a Table or its columns, like:
// setProperty
// addColumn
// deleteColumn
// updateColumn
// etc

// the table history
// +-------+--------------------+------+--------+-------------+--------------------+----+--------+---------+-----------+--------------+-------------+----------------+------------+--------------------+
// |version|           timestamp|userId|userName|    operation| operationParameters| job|notebook|clusterId|readVersion|isolationLevel|isBlindAppend|operationMetrics|userMetadata|          engineInfo|
// +-------+--------------------+------+--------+-------------+--------------------+----+--------+---------+-----------+--------------+-------------+----------------+------------+--------------------+
// |      2|2024-05-03 21:36:...|  null|    null|CHANGE COLUMN|{column -> {"name...|null|    null|     null|          1|  Serializable|         true|              {}|        null|Apache-Spark/3.4....|
// |      1|2024-05-03 21:36:...|  null|    null|CHANGE COLUMN|{column -> {"name...|null|    null|     null|          0|  Serializable|         true|              {}|        null|Apache-Spark/3.4....|
// |      0|2024-05-03 21:36:...|  null|    null| CREATE TABLE|{isManaged -> fal...|null|    null|     null|       null|  Serializable|         true|              {}|        null|Apache-Spark/3.4....|
// +-------+--------------------+------+--------+-------------+--------------------+----+--------+---------+-----------+--------------+-------------+----------------+------------+--------------------+

**Comment by pgrandjean** [comment]
Unsurprisingly the above does not work on Databricks.

**Comment by foss-contributor** [comment]
@madten, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
