### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.command.LeafRunnableCommand

### ISSUE THREAD

**Issue by yangyingjie** [delta-io/delta#854]
use delta 1.1.0 on spark 3.1.1 Error
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.command.LeafRunnableCommand

**Comment by zsxwing** [comment]
Delta 1.1.0 requires Spark 3.2.*.

**Comment by yangyingjie** [comment]
Delta 1.1.0 requires Spark 3.2.*.

**Comment by mikeweltevrede** [comment]
Unfortunately, this did not solve it for me. I have installed delta==1.1.0 and pyspark==3.2.0 in a virtual environment. Any other idea what the solution might be?

The full readout is:
```
        with tempfile.TemporaryDirectory() as tmpdir:
>           df.write.format("delta").partitionBy("Period").mode("overwrite").save(tmpdir)

preprocessing_test\data_preparation_test.py:202: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\venv\lib\site-packages\pyspark\sql\readwriter.py:740: in save
    self._jwrite.save(path)
..\..\venv\lib\site-packages\py4j\java_gateway.py:1310: in __call__
    answer, self.gateway_client, self.target_id, self.name)
..\..\venv\lib\site-packages\pyspark\sql\utils.py:111: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

answer = 'xro86'
gateway_client = <py4j.clientserver.JavaClient object at 0x000001A03134C388>
target_id = 'o85', name = 'save'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
                    raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
>                       format(target_id, ".", name), value)
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o85.save.
E                   : java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/command/LeafRunnableCommand
E                   	at java.lang.ClassLoader.defineClass1(Native Method)
E                   	at java.lang.ClassLoader.defineClass(Unknown Source)
E                   	at java.security.SecureClassLoader.defineClass(Unknown Source)
E                   	at java.net.URLClassLoader.defineClass(Unknown Source)
E                   	at java.net.URLClassLoader.access$100(Unknown Source)
E                   	at java.net.URLClassLoader$1.run(Unknown Source)
E                   	at java.net.URLClassLoader$1.run(Unknown Source)
E                   	at java.security.AccessController.doPrivileged(Native Method)
E                   	at java.net.URLClassLoader.findClass(Unknown Source)
E                   	at java.lang.ClassLoader.loadClass(Unknown Source)
E                   	at java.lang.ClassLoader.loadClass(Unknown Source)
E                   	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:148)
E                   	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
E                   	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
E                   	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
E                   	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
E                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
E                   	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
E                   	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
E                   	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
E                   	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
E                   	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
E                   	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:362)
E                   	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
E                   	at java.lang.reflect.Method.invoke(Unknown Source)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Unknown Source)
E                   Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.command.LeafRunnableCommand
E                   	at java.net.URLClassLoader.findClass(Unknown Source)
E                   	at java.lang.ClassLoader.loadClass(Unknown Source)
E                   	at java.lang.ClassLoader.loadClass(Unknown Source)
E                   	... 44 more

..\..\venv\lib\site-packages\py4j\protocol.py:328: Py4JJavaError
```

**Comment by zsxwing** [comment]
@mikeweltevrede could you print the spark version in your code to check? Such as
```
>>> print(sc.version)
3.2.0
```

**Comment by mikeweltevrede** [comment]
@zsxwing thanks for your swift response. Here is the screenshot:
![image](https://user-images.githubusercontent.com/46759318/150932114-e7cc7864-86e6-4722-8ea5-f4de19d9a041.png)

**Comment by zsxwing** [comment]
@mikeweltevrede Could you try `sc.version` or `spark.version` instead (`sc` is the spark context)? It will show the version of your Spark jar that pyspark uses. My hunch is pyspark runs with 3.2.0 python files but 3.1.x jar files. The following command can find the Spark jar location:

```
>>> print(spark._jsparkSession.getClass().getResource("/org/apache/spark/sql/SparkSession.class"))
jar:file:.../jars/spark-sql_2.12-3.2.0.jar!/org/apache/spark/sql/SparkSession.class
```

**Comment by mikeweltevrede** [comment]
@zsxwing I find the following, so you are indeed correct:

![image](https://user-images.githubusercontent.com/46759318/151509467-b19de5cf-1afd-4f0b-9679-39c536587548.png)

![image](https://user-images.githubusercontent.com/46759318/151509649-a788ac61-3348-4f9f-8f29-3237c70bcb19.png)

Is there a way to solve this?

**Comment by zsxwing** [comment]
The following command can find the Spark jar location:

```
>>> print(spark._jsparkSession.getClass().getResource("/org/apache/spark/sql/SparkSession.class"))
jar:file:.../jars/spark-sql_2.12-3.2.0.jar!/org/apache/spark/sql/SparkSession.class
```

In addition, you can also check your environment `SPARK_HOME` to see if it points to a different Spark distribution.

**Comment by mikeweltevrede** [comment]
Thank you @zsxwing - that solves my issue!
