### ISSUE TITLE
Corrupted delta on out of space

### ISSUE THREAD

**Issue by tomasbartalos** [delta-io/delta#91]
I'm running a streaming job writing to delta. Recently my disk space run out, so streaming jobs was repeatedly failing ([out_of_space.log](https://github.com/delta-io/delta/files/3381243/out_of_space.log)) with:
`Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 58.0 failed 4 times, most recent failure: Lost task 9.3 in stage 58.0 (TID 2581, 10.42.46.221, executor 2): java.io.IOException: No space left on device`

Despite this error, some streaming jobs managed to write from time to time. 
After resolving the disk space issue, I'm not able to read delta table anymore ([read_error.log](https://github.com/delta-io/delta/files/3381093/read_error.log)):
`Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/datastore/data/delta/archive/events/event_hour=20190705225/part-00001-c6369a9f-37bb-47f3-b764-3bffcf5257a5.c000.snappy.parquet at 6144 exp: -586689930 got: -1297451656`

It seems like parquet, which was not fully written was added to delta log.
Snippet of commit log for file 00000000000000033412.json:
```
{“commitInfo”:{“timestamp”:1562411477182,“operation”:“STREAMING UPDATE”,“operationParameters”:{“outputMode”:“Append”,“queryId”:“3e553a00-4b3b-4369-ad40-3f528a4d7369",“epochId”:“29609"},“readVersion”:33411}}
{“txn”:{“appId”:“3e553a00-4b3b-4369-ad40-3f528a4d7369",“version”:29609,“lastUpdated”:1562411477182}}
{“add”:{“path”:“event_hour=20190705225/part-00001-c6369a9f-37bb-47f3-b764-3bffcf5257a5.c000.snappy.parquet”,“partitionValues”:{“event_hour”:“20190705225"},“size”:12889,“modificationTime”:1562411474000,“dataChange”:true}}
```

### Parquet file

- The parquet file "part-00001-c6369a9f-37bb-47f3-b764-3bffcf5257a5.c000.snappy.parquet" has 12889 bytes - same number as written to delta log (“size”:12889).
- When I try to read the parquet with checksum file deleted I get exception:
  `IOException: Could not read footer for file`

### Code observations

- AddFile entry from commit log contains correct parquet size (12889). This is filled in [DelayedCommitProtocol.commitTask()](https://github.com/delta-io/delta/blob/ae3daa85be7cfb574a83f8d73eb10920243e4014/src/main/scala/org/apache/spark/sql/delta/files/DelayedCommitProtocol.scala#L139), this means [dataWriter.commit()](https://github.com/apache/spark/blob/c3e32bf06c35ba2580d46150923abfa795b4446a/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala#L247) had to be called 
- But still parquet was not fully written by the executor, which implies [DynamicPartitionDataWriter.write()](https://github.com/apache/spark/blob/c3e32bf06c35ba2580d46150923abfa795b4446a/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala#L245) does not handle out of space problem correctly and doesn't throw exception (?)

**Comment by zsxwing** [comment]
```
2019-07-06 11:08:12	Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 58.0 failed 4 times, most recent failure: Lost task 9.3 in stage 58.0 (TID 2581, 10.42.46.221, executor 2): java.io.IOException: No space left on device
2019-07-06 11:08:12	at java.io.FileOutputStream.close0(Native Method)
2019-07-06 11:08:12	at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
2019-07-06 11:08:12	at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
2019-07-06 11:08:12	at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
2019-07-06 11:08:12	at java.io.FileOutputStream.close(FileOutputStream.java:354)
2019-07-06 11:08:12	at org.apache.spark.storage.TimeTrackingOutputStream.close(TimeTrackingOutputStream.java:72)
2019-07-06 11:08:12	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseBufferedOutputStream$1.org$apache$spark$storage$DiskBlockObjectWriter$ManualCloseOutputStream$$super$close(DiskBlockObjectWriter.scala:106)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseOutputStream.manualClose(DiskBlockObjectWriter.scala:63)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseOutputStream.manualClose$(DiskBlockObjectWriter.scala:62)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseBufferedOutputStream$1.manualClose(DiskBlockObjectWriter.scala:106)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.$anonfun$closeResources$1(DiskBlockObjectWriter.scala:133)
2019-07-06 11:08:12	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2019-07-06 11:08:12	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.closeResources(DiskBlockObjectWriter.scala:134)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.$anonfun$close$2(DiskBlockObjectWriter.scala:156)
2019-07-06 11:08:12	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1369)
2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.close(DiskBlockObjectWriter.scala:156)
2019-07-06 11:08:12	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:157)
2019-07-06 11:08:12	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
2019-07-06 11:08:12	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
2019-07-06 11:08:12	at org.apache.spark.scheduler.Task.run(Task.scala:121)
2019-07-06 11:08:12	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
2019-07-06 11:08:12	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
2019-07-06 11:08:12	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
2019-07-06 11:08:12	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-07-06 11:08:12	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-07-06 11:08:12	at java.lang.Thread.run(Thread.java:748)
```
As per the above stack trace, this is because one of your executors was running out of disk when writing a shuffle file. This should not impact the parquet file writing.

**Comment by zsxwing** [comment]
For the checksum error, could you try to set the following spark conf to ignore the checksum file and see if you can read the table? Just to see if the parquet file is corrupted or the checksum file for this parquet file is wrong.

```
--conf spark.hadoop.fs.file.impl=org.apache.hadoop.fs.RawLocalFileSystem
```

**Comment by tomasbartalos** [comment]
> For the checksum error, could you try to set the following spark conf to ignore the checksum file and see if you can read the table? Just to see if the parquet file is corrupted or the checksum file for this parquet file is wrong.
> 
> ```
> --conf spark.hadoop.fs.file.impl=org.apache.hadoop.fs.RawLocalFileSystem
> ```
In this case I get the error mentioned in the issue:
`Caused by: java.io.IOException: Could not read footer for file`

**Comment by tomasbartalos** [comment]
> ```
> 2019-07-06 11:08:12	Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 58.0 failed 4 times, most recent failure: Lost task 9.3 in stage 58.0 (TID 2581, 10.42.46.221, executor 2): java.io.IOException: No space left on device
> 2019-07-06 11:08:12	at java.io.FileOutputStream.close0(Native Method)
> 2019-07-06 11:08:12	at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
> 2019-07-06 11:08:12	at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
> 2019-07-06 11:08:12	at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
> 2019-07-06 11:08:12	at java.io.FileOutputStream.close(FileOutputStream.java:354)
> 2019-07-06 11:08:12	at org.apache.spark.storage.TimeTrackingOutputStream.close(TimeTrackingOutputStream.java:72)
> 2019-07-06 11:08:12	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseBufferedOutputStream$1.org$apache$spark$storage$DiskBlockObjectWriter$ManualCloseOutputStream$$super$close(DiskBlockObjectWriter.scala:106)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseOutputStream.manualClose(DiskBlockObjectWriter.scala:63)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseOutputStream.manualClose$(DiskBlockObjectWriter.scala:62)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter$ManualCloseBufferedOutputStream$1.manualClose(DiskBlockObjectWriter.scala:106)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.$anonfun$closeResources$1(DiskBlockObjectWriter.scala:133)
> 2019-07-06 11:08:12	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> 2019-07-06 11:08:12	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.closeResources(DiskBlockObjectWriter.scala:134)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.$anonfun$close$2(DiskBlockObjectWriter.scala:156)
> 2019-07-06 11:08:12	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1369)
> 2019-07-06 11:08:12	at org.apache.spark.storage.DiskBlockObjectWriter.close(DiskBlockObjectWriter.scala:156)
> 2019-07-06 11:08:12	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:157)
> 2019-07-06 11:08:12	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 2019-07-06 11:08:12	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
> 2019-07-06 11:08:12	at org.apache.spark.scheduler.Task.run(Task.scala:121)
> 2019-07-06 11:08:12	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
> 2019-07-06 11:08:12	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
> 2019-07-06 11:08:12	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
> 2019-07-06 11:08:12	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 2019-07-06 11:08:12	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 2019-07-06 11:08:12	at java.lang.Thread.run(Thread.java:748)
> ```
> 
> 
> As per the above stack trace, this is because one of your executors was running out of disk when writing a shuffle file. This should not impact the parquet file writing.

The thing is, this stack trace isn't really connected to the corrupted delta. I have 4 independent streams writing to 4 deltas. Some of them are more complex and implemented with foreachBatch - the stack trace originates from this ones, but they have not been corrupted.
And 2 of them are just archivers - reading from Kafka and writing to delta. One of the archivers got corrupted.
I can't find any stack trace connected to archivers. 
This could also mean there wasn't any exception...

**Comment by mkhq** [comment]
@tomasbartalos did you solve this in the end?

**Comment by tomasbartalos** [comment]
> @tomasbartalos did you solve this in the end?

It happened on disk out of space and I didn't run to the same situation again
